In [1]:
import numpy as np
import pandas as pd

In [2]:
df=pd.read_csv('All Cancer Data/Breast.csv')
df.sample(7)

,Age recode with <1 year olds and 90+,Sex,Year of diagnosis,"Race and origin recode (NHW, NHB, NHAIAN, NHAPI, Hispanic)",Marital status at diagnosis,Primary Site,Histologic Type ICD-O-3,Combined Summary Stage with Expanded Regional Codes (2004+),Radiation recode,"Chemotherapy recode (yes, no/unk)",RX Summ--Surg Prim Site (1998-2022),Survival months,Vital status recode (study cutoff used),COD to site recode,Median household income inflation adj to 2024,Rural-Urban Continuum Code
332181,45-49 years,Female,2013,Hispanic (All Races),Single (never married),505,8500,Regional lymph nodes involved only,"Recommended, unknown if administered",Yes,51,0121,Alive,Alive,"$75,000 - $79,999",Counties in metropolitan areas ge 1 million pop
1406998,55-59 years,Female,2017,Non-Hispanic White,Married (including common law),504,8500,Regional lymph nodes involved only,Beam radiation,Yes,22,0083,Alive,Alive,"$55,000 - $59,999",Nonmetropolitan counties adjacent to a metropo...
933391,40-44 years,Female,2019,Hispanic (All Races),Married (including common law),508,8500,Regional lymph nodes involved only,Beam radiation,Yes,22,0055,Alive,Alive,"$65,000 - $69,999","Counties in metropolitan areas of 250,000 to 1..."
38887,60-64 years,Female,2010,Non-Hispanic White,Unknown,504,8500,Regional lymph nodes involved only,"Recommended, unknown if administered",No/Unknown,22,0167,Alive,Alive,"$100,000 - $109,999",Counties in metropolitan areas ge 1 million pop
63678,90+ years,Female,2018,Non-Hispanic White,Widowed,508,8500,Localized only,None/Unknown,No/Unknown,22,0064,Alive,Alive,"$120,000+",Counties in metropolitan areas ge 1 million pop
910805,55-59 years,Female,2017,Non-Hispanic Black,Widowed,505,8520,Distant site(s)/node(s) involved,None/Unknown,No/Unknown,45,0074,Alive,Alive,"$75,000 - $79,999",Counties in metropolitan areas ge 1 million pop
362256,50-54 years,Female,2021,Non-Hispanic Asian or Pacific Islander,Married (including common law),504,8500,Localized only,Beam radiation,No/Unknown,22,0025,Alive,Alive,"$120,000+",Counties in metropolitan areas ge 1 million pop

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1442083 entries, 0 to 1442082
Data columns (total 16 columns):
 #   Column                                                       Non-Null Count    Dtype
---  ------                                                       --------------    -----
 0   Age recode with <1 year olds and 90+                         1442083 non-null  object
 1   Sex                                                          1442083 non-null  object
 2   Year of diagnosis                                            1442083 non-null  int64
 3   Race and origin recode (NHW, NHB, NHAIAN, NHAPI, Hispanic)   1442083 non-null  object
 4   Marital status at diagnosis                                  1442083 non-null  object
 5   Primary Site                                                 1442083 non-null  int64
 6   Histologic Type ICD-O-3                                      1442083 non-null  int64
 7   Combined Summary Stage with Expanded Regional Codes (2004+)  1442083 non-null  object
 8   Radiation recode                                             1442083 non-null  object
 9   Chemotherapy recode (yes, no/unk)                            1442083 non-null  object
 10  RX Summ--Surg Prim Site (1998-2022)                          1442083 non-null  object
 11  Survival months                                              1442083 non-null  object
 12  Vital status recode (study cutoff used)                      1442083 non-null  object
 13  COD to site recode                                           1442083 non-null  object
 14  Median household income inflation adj to 2024                1442083 non-null  object
 15  Rural-Urban Continuum Code                                   1442083 non-null  object
dtypes: int64(3), object(13)
memory usage: 176.0+ MB

In [4]:
a=df.columns
for i in a:
    print(f'{df[i].value_counts()}')
    print(f'{df[i].value_counts().sum()}')
    print("")
    print('-------------------------------------------------------------------------------------')
    print("")

Age recode with <1 year olds and 90+
60-64 years    185149
65-69 years    184425
55-59 years    171160
70-74 years    160042
50-54 years    157092
45-49 years    133825
75-79 years    125774
80-84 years     88160
40-44 years     87846
85-89 years     51192
35-39 years     43429
90+ years       26495
30-34 years     19803
25-29 years      6482
20-24 years      1073
15-19 years       117
10-14 years        13
05-09 years         3
01-04 years         2
00 years            1
Name: count, dtype: int64
1442083

-------------------------------------------------------------------------------------

Sex
Female    1431122
Male        10961
Name: count, dtype: int64
1442083

-------------------------------------------------------------------------------------

Year of diagnosis
2023    74416
2021    73228
2022    72444
2019    70275
2018    68081
2017    66335
2016    64512
2015    64221
2020    64069
2014    62270
2013    61104
2012    59706
2011    58734
2009    56980
2010    56482
2008    55694
2007    54301
2001    52133
2006    51998
2002    51887
2005    51295
2000    51100
2004    50856
2003    49962
Name: count, dtype: int64
1442083

-------------------------------------------------------------------------------------

Race and origin recode (NHW, NHB, NHAIAN, NHAPI, Hispanic)
Non-Hispanic White                            987034
Hispanic (All Races)                          168828
Non-Hispanic Black                            146089
Non-Hispanic Asian or Pacific Islander        125058
Non-Hispanic American Indian/Alaska Native      8413
Non-Hispanic Unknown Race                       6661
Name: count, dtype: int64
1442083

-------------------------------------------------------------------------------------

Marital status at diagnosis
Married (including common law)    777078
Widowed                           218388
Single (never married)            208680
Divorced                          150482
Unknown                            67362
Separated                          15148
Unmarried or Domestic Partner       4945
Name: count, dtype: int64
1442083

-------------------------------------------------------------------------------------

Primary Site
504    471904
508    315244
509    219184
502    165012
505    102065
503     76985
501     74623
500      8777
506      8289
Name: count, dtype: int64
1442083

-------------------------------------------------------------------------------------

Histologic Type ICD-O-3
8500    1050885
8520     133237
8522      82717
8523      31263
8480      29320
         ...
8263          1
8990          1
9231          1
9064          1
8891          1
Name: count, Length: 191, dtype: int64
1442083

-------------------------------------------------------------------------------------

Combined Summary Stage with Expanded Regional Codes (2004+)
Localized only                                                  789407
Regional lymph nodes involved only                              277756
Blank(s)                                                        205082
Distant site(s)/node(s) involved                                 72003
Regional by both direct extension and lymph node involvement     43464
Unknown/unstaged/unspecified/DCO                                 30152
Regional by direct extension only                                24206
In situ                                                             13
Name: count, dtype: int64
1442083

-------------------------------------------------------------------------------------

Radiation recode
Beam radiation                                           676318
None/Unknown                                             667900
Refused (1988+)                                           37043
Recommended, unknown if administered                      31561
Radioactive implants (includes brachytherapy) (1988+)     20272
Radiation, NOS  method or source not specified             6311
Combination of beam with implants or isotopes              2245
Radioisotopes (1988+)                                       433
Name: count, dtype: int64
1442083

-------------------------------------------------------------------------------------

Chemotherapy recode (yes, no/unk)
No/Unknown    893621
Yes           548462
Name: count, dtype: int64
1442083

-------------------------------------------------------------------------------------

RX Summ--Surg Prim Site (1998-2022)
22          442773
51          151147
00          127850
41          127163
23          122012
Blank(s)     74416
20           68130
24           55546
42           35555
40           23430
52           21682
30           20790
49           19217
50           18393
45           17600
44           13807
48           12592
99           10580
47           10105
43            9021
54            7400
55            6972
59            6065
46            5133
21            4639
58            4191
80            4168
53            4059
75            3686
57            3340
56            2153
61            2022
90            1846
63            1333
62             783
60             620
19             242
64             229
65             216
76             203
68             158
69             148
66             120
72             115
74             115
71             100
73              89
67              77
70              52
Name: count, dtype: int64
1442083

-------------------------------------------------------------------------------------

Survival months
0000    17327
0001    13582
0002    12843
0004    12413
0006    11563
        ...
0278     1362
0286     1349
0284     1334
0281     1323
0287     1256
Name: count, Length: 289, dtype: int64
1442083

-------------------------------------------------------------------------------------

Vital status recode (study cutoff used)
Alive    960820
Dead     481263
Name: count, dtype: int64
1442083

-------------------------------------------------------------------------------------

COD to site recode
Alive                       960820
Breast                      200107
Diseases of Heart            64270
Other Cause of Death         52363
Cerebrovascular Diseases     17122
                             ...
Lip                              7
Floor of Mouth                   6
Penis                            2
Syphilis                         1
Testis                           1
Name: count, Length: 92, dtype: int64
1442083

-------------------------------------------------------------------------------------

Median household income inflation adj to 2024
$75,000 - $79,999                         177134
$100,000 - $109,999                       158298
$85,000 - $89,999                         135031
$120,000+                                 133187
$80,000 - $84,999                         129038
$110,000 - $119,999                       112520
$90,000 - $94,999                         109418
$70,000 - $74,999                         101369
$65,000 - $69,999                          94977
$95,000 - $99,999                          88796
$60,000 - $64,999                          59728
$55,000 - $59,999                          53679
$50,000 - $54,999                          43129
$45,000 - $49,999                          23364
$40,000 - $44,999                          13432
< $40,000                                   8677
Unknown/missing/no match/Not 1990-2024       306
Name: count, dtype: int64
1442083

-------------------------------------------------------------------------------------

Rural-Urban Continuum Code
Counties in metropolitan areas ge 1 million pop                 884803
Counties in metropolitan areas of 250,000 to 1 million pop      295319
Counties in metropolitan areas of lt 250 thousand pop           107173
Nonmetropolitan counties adjacent to a metropolitan area         92174
Nonmetropolitan counties not adjacent to a metropolitan area     60686
Unknown/missing/no match (Alaska or Hawaii - Entire State)        1622
Unknown/missing/no match/Not 1990-2024                             306
Name: count, dtype: int64
1442083

-------------------------------------------------------------------------------------

In [5]:
b=df.columns
for i in b:
    print(f'{df[i].unique()}')
    print("")
    print('-------------------------------------------------------------------------------------')
    print("")

['75-79 years' '70-74 years' '60-64 years' '40-44 years' '35-39 years'
 '50-54 years' '80-84 years' '55-59 years' '85-89 years' '30-34 years'
 '65-69 years' '90+ years' '45-49 years' '25-29 years' '20-24 years'
 '15-19 years' '01-04 years' '10-14 years' '05-09 years' '00 years']

-------------------------------------------------------------------------------------

['Female' 'Male']

-------------------------------------------------------------------------------------

[2003 2010 2018 2023 2005 2001 2015 2002 2004 2013 2012 2014 2011 2009
 2017 2021 2000 2016 2007 2006 2019 2020 2022 2008]

-------------------------------------------------------------------------------------

['Non-Hispanic White' 'Non-Hispanic Black' 'Hispanic (All Races)'
 'Non-Hispanic Asian or Pacific Islander'
 'Non-Hispanic American Indian/Alaska Native' 'Non-Hispanic Unknown Race']

-------------------------------------------------------------------------------------

['Divorced' 'Single (never married)' 'Married (including common law)'
 'Widowed' 'Unknown' 'Separated' 'Unmarried or Domestic Partner']

-------------------------------------------------------------------------------------

[506 509 508 504 501 502 503 505 500]

-------------------------------------------------------------------------------------

[8520 8500 8513 8522 8010 8530 8480 8140 8523 8510 8540 8507 9150 8541
 8046 8543 8211 8575 8501 8000 9120 8200 9020 8524 8201 8503 8504 8560
 8542 8401 8050 8070 8574 8801 8260 8255 8509 8490 8343 8521 8071 8481
 8246 8022 8013 8323 8032 8502 8894 8001 8021 8012 8041 8141 8230 8980
 8800 8512 8570 8315 8314 9180 8810 8983 9220 8573 8935 8430 8035 8033
 8890 8830 8920 8802 8804 8020 8407 8123 8940 8805 8832 8005 8249 8453
 8514 8344 8550 8243 8982 8572 8244 8571 8240 8811 8562 8525 8720 8858
 8310 9183 8074 9581 8082 8963 8031 8147 8851 8052 8072 8825 8015 8410
 8102 8452 8251 8320 8470 8850 8003 9044 8004 9181 9041 8803 8265 8154
 9260 8030 8413 9040 8440 8340 8854 8836 8815 8076 8714 8859 8110 9561
 8083 9133 8130 8895 8450 8382 8933 8350 8852 9473 8840 8247 8581 9580
 8900 8855 8912 9540 8014 8743 8075 8210 9071 9170 8896 8910 9500 8190
 8090 8950 8042 8290 8471 8253 8482 8045 9364 8263 8814 9100 9182 9186
 8508 8901 8341 8460 8990 8011 9231 9064 8891]

-------------------------------------------------------------------------------------

['Blank(s)' 'Localized only' 'Regional by direct extension only'
 'Regional lymph nodes involved only' 'Unknown/unstaged/unspecified/DCO'
 'Regional by both direct extension and lymph node involvement'
 'Distant site(s)/node(s) involved' 'In situ']

-------------------------------------------------------------------------------------

['None/Unknown' 'Beam radiation' 'Refused (1988+)'
 'Recommended, unknown if administered'
 'Radioactive implants (includes brachytherapy) (1988+)'
 'Radiation, NOS  method or source not specified'
 'Combination of beam with implants or isotopes' 'Radioisotopes (1988+)']

-------------------------------------------------------------------------------------

['No/Unknown' 'Yes']

-------------------------------------------------------------------------------------

['22' '80' 'Blank(s)' '41' '23' '51' '44' '00' '45' '20' '30' '58' '50'
 '53' '43' '75' '52' '42' '49' '40' '48' '46' '24' '66' '47' '55' '61'
 '56' '54' '21' '64' '99' '59' '76' '60' '63' '62' '90' '57' '73' '19'
 '67' '74' '70' '65' '72' '69' '71' '68']

-------------------------------------------------------------------------------------

['0014' '0012' '0070' '0011' '0081' '0007' '0272' '0010' '0096' '0050'
 '0130' '0028' '0135' '0117' '0089' '0216' '0122' '0240' '0017' '0225'
 '0015' '0143' '0082' '0031' '0087' '0066' '0184' '0062' '0209' '0161'
 '0072' '0194' '0000' '0043' '0019' '0068' '0052' '0029' '0230' '0032'
 '0106' '0151' '0055' '0034' '0098' '0053' '0030' '0020' '0018' '0271'
 '0080' '0021' '0049' '0201' '0092' '0048' '0270' '0042' '0142' '0001'
 '0023' '0076' '0065' '0181' '0024' '0044' '0199' '0102' '0131' '0103'
 '0104' '0113' '0120' '0164' '0005' '0220' '0016' '0067' '0086' '0287'
 '0133' '0222' '0155' '0006' '0083' '0121' '0198' '0059' '0071' '0039'
 '0002' '0144' '0033' '0013' '0004' '0040' '0085' '0009' '0100' '0008'
 '0153' '0025' '0171' '0234' '0022' '0116' '0152' '0266' '0097' '0057'
 '0218' '0073' '0208' '0263' '0258' '0163' '0259' '0170' '0146' '0202'
 '0141' '0191' '0159' '0099' '0091' '0035' '0134' '0056' '0109' '0118'
 '0107' '0075' '0126' '0197' '0213' '0269' '0136' '0069' '0282' '0051'
 '0088' '0204' '0200' '0183' '0254' '0260' '0138' '0123' '0241' '0045'
 '0173' '0125' '0145' '0235' '0275' '0128' '0168' '0160' '0105' '0167'
 '0176' '0203' '0061' '0047' '0094' '0190' '0251' '0112' '0037' '0172'
 '0150' '0196' '0157' '0137' '0186' '0285' '0139' '0095' '0249' '0093'
 '0127' '0284' '0046' '0193' '0147' '0074' '0156' '0064' '0026' '0255'
 '0060' '0195' '0265' '0054' '0267' '0174' '0038' '0273' '0250' '0227'
 '0280' '0041' '0221' '0281' '0036' '0192' '0229' '0140' '0187' '0179'
 '0210' '0239' '0158' '0132' '0058' '0215' '0154' '0246' '0226' '0261'
 '0149' '0078' '0224' '0148' '0111' '0206' '0003' '0188' '0252' '0063'
 '0175' '0079' '0214' '0129' '0205' '0211' 'Unknown' '0027' '0165' '0256'
 '0166' '0077' '0207' '0090' '0189' '0108' '0247' '0223' '0264' '0162'
 '0212' '0180' '0182' '0257' '0084' '0236' '0178' '0238' '0237' '0268'
 '0274' '0219' '0110' '0119' '0185' '0114' '0217' '0243' '0283' '0169'
 '0244' '0278' '0279' '0115' '0101' '0286' '0231' '0124' '0245' '0177'
 '0232' '0228' '0253' '0262' '0233' '0242' '0277' '0276' '0248']

-------------------------------------------------------------------------------------

['Dead' 'Alive']

-------------------------------------------------------------------------------------

['Breast' 'Diseases of Heart' 'Alive' 'Alzheimers (ICD-9 and 10 only)'
 'Other Infectious and Parasitic Diseases including HIV'
 'Other Cause of Death' 'Corpus Uteri' 'Cerebrovascular Diseases'
 'Chronic Liver Disease and Cirrhosis'
 'Hypertension without Heart Disease' 'Lung and Bronchus' 'Septicemia'
 'Soft Tissue including Heart' 'Pneumonia and Influenza'
 'Brain and Other Nervous System' 'Atherosclerosis'
 'Chronic Obstructive Pulmonary Disease and Allied Cond'
 'Colon excluding Rectum' 'Stomach and Duodenal Ulcers' 'Liver' 'Ovary'
 'Non-Hodgkin Lymphoma' 'Accidents and Adverse Effects'
 'State DC not available or state DC available but no COD'
 'Acute Myeloid Leukemia' 'Hodgkin Lymphoma'
 'Miscellaneous Malignant Cancer'
 'Nephritis, Nephrotic Syndrome and Nephrosis' 'Pancreas'
 'In situ, benign or unknown behavior neoplasm' 'Congenital Anomalies'
 'Myeloma' 'Non-Melanoma Skin' 'Urinary Bladder' 'Other Digestive Organs'
 'Nasopharynx' 'Kidney and Renal Pelvis' 'Vulva' 'Melanoma of the Skin'
 'Diabetes Mellitus' 'Bones and Joints' 'Rectum and Rectosigmoid Junction'
 'Stomach' 'Symptoms, Signs and Ill-Defined Conditions' 'Esophagus'
 'Aleukemic, Subleukemic and NOS' 'Uterus, NOS' 'Intrahepatic Bile Duct'
 'Aortic Aneurysm and Dissection'
 'Other Diseases of Arteries, Arterioles, Capillaries'
 'Other Endocrine including Thymus' 'Thyroid'
 'Suicide and Self-Inflicted Injury' 'Other Female Genital Organs'
 'Chronic Lymphocytic Leukemia' 'Gallbladder' 'Eye and Orbit' 'Lip'
 'Cervix Uteri' 'Other Acute Leukemia' 'Anus, Anal Canal and Anorectum'
 'Other Urinary Organs' 'Tuberculosis' 'Small Intestine' 'Other Biliary'
 'Hypopharynx' 'Chronic Myeloid Leukemia' 'Acute Monocytic Leukemia'
 'Retroperitoneum' 'Ureter' 'Peritoneum, Omentum and Mesentery'
 'Other Oral Cavity and Pharynx' 'Larynx' 'Prostate'
 'Other Myeloid/Monocytic Leukemia'
 'Trachea, Mediastinum and Other Respiratory Organs' 'Salivary Gland'
 'Tongue' 'Homicide and Legal Intervention' 'Acute Lymphocytic Leukemia'
 'Vagina' 'Gum and Other Mouth' 'Pleura'
 'Complications of Pregnancy, Childbirth, Puerperium'
 'Other Lymphocytic Leukemia' 'Oropharynx' 'Syphilis'
 'Nose, Nasal Cavity and Middle Ear' 'Tonsil' 'Floor of Mouth' 'Penis'
 'Testis']

-------------------------------------------------------------------------------------

['$110,000 - $119,999' '$95,000 - $99,999' '$120,000+'
 '$100,000 - $109,999' 'Unknown/missing/no match/Not 1990-2024'
 '$85,000 - $89,999' '$90,000 - $94,999' '$80,000 - $84,999'
 '$75,000 - $79,999' '$70,000 - $74,999' '$65,000 - $69,999' '< $40,000'
 '$60,000 - $64,999' '$55,000 - $59,999' '$50,000 - $54,999'
 '$45,000 - $49,999' '$40,000 - $44,999']

-------------------------------------------------------------------------------------

['Counties in metropolitan areas ge 1 million pop'
 'Unknown/missing/no match/Not 1990-2024'
 'Counties in metropolitan areas of 250,000 to 1 million pop'
 'Nonmetropolitan counties adjacent to a metropolitan area'
 'Nonmetropolitan counties not adjacent to a metropolitan area'
 'Counties in metropolitan areas of lt 250 thousand pop'
 'Unknown/missing/no match (Alaska or Hawaii - Entire State)']

-------------------------------------------------------------------------------------

*Demographical Variables*

In [6]:
#Changed data type of age to string 
df['Age recode with <1 year olds and 90+']=df['Age recode with <1 year olds and 90+'].astype(str)
#Remover 'years' from '70-75 years'
df['Age recode with <1 year olds and 90+']=df['Age recode with <1 year olds and 90+'].str.strip(' years')

#'70-75' -> |70| |75|

age_lower = df['Age recode with <1 year olds and 90+'].str.replace('+', '', regex=False).str.split('-').str[0].astype(int)
age_upper = df['Age recode with <1 year olds and 90+'].str.replace('+', '', regex=False).str.split('-').str[-1].astype(int)

#Created a variable age which stores mid point of given age for calculation on age (mean age etc.)

df['Age']=(age_lower+age_upper)/2
df.sample(7)

,Age recode with <1 year olds and 90+,Sex,Year of diagnosis,"Race and origin recode (NHW, NHB, NHAIAN, NHAPI, Hispanic)",Marital status at diagnosis,Primary Site,Histologic Type ICD-O-3,Combined Summary Stage with Expanded Regional Codes (2004+),Radiation recode,"Chemotherapy recode (yes, no/unk)",RX Summ--Surg Prim Site (1998-2022),Survival months,Vital status recode (study cutoff used),COD to site recode,Median household income inflation adj to 2024,Rural-Urban Continuum Code,Age
634847,55-59,Female,2020,Non-Hispanic White,Single (never married),502,8500,Distant site(s)/node(s) involved,None/Unknown,Yes,00,0016,Alive,Alive,"$85,000 - $89,999",Counties in metropolitan areas ge 1 million pop,57.0
531770,55-59,Female,2003,Non-Hispanic Black,Married (including common law),502,8500,Blank(s),Beam radiation,Yes,22,0246,Alive,Alive,"$75,000 - $79,999",Counties in metropolitan areas ge 1 million pop,57.0
429206,55-59,Female,2010,Non-Hispanic White,Married (including common law),504,8500,Localized only,Beam radiation,No/Unknown,22,0157,Alive,Alive,"$80,000 - $84,999",Counties in metropolitan areas ge 1 million pop,57.0
709688,30-34,Female,2002,Non-Hispanic White,Married (including common law),509,8500,Blank(s),Beam radiation,Yes,51,0010,Dead,State DC not available or state DC available b...,"$75,000 - $79,999","Counties in metropolitan areas of 250,000 to 1...",32.0
505294,85-89,Female,2011,Non-Hispanic White,Married (including common law),509,8500,Localized only,None/Unknown,Yes,41,0136,Alive,Alive,"$75,000 - $79,999",Counties in metropolitan areas ge 1 million pop,87.0
1187458,40-44,Female,2002,Non-Hispanic Black,Single (never married),504,8500,Blank(s),None/Unknown,No/Unknown,50,0047,Dead,Breast,"$80,000 - $84,999",Counties in metropolitan areas ge 1 million pop,42.0
585555,75-79,Female,2021,Non-Hispanic White,Single (never married),508,8500,Localized only,Beam radiation,No/Unknown,22,0034,Alive,Alive,"$90,000 - $94,999",Counties in metropolitan areas ge 1 million pop,77.0

*Tumor*

In [7]:
#Replacing the site code with their actual Anatomical site 

primary_sites = {
    500: "Nipple and areola",
    501: "Central portion of breast",
    502: "Upper-inner quadrant of breast",
    503: "Lower-inner quadrant of breast",
    504: "Upper-outer quadrant of breast",
    505: "Lower-outer quadrant of breast",
    506: "Axillary tail of breast",
    508: "Overlapping lesion of breast",
    509: "Breast, NOS (Not Otherwise Specified)"
}
df['Primary Site'] = df['Primary Site'].map(primary_sites)
df['Cancer_type']='Breast'

In [8]:
#Histology codes are replaced with Their Histological family group name.

bins =   [0, 8049, 8139, 8349, 8549, 8799, 9999]


#Bins work as intervals and labels as value of the code if it falls in that bin.
# If Histologuy code falls between 7999 to 8009 then it will replace it with 'Neoplasms, NOS'.

labels = ["Carcinoma NOS", "Squamous Cell", "Adenocarcinoma",
          "Ductal/Lobular", "Sarcoma/Rare", "Other"]

df['Histologic Type ICD-O-3'] = pd.cut(
    pd.to_numeric(df['Histologic Type ICD-O-3'], errors='coerce'), 
    bins=bins, 
    labels=labels, 
    ordered=False
)

*Staging*

In [9]:
#Created a mew variable 'Stage' and changed the given categpries in 'Combined Summary Stage with Expanded Regional Codes (2004+)' to [I,II,III,IV].

stage_mapping = {
    "Localized only": "I",
    "Regional by direct extension only": "II",      
    "Regional lymph nodes involved only": "III",
    "Regional by both direct extension and lymph node involvement": "III",
    "Distant site(s)/node(s) involved": "IV",         
    "Unknown/unstaged/unspecified/DCO": "Unknown",
    "Blank(s)": "Unknown"
}
df['Stage']=df['Combined Summary Stage with Expanded Regional Codes (2004+)'].map(stage_mapping)

*Treatment*

In [10]:
#Created a new variable 'Radiation'  and changed the given categpries in 'Radiation recode' to [Radiation,No Radiation,Unknown].

radiation_map = {
    'None/Unknown': 'No',
    'Beam radiation': 'Yes',
    'Radiation, NOS  method or source not specified': 'Yes',
    'Refused (1988+)': 'No',
    'Recommended, unknown if administered': 'Unknown',
    'Radioactive implants (includes brachytherapy) (1988+)': 'Yes',
    'Combination of beam with implants or isotopes': 'Yes',
    'Radioisotopes (1988+)': 'Yes',
}
df['Radiation'] = df['Radiation recode'].map(radiation_map)

In [11]:
#Created a new variable 'Surgery' and changed the given surgery codes in 'RX Summ--Surg Prim Site (1998-2022)' to [Yes,NO,unknown].

surgery_binary_map = {
    # No surgical intervention
    '0': 'No',
    # Surgical interventions (Destruction, Excisions, Resections)
    '12': 'Yes',
    '13': 'Yes',
    '15': 'Yes',
    '19': 'Yes',
    '20': 'Yes',
    '21': 'Yes',
    '22': 'Yes',
    '23': 'Yes',
    '24': 'Yes',
    '25': 'Yes',
    '30': 'Yes',
    '33': 'Yes',
    '45': 'Yes',
    '46': 'Yes',
    '47': 'Yes',
    '48': 'Yes',
    '55': 'Yes',
    '56': 'Yes',
    '65': 'Yes',
    '66': 'Yes',
    '70': 'Yes',
    '80': 'Yes',
    '90': 'Yes',  # Surgery performed, scope unknown
    
    # Missing, uncollected, or unstageable data
    '99': 'Unknown',
    'Blank(s)': 'Unknown'
}
df['surgery']=df['RX Summ--Surg Prim Site (1998-2022)'].map(surgery_binary_map)

In [12]:
s = df['surgery'] == 'Yes'
r = df['Radiation'] == 'Yes'
c = df['Chemotherapy recode (yes, no/unk)'] == 'Yes'

# Define the conditions in order of priority (most specific to least specific)
conditions = [
    s & r & c,
    s & r,
    s & c,
    r & c,
    s,
    r,
    c
]

# Define the corresponding outputs
choices = [
    'Surgery+Radiation+Chemotherapy',
    'Surgery+Radiation',
    'Surgery+Chemotherapy',
    'Radiation+Chemotherapy',
    'Surgery',
    'Radiation',
    'Chemotherapy'
]

# Apply the conditions and choices to create the new column
df['Treatment'] = np.select(conditions, choices, default='Unknown')

*Outcomes*

In [13]:
#Changed survival month data type to numeric from object
df['Survival months']=pd.to_numeric(df['Survival months'],errors='coerce')
#replaced unknown with NaN
df['Survival months']=df['Survival months'].replace('unknown',np.nan)
#Dropped rows with unknkown Survival months
df=df.dropna(subset=['Survival months'])

In [14]:
#Assigned Binary(0,1) to vital status
df['Vital status recode (study cutoff used)']=df['Vital status recode (study cutoff used)'].replace(['Alive','Dead'],[0,1])

C:\Users\ricky\AppData\Local\Temp\ipykernel_24012\2702481694.py:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['Vital status recode (study cutoff used)']=df['Vital status recode (study cutoff used)'].replace(['Alive','Dead'],[0,1])

*SocioEconomic*

In [15]:
#Changed datatype to string
df['Median household income inflation adj to 2024']=df['Median household income inflation adj to 2024'].astype(str)

#'$70,000 - $74,999' -> '70000 - 74999' 
clean_inc = df['Median household income inflation adj to 2024'].str.replace('$', '', regex=False).str.replace(',', '', regex=False).str.replace('+', '', regex=False).str.replace('<', '', regex=False).str.strip()

#'70000 - 74999' -> '70000' | '74999' 
lower = clean_inc.str.split('-').str[0]
upper = clean_inc.str.split('-').str[-1]
# '70000' ->700000 (string to numeric) 
inc_lower=pd.to_numeric(lower,errors='coerce')
inc_upper=pd.to_numeric(upper,errors='coerce')

#Created a variable income which stores mid point of given income for calculation on income (mean inclome etc.)
df['Income']=(inc_lower+inc_upper)/2
df.sample(7)

,Age recode with <1 year olds and 90+,Sex,Year of diagnosis,"Race and origin recode (NHW, NHB, NHAIAN, NHAPI, Hispanic)",Marital status at diagnosis,Primary Site,Histologic Type ICD-O-3,Combined Summary Stage with Expanded Regional Codes (2004+),Radiation recode,"Chemotherapy recode (yes, no/unk)",...,COD to site recode,Median household income inflation adj to 2024,Rural-Urban Continuum Code,Age,Cancer_type,Stage,Radiation,surgery,Treatment,Income
542338,70-74,Female,2005,Non-Hispanic White,Married (including common law),Upper-inner quadrant of breast,Ductal/Lobular,Localized only,None/Unknown,No/Unknown,...,Alive,"$75,000 - $79,999",Counties in metropolitan areas ge 1 million pop,72.0,Breast,I,No,Yes,Surgery,77499.5
1436615,75-79,Female,2022,Non-Hispanic White,Single (never married),Overlapping lesion of breast,Ductal/Lobular,Localized only,Beam radiation,Yes,...,Alive,"$55,000 - $59,999",Nonmetropolitan counties adjacent to a metropo...,77.0,Breast,I,Yes,Yes,Surgery+Radiation+Chemotherapy,57499.5
1176345,45-49,Female,2001,Hispanic (All Races),Married (including common law),"Breast, NOS (Not Otherwise Specified)",Ductal/Lobular,Blank(s),Beam radiation,Yes,...,Breast,"$75,000 - $79,999",Counties in metropolitan areas ge 1 million pop,47.0,Breast,Unknown,Yes,NaN,Radiation+Chemotherapy,77499.5
785605,80-84,Female,2008,Non-Hispanic White,Widowed,Upper-outer quadrant of breast,Ductal/Lobular,Localized only,Beam radiation,No/Unknown,...,Alzheimers (ICD-9 and 10 only),"$100,000 - $109,999",Counties in metropolitan areas ge 1 million pop,82.0,Breast,I,Yes,Yes,Surgery+Radiation,104999.5
850893,50-54,Female,2013,Non-Hispanic White,Married (including common law),Lower-inner quadrant of breast,Ductal/Lobular,Localized only,Beam radiation,No/Unknown,...,Alive,"$85,000 - $89,999",Counties in metropolitan areas ge 1 million pop,52.0,Breast,I,Yes,Yes,Surgery+Radiation,87499.5
675515,80-84,Female,2004,Non-Hispanic White,Widowed,Lower-outer quadrant of breast,Ductal/Lobular,Localized only,None/Unknown,No/Unknown,...,Diseases of Heart,"$75,000 - $79,999",Counties in metropolitan areas ge 1 million pop,82.0,Breast,I,No,NaN,Unknown,77499.5
831292,20-24,Female,2011,Hispanic (All Races),Single (never married),Overlapping lesion of breast,Carcinoma NOS,Localized only,None/Unknown,No/Unknown,...,Alive,"$55,000 - $59,999","Counties in metropolitan areas of 250,000 to 1...",22.0,Breast,I,No,NaN,Unknown,57499.5

In [16]:
a=df.columns
a
for i in a:
    print(f'{df[i].value_counts()}')
    print(f'{df[i].value_counts().sum()}')
    print("")
    print('-------------------------------------------------------------------------------------')
    print("")

Age recode with <1 year olds and 90+
60-64    184846
65-69    184034
55-59    170917
70-74    159583
50-54    156923
45-49    133713
75-79    125168
40-44     87778
80-84     87290
85-89     50002
35-39     43405
90+       24571
30-34     19790
25-29      6476
20-24      1071
15-19       117
10-14        13
05-09         3
01-04         2
00            1
Name: count, dtype: int64
1435703

-------------------------------------------------------------------------------------

Sex
Female    1424810
Male        10893
Name: count, dtype: int64
1435703

-------------------------------------------------------------------------------------

Year of diagnosis
2023    74200
2021    72901
2022    72167
2019    69980
2018    67766
2017    66124
2016    64261
2015    63913
2020    63751
2014    61948
2013    60894
2012    59467
2011    58514
2009    56764
2010    56266
2008    55488
2007    54035
2001    51818
2006    51769
2002    51587
2005    51012
2000    50799
2004    50596
2003    49683
Name: count, dtype: int64
1435703

-------------------------------------------------------------------------------------

Race and origin recode (NHW, NHB, NHAIAN, NHAPI, Hispanic)
Non-Hispanic White                            982126
Hispanic (All Races)                          168373
Non-Hispanic Black                            145433
Non-Hispanic Asian or Pacific Islander        124763
Non-Hispanic American Indian/Alaska Native      8375
Non-Hispanic Unknown Race                       6633
Name: count, dtype: int64
1435703

-------------------------------------------------------------------------------------

Marital status at diagnosis
Married (including common law)    775962
Widowed                           215068
Single (never married)            208049
Divorced                          149591
Unknown                            67086
Separated                          15003
Unmarried or Domestic Partner       4944
Name: count, dtype: int64
1435703

-------------------------------------------------------------------------------------

Primary Site
Upper-outer quadrant of breast           471890
Overlapping lesion of breast             315228
Breast, NOS (Not Otherwise Specified)    212888
Upper-inner quadrant of breast           165009
Lower-outer quadrant of breast           102055
Lower-inner quadrant of breast            76975
Central portion of breast                 74610
Nipple and areola                          8761
Axillary tail of breast                    8287
Name: count, dtype: int64
1435703

-------------------------------------------------------------------------------------

Histologic Type ICD-O-3
Ductal/Lobular    1364630
Carcinoma NOS       28617
Adenocarcinoma      27664
Sarcoma/Rare         6705
Other                4900
Squamous Cell        3187
Name: count, dtype: int64
1435703

-------------------------------------------------------------------------------------

Combined Summary Stage with Expanded Regional Codes (2004+)
Localized only                                                  789384
Regional lymph nodes involved only                              277753
Blank(s)                                                        203887
Distant site(s)/node(s) involved                                 71941
Regional by both direct extension and lymph node involvement     43460
Unknown/unstaged/unspecified/DCO                                 25084
Regional by direct extension only                                24181
In situ                                                             13
Name: count, dtype: int64
1435703

-------------------------------------------------------------------------------------

Radiation recode
Beam radiation                                           676318
None/Unknown                                             661520
Refused (1988+)                                           37043
Recommended, unknown if administered                      31561
Radioactive implants (includes brachytherapy) (1988+)     20272
Radiation, NOS  method or source not specified             6311
Combination of beam with implants or isotopes              2245
Radioisotopes (1988+)                                       433
Name: count, dtype: int64
1435703

-------------------------------------------------------------------------------------

Chemotherapy recode (yes, no/unk)
No/Unknown    887241
Yes           548462
Name: count, dtype: int64
1435703

-------------------------------------------------------------------------------------

RX Summ--Surg Prim Site (1998-2022)
22          442773
51          151147
00          127614
41          127163
23          122012
Blank(s)     74200
20           68130
24           55546
42           35555
40           23430
52           21682
30           20790
49           19217
50           18393
45           17600
44           13807
48           12592
47           10105
43            9021
54            7400
55            6972
59            6065
46            5133
99            4652
21            4639
58            4191
80            4168
53            4059
75            3686
57            3340
56            2153
61            2022
90            1846
63            1333
62             783
60             620
19             242
64             229
65             216
76             203
68             158
69             148
66             120
72             115
74             115
71             100
73              89
67              77
70              52
Name: count, dtype: int64
1435703

-------------------------------------------------------------------------------------

Survival months
0.0      17327
1.0      13582
2.0      12843
4.0      12413
6.0      11563
         ...
278.0     1362
286.0     1349
284.0     1334
281.0     1323
287.0     1256
Name: count, Length: 288, dtype: int64
1435703

-------------------------------------------------------------------------------------

Vital status recode (study cutoff used)
0    960792
1    474911
Name: count, dtype: int64
1435703

-------------------------------------------------------------------------------------

COD to site recode
Alive                       960792
Breast                      195109
Diseases of Heart            63782
Other Cause of Death         52131
Cerebrovascular Diseases     17012
                             ...
Lip                              7
Floor of Mouth                   6
Penis                            2
Syphilis                         1
Testis                           1
Name: count, Length: 92, dtype: int64
1435703

-------------------------------------------------------------------------------------

Median household income inflation adj to 2024
$75,000 - $79,999                         176403
$100,000 - $109,999                       157662
$85,000 - $89,999                         134398
$120,000+                                 132691
$80,000 - $84,999                         128525
$110,000 - $119,999                       112002
$90,000 - $94,999                         108939
$70,000 - $74,999                         100968
$65,000 - $69,999                          94525
$95,000 - $99,999                          88476
$60,000 - $64,999                          59399
$55,000 - $59,999                          53364
$50,000 - $54,999                          42842
$45,000 - $49,999                          23231
$40,000 - $44,999                          13367
< $40,000                                   8608
Unknown/missing/no match/Not 1990-2024       303
Name: count, dtype: int64
1435703

-------------------------------------------------------------------------------------

Rural-Urban Continuum Code
Counties in metropolitan areas ge 1 million pop                 881117
Counties in metropolitan areas of 250,000 to 1 million pop      293960
Counties in metropolitan areas of lt 250 thousand pop           106664
Nonmetropolitan counties adjacent to a metropolitan area         91679
Nonmetropolitan counties not adjacent to a metropolitan area     60359
Unknown/missing/no match (Alaska or Hawaii - Entire State)        1621
Unknown/missing/no match/Not 1990-2024                             303
Name: count, dtype: int64
1435703

-------------------------------------------------------------------------------------

Age
62.0    184846
67.0    184034
57.0    170917
72.0    159583
52.0    156923
47.0    133713
77.0    125168
42.0     87778
82.0     87290
87.0     50002
37.0     43405
90.0     24571
32.0     19790
27.0      6476
22.0      1071
17.0       117
12.0        13
7.0          3
2.5          2
0.0          1
Name: count, dtype: int64
1435703

-------------------------------------------------------------------------------------

Cancer_type
Breast    1435703
Name: count, dtype: int64
1435703

-------------------------------------------------------------------------------------

Stage
I          789384
III        321213
Unknown    228971
IV          71941
II          24181
Name: count, dtype: int64
1435690

-------------------------------------------------------------------------------------

Radiation
Yes        705579
No         698563
Unknown     31561
Name: count, dtype: int64
1435703

-------------------------------------------------------------------------------------

surgery
Yes        775089
Unknown     78852
Name: count, dtype: int64
853941

-------------------------------------------------------------------------------------

Treatment
Surgery+Radiation                 337697
Unknown                           319919
Surgery+Radiation+Chemotherapy    194562
Surgery                           177380
Chemotherapy                      167375
Radiation+Chemotherapy            121075
Surgery+Chemotherapy               65450
Radiation                          52245
Name: count, dtype: int64
1435703

-------------------------------------------------------------------------------------

Income
77499.5     176403
104999.5    157662
87499.5     134398
120000.0    132691
82499.5     128525
114999.5    112002
92499.5     108939
72499.5     100968
67499.5      94525
97499.5      88476
62499.5      59399
57499.5      53364
52499.5      42842
47499.5      23231
42499.5      13367
40000.0       8608
Name: count, dtype: int64
1435400

-------------------------------------------------------------------------------------

In [17]:
df = df.drop(columns=['Unnamed: 0'], errors='ignore')
df.to_csv('Breast_Clean.csv', index=False)
print("Ready for analysis!")
df.info()

Ready for analysis!
<class 'pandas.core.frame.DataFrame'>
Index: 1435703 entries, 0 to 1442082
Data columns (total 23 columns):
 #   Column                                                       Non-Null Count    Dtype
---  ------                                                       --------------    -----
 0   Age recode with <1 year olds and 90+                         1435703 non-null  object
 1   Sex                                                          1435703 non-null  object
 2   Year of diagnosis                                            1435703 non-null  int64
 3   Race and origin recode (NHW, NHB, NHAIAN, NHAPI, Hispanic)   1435703 non-null  object
 4   Marital status at diagnosis                                  1435703 non-null  object
 5   Primary Site                                                 1435703 non-null  object
 6   Histologic Type ICD-O-3                                      1435703 non-null  category
 7   Combined Summary Stage with Expanded Regional Codes (2004+)  1435703 non-null  object
 8   Radiation recode                                             1435703 non-null  object
 9   Chemotherapy recode (yes, no/unk)                            1435703 non-null  object
 10  RX Summ--Surg Prim Site (1998-2022)                          1435703 non-null  object
 11  Survival months                                              1435703 non-null  float64
 12  Vital status recode (study cutoff used)                      1435703 non-null  int64
 13  COD to site recode                                           1435703 non-null  object
 14  Median household income inflation adj to 2024                1435703 non-null  object
 15  Rural-Urban Continuum Code                                   1435703 non-null  object
 16  Age                                                          1435703 non-null  float64
 17  Cancer_type                                                  1435703 non-null  object
 18  Stage                                                        1435690 non-null  object
 19  Radiation                                                    1435703 non-null  object
 20  surgery                                                      853941 non-null   object
 21  Treatment                                                    1435703 non-null  object
 22  Income                                                       1435400 non-null  float64
dtypes: category(1), float64(3), int64(2), object(17)
memory usage: 253.3+ MB

In [18]:
df.columns

Index(['Age recode with <1 year olds and 90+', 'Sex', 'Year of diagnosis',
       'Race and origin recode (NHW, NHB, NHAIAN, NHAPI, Hispanic)',
       'Marital status at diagnosis', 'Primary Site',
       'Histologic Type ICD-O-3',
       'Combined Summary Stage with Expanded Regional Codes (2004+)',
       'Radiation recode', 'Chemotherapy recode (yes, no/unk)',
       'RX Summ--Surg Prim Site (1998-2022)', 'Survival months',
       'Vital status recode (study cutoff used)', 'COD to site recode',
       'Median household income inflation adj to 2024',
       'Rural-Urban Continuum Code', 'Age', 'Cancer_type', 'Stage',
       'Radiation', 'surgery', 'Treatment', 'Income'],
      dtype='object')