In [1]:
import numpy as np
import pandas as pd

In [2]:
df=pd.read_csv('All Cancer Data/Liver.csv')
df.sample(7)

,Age recode with <1 year olds and 90+,Sex,Year of diagnosis,"Race and origin recode (NHW, NHB, NHAIAN, NHAPI, Hispanic)",Marital status at diagnosis,Primary Site,Histologic Type ICD-O-3,Combined Summary Stage with Expanded Regional Codes (2004+),Radiation recode,"Chemotherapy recode (yes, no/unk)",RX Summ--Surg Prim Site (1998-2022),Survival months,Vital status recode (study cutoff used),COD to site recode,Median household income inflation adj to 2024,Rural-Urban Continuum Code
5326,40-44 years,Male,2012,Non-Hispanic Asian or Pacific Islander,Unknown,220,8170,Regional by direct extension only,None/Unknown,No/Unknown,00,0006,Dead,Liver,"$100,000 - $109,999",Counties in metropolitan areas ge 1 million pop
99360,55-59 years,Male,2018,Non-Hispanic White,Unknown,220,8240,Unknown/unstaged/unspecified/DCO,None/Unknown,No/Unknown,00,0060,Alive,Alive,"$110,000 - $119,999",Counties in metropolitan areas ge 1 million pop
48382,80-84 years,Female,2008,Non-Hispanic Asian or Pacific Islander,Widowed,220,8170,Localized only,None/Unknown,Yes,00,0038,Dead,Cerebrovascular Diseases,"$120,000+",Counties in metropolitan areas ge 1 million pop
110179,55-59 years,Male,2022,Hispanic (All Races),Married (including common law),220,8170,Localized only,Radioisotopes (1988+),No/Unknown,00,0012,Dead,Liver,"$90,000 - $94,999","Counties in metropolitan areas of 250,000 to 1..."
5553,50-54 years,Male,2008,Non-Hispanic American Indian/Alaska Native,Single (never married),220,8170,Unknown/unstaged/unspecified/DCO,None/Unknown,No/Unknown,00,0025,Dead,Liver,"$100,000 - $109,999",Counties in metropolitan areas ge 1 million pop
57728,50-54 years,Male,2007,Hispanic (All Races),Single (never married),220,8170,Unknown/unstaged/unspecified/DCO,None/Unknown,No/Unknown,00,0018,Dead,Chronic Liver Disease and Cirrhosis,"$75,000 - $79,999",Counties in metropolitan areas ge 1 million pop
29610,75-79 years,Female,2022,Non-Hispanic American Indian/Alaska Native,Married (including common law),220,8170,Regional by direct extension only,Radioisotopes (1988+),No/Unknown,00,0019,Alive,Alive,"$100,000 - $109,999","Counties in metropolitan areas of 250,000 to 1..."

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 157497 entries, 0 to 157496
Data columns (total 16 columns):
 #   Column                                                       Non-Null Count   Dtype
---  ------                                                       --------------   -----
 0   Age recode with <1 year olds and 90+                         157497 non-null  object
 1   Sex                                                          157497 non-null  object
 2   Year of diagnosis                                            157497 non-null  int64
 3   Race and origin recode (NHW, NHB, NHAIAN, NHAPI, Hispanic)   157497 non-null  object
 4   Marital status at diagnosis                                  157497 non-null  object
 5   Primary Site                                                 157497 non-null  int64
 6   Histologic Type ICD-O-3                                      157497 non-null  int64
 7   Combined Summary Stage with Expanded Regional Codes (2004+)  157497 non-null  object
 8   Radiation recode                                             157497 non-null  object
 9   Chemotherapy recode (yes, no/unk)                            157497 non-null  object
 10  RX Summ--Surg Prim Site (1998-2022)                          157497 non-null  object
 11  Survival months                                              157497 non-null  object
 12  Vital status recode (study cutoff used)                      157497 non-null  object
 13  COD to site recode                                           157497 non-null  object
 14  Median household income inflation adj to 2024                157497 non-null  object
 15  Rural-Urban Continuum Code                                   157497 non-null  object
dtypes: int64(3), object(13)
memory usage: 19.2+ MB

In [4]:
a=df.columns
for i in a:
    print(f'{df[i].value_counts()}')
    print(f'{df[i].value_counts().sum()}')
    print("")
    print('-------------------------------------------------------------------------------------')
    print("")

Age recode with <1 year olds and 90+
60-64 years    26804
65-69 years    25391
55-59 years    22835
70-74 years    20282
75-79 years    15975
50-54 years    13672
80-84 years    11251
85-89 years     6315
45-49 years     6136
90+ years       2859
40-44 years     2241
35-39 years     1036
01-04 years      687
30-34 years      534
25-29 years      375
00 years         358
20-24 years      253
15-19 years      181
05-09 years      157
10-14 years      155
Name: count, dtype: int64
157497

-------------------------------------------------------------------------------------

Sex
Male      115829
Female     41668
Name: count, dtype: int64
157497

-------------------------------------------------------------------------------------

Year of diagnosis
2019    8513
2021    8399
2018    8288
2015    8231
2016    8146
2017    8059
2014    8029
2023    7855
2022    7825
2020    7655
2013    7649
2012    7298
2011    6884
2010    6515
2009    6402
2008    5915
2007    5610
2006    5223
2005    4996
2004    4574
2003    4199
2002    3966
2001    3816
2000    3450
Name: count, dtype: int64
157497

-------------------------------------------------------------------------------------

Race and origin recode (NHW, NHB, NHAIAN, NHAPI, Hispanic)
Non-Hispanic White                            79621
Hispanic (All Races)                          33101
Non-Hispanic Asian or Pacific Islander        24264
Non-Hispanic Black                            18099
Non-Hispanic American Indian/Alaska Native     2003
Non-Hispanic Unknown Race                       409
Name: count, dtype: int64
157497

-------------------------------------------------------------------------------------

Marital status at diagnosis
Married (including common law)    77271
Single (never married)            32757
Divorced                          18486
Widowed                           18450
Unknown                            7310
Separated                          2550
Unmarried or Domestic Partner       673
Name: count, dtype: int64
157497

-------------------------------------------------------------------------------------

Primary Site
220    157497
Name: count, dtype: int64
157497

-------------------------------------------------------------------------------------

Histologic Type ICD-O-3
8170    133913
8000      8199
8010      2937
8160      2906
8140      2748
         ...
8503         1
9581         1
8154         1
9044         1
8241         1
Name: count, Length: 133, dtype: int64
157497

-------------------------------------------------------------------------------------

Combined Summary Stage with Expanded Regional Codes (2004+)
Localized only                                                  65286
Regional by direct extension only                               29892
Distant site(s)/node(s) involved                                21226
Unknown/unstaged/unspecified/DCO                                20753
Blank(s)                                                        15431
Regional by both direct extension and lymph node involvement     2926
Regional lymph nodes involved only                               1982
In situ                                                             1
Name: count, dtype: int64
157497

-------------------------------------------------------------------------------------

Radiation recode
None/Unknown                                             139135
Radioisotopes (1988+)                                      8275
Beam radiation                                             5633
Radioactive implants (includes brachytherapy) (1988+)      2566
Refused (1988+)                                             947
Recommended, unknown if administered                        460
Radiation, NOS  method or source not specified              335
Combination of beam with implants or isotopes               146
Name: count, dtype: int64
157497

-------------------------------------------------------------------------------------

Chemotherapy recode (yes, no/unk)
No/Unknown    109940
Yes            47557
Name: count, dtype: int64
157497

-------------------------------------------------------------------------------------

RX Summ--Surg Prim Site (1998-2022)
00          109265
16           10576
Blank(s)      7855
99            7511
61            5800
36            2234
10            1521
23            1453
20            1090
37            1082
22            1052
21            1044
24            1015
30             805
60             736
17             598
26             580
15             537
51             505
25             474
90             296
13             283
52             271
50             226
75             148
14             138
38             135
59              96
12              93
66              50
11              25
65               3
Name: count, dtype: int64
157497

-------------------------------------------------------------------------------------

Survival months
0000       21886
0001       13639
0002       10309
0003        7702
Unknown     6424
           ...
0273           4
0285           4
0286           3
0279           3
0277           3
Name: count, Length: 289, dtype: int64
157497

-------------------------------------------------------------------------------------

Vital status recode (study cutoff used)
Dead     129208
Alive     28289
Name: count, dtype: int64
157497

-------------------------------------------------------------------------------------

COD to site recode
Liver                                                83350
Alive                                                28289
Chronic Liver Disease and Cirrhosis                   6792
Miscellaneous Malignant Cancer                        6775
Other Cause of Death                                  5992
                                                     ...
Trachea, Mediastinum and Other Respiratory Organs        2
Pleura                                                   2
Floor of Mouth                                           1
Vagina                                                   1
Other Male Genital Organs                                1
Name: count, Length: 91, dtype: int64
157497

-------------------------------------------------------------------------------------

Median household income inflation adj to 2024
$75,000 - $79,999                         21298
$100,000 - $109,999                       17166
$85,000 - $89,999                         14263
$80,000 - $84,999                         13942
$120,000+                                 12959
$70,000 - $74,999                         11825
$90,000 - $94,999                         11569
$65,000 - $69,999                         11271
$110,000 - $119,999                       10004
$95,000 - $99,999                          9287
$60,000 - $64,999                          6992
$55,000 - $59,999                          6385
$50,000 - $54,999                          5254
$45,000 - $49,999                          2736
$40,000 - $44,999                          1501
< $40,000                                  1017
Unknown/missing/no match/Not 1990-2024       28
Name: count, dtype: int64
157497

-------------------------------------------------------------------------------------

Rural-Urban Continuum Code
Counties in metropolitan areas ge 1 million pop                 98056
Counties in metropolitan areas of 250,000 to 1 million pop      32317
Counties in metropolitan areas of lt 250 thousand pop           11053
Nonmetropolitan counties adjacent to a metropolitan area         9398
Nonmetropolitan counties not adjacent to a metropolitan area     6410
Unknown/missing/no match (Alaska or Hawaii - Entire State)        235
Unknown/missing/no match/Not 1990-2024                             28
Name: count, dtype: int64
157497

-------------------------------------------------------------------------------------

In [5]:
b=df.columns
for i in b:
    print(f'{df[i].unique()}')
    print("")
    print('-------------------------------------------------------------------------------------')
    print("")

['75-79 years' '80-84 years' '85-89 years' '55-59 years' '65-69 years'
 '70-74 years' '50-54 years' '60-64 years' '40-44 years' '45-49 years'
 '90+ years' '30-34 years' '01-04 years' '35-39 years' '15-19 years'
 '25-29 years' '10-14 years' '05-09 years' '20-24 years' '00 years']

-------------------------------------------------------------------------------------

['Female' 'Male']

-------------------------------------------------------------------------------------

[2007 2022 2000 2016 2018 2006 2005 2001 2017 2013 2008 2003 2004 2009
 2019 2023 2012 2011 2020 2002 2014 2010 2015 2021]

-------------------------------------------------------------------------------------

['Hispanic (All Races)' 'Non-Hispanic White'
 'Non-Hispanic Asian or Pacific Islander' 'Non-Hispanic Black'
 'Non-Hispanic American Indian/Alaska Native' 'Non-Hispanic Unknown Race']

-------------------------------------------------------------------------------------

['Divorced' 'Married (including common law)'
 'Unmarried or Domestic Partner' 'Unknown' 'Single (never married)'
 'Separated' 'Widowed']

-------------------------------------------------------------------------------------

[220]

-------------------------------------------------------------------------------------

[8170 8174 8140 8000 8246 8171 8180 8010 8172 9124 8046 8190 8249 8800
 9120 8970 8240 8173 8033 9133 8175 8001 8890 8020 8980 8481 8012 8991
 8255 8576 8162 8500 8310 8450 8211 8830 8805 9560 8480 8161 9064 8041
 9061 8323 8013 9473 8032 8071 9130 8711 8005 8021 8801 8963 8936 8082
 8982 9071 8504 9251 9180 8160 9260 8802 8910 8804 8470 8070 8022 8574
 8900 8490 8045 9150 8560 9043 8693 8720 8141 8901 8035 8550 8806 8440
 8004 8815 9500 8002 8243 8920 8852 9070 8850 8575 9490 8452 8714 8894
 8260 8453 8700 9040 8290 8120 8163 9100 8230 8803 8471 8042 8031 9540
 8337 8810 9170 8825 8003 9220 9041 8370 8940 8312 9080 8680 8891 8896
 8854 8011 8503 9581 8154 9044 8241]

-------------------------------------------------------------------------------------

['Unknown/unstaged/unspecified/DCO' 'Localized only' 'Blank(s)'
 'Regional by direct extension only' 'Distant site(s)/node(s) involved'
 'Regional by both direct extension and lymph node involvement'
 'Regional lymph nodes involved only' 'In situ']

-------------------------------------------------------------------------------------

['None/Unknown' 'Radioisotopes (1988+)' 'Refused (1988+)'
 'Radioactive implants (includes brachytherapy) (1988+)' 'Beam radiation'
 'Recommended, unknown if administered'
 'Radiation, NOS  method or source not specified'
 'Combination of beam with implants or isotopes']

-------------------------------------------------------------------------------------

['No/Unknown' 'Yes']

-------------------------------------------------------------------------------------

['00' '30' '21' '10' '61' '16' '60' 'Blank(s)' '23' '99' '36' '12' '22'
 '51' '37' '13' '25' '26' '52' '20' '15' '66' '17' '50' '24' '14' '90'
 '75' '38' '11' '59' '65']

-------------------------------------------------------------------------------------

['0024' '0012' '0004' '0023' '0014' '0000' '0001' '0015' '0002' '0007'
 '0020' '0089' '0028' '0038' '0009' '0084' '0048' '0010' '0011' '0021'
 '0032' 'Unknown' '0068' '0022' '0050' '0005' '0043' '0003' '0041' '0259'
 '0049' '0170' '0018' '0008' '0013' '0144' '0044' '0067' '0040' '0037'
 '0168' '0059' '0052' '0006' '0031' '0029' '0030' '0053' '0051' '0249'
 '0101' '0034' '0090' '0061' '0027' '0216' '0060' '0016' '0221' '0078'
 '0115' '0042' '0099' '0070' '0149' '0064' '0118' '0091' '0072' '0103'
 '0019' '0161' '0071' '0033' '0210' '0176' '0046' '0054' '0055' '0111'
 '0246' '0117' '0057' '0035' '0017' '0069' '0026' '0080' '0075' '0123'
 '0163' '0121' '0218' '0172' '0179' '0073' '0171' '0231' '0092' '0100'
 '0287' '0036' '0102' '0147' '0110' '0280' '0079' '0268' '0271' '0125'
 '0239' '0045' '0223' '0143' '0256' '0156' '0237' '0195' '0132' '0076'
 '0077' '0133' '0119' '0282' '0088' '0265' '0183' '0145' '0074' '0281'
 '0260' '0058' '0272' '0254' '0082' '0083' '0085' '0047' '0276' '0130'
 '0087' '0270' '0126' '0178' '0225' '0278' '0025' '0267' '0217' '0261'
 '0283' '0093' '0175' '0164' '0253' '0266' '0252' '0128' '0241' '0109'
 '0263' '0247' '0257' '0235' '0039' '0258' '0097' '0108' '0081' '0202'
 '0162' '0063' '0242' '0262' '0122' '0112' '0129' '0131' '0251' '0200'
 '0243' '0255' '0065' '0150' '0240' '0180' '0248' '0245' '0229' '0244'
 '0250' '0152' '0234' '0232' '0236' '0142' '0154' '0113' '0066' '0230'
 '0137' '0086' '0107' '0181' '0228' '0187' '0238' '0188' '0215' '0222'
 '0226' '0227' '0208' '0165' '0094' '0220' '0159' '0219' '0106' '0199'
 '0194' '0211' '0214' '0135' '0213' '0209' '0056' '0062' '0177' '0212'
 '0207' '0173' '0158' '0206' '0205' '0204' '0192' '0203' '0134' '0191'
 '0151' '0201' '0189' '0148' '0196' '0193' '0224' '0198' '0197' '0190'
 '0185' '0124' '0186' '0138' '0182' '0184' '0153' '0105' '0157' '0095'
 '0120' '0098' '0167' '0166' '0174' '0127' '0169' '0141' '0096' '0160'
 '0114' '0155' '0146' '0104' '0140' '0139' '0136' '0116' '0269' '0284'
 '0285' '0275' '0233' '0264' '0274' '0286' '0273' '0279' '0277']

-------------------------------------------------------------------------------------

['Dead' 'Alive']

-------------------------------------------------------------------------------------

['Liver' 'Alive' 'Other Digestive Organs' 'Prostate'
 'Aortic Aneurysm and Dissection' 'Kidney and Renal Pelvis'
 'State DC not available or state DC available but no COD'
 'Other Cause of Death' 'Lung and Bronchus' 'Other Biliary'
 'Miscellaneous Malignant Cancer'
 'Other Infectious and Parasitic Diseases including HIV'
 'Colon excluding Rectum' 'Intrahepatic Bile Duct' 'Diseases of Heart'
 'Chronic Liver Disease and Cirrhosis' 'Stomach and Duodenal Ulcers'
 'Breast' 'Cerebrovascular Diseases' 'Gum and Other Mouth' 'Gallbladder'
 'Ureter' 'Other Diseases of Arteries, Arterioles, Capillaries'
 'Melanoma of the Skin' 'Urinary Bladder' 'Non-Hodgkin Lymphoma'
 'In situ, benign or unknown behavior neoplasm' 'Congenital Anomalies'
 'Alzheimers (ICD-9 and 10 only)' 'Septicemia'
 'Other Oral Cavity and Pharynx' 'Hypertension without Heart Disease'
 'Chronic Obstructive Pulmonary Disease and Allied Cond'
 'Nephritis, Nephrotic Syndrome and Nephrosis'
 'Soft Tissue including Heart' 'Stomach' 'Pneumonia and Influenza'
 'Pancreas' 'Vulva' 'Symptoms, Signs and Ill-Defined Conditions'
 'Diabetes Mellitus' 'Rectum and Rectosigmoid Junction'
 'Acute Myeloid Leukemia' 'Anus, Anal Canal and Anorectum' 'Tongue'
 'Larynx' 'Accidents and Adverse Effects' 'Myeloma'
 'Suicide and Self-Inflicted Injury' 'Atherosclerosis' 'Bones and Joints'
 'Chronic Myeloid Leukemia'
 'Certain Conditions Originating in Perinatal Period'
 'Other Urinary Organs' 'Non-Melanoma Skin' 'Esophagus' 'Cervix Uteri'
 'Retroperitoneum' 'Nasopharynx' 'Nose, Nasal Cavity and Middle Ear'
 'Ovary' 'Hypopharynx' 'Tonsil' 'Homicide and Legal Intervention'
 'Tuberculosis' 'Aleukemic, Subleukemic and NOS' 'Floor of Mouth'
 'Peritoneum, Omentum and Mesentery' 'Other Female Genital Organs'
 'Testis' 'Brain and Other Nervous System' 'Oropharynx' 'Thyroid'
 'Other Acute Leukemia' 'Other Endocrine including Thymus' 'Corpus Uteri'
 'Eye and Orbit' 'Chronic Lymphocytic Leukemia' 'Small Intestine'
 'Uterus, NOS' 'Hodgkin Lymphoma'
 'Complications of Pregnancy, Childbirth, Puerperium' 'Vagina'
 'Salivary Gland' 'Other Male Genital Organs' 'Other Lymphocytic Leukemia'
 'Other Myeloid/Monocytic Leukemia' 'Pleura' 'Penis'
 'Trachea, Mediastinum and Other Respiratory Organs'
 'Acute Lymphocytic Leukemia']

-------------------------------------------------------------------------------------

['$110,000 - $119,999' '$120,000+' '$100,000 - $109,999'
 '$95,000 - $99,999' 'Unknown/missing/no match/Not 1990-2024'
 '$85,000 - $89,999' '$90,000 - $94,999' '$80,000 - $84,999'
 '$75,000 - $79,999' '$65,000 - $69,999' '$70,000 - $74,999'
 '$60,000 - $64,999' '$55,000 - $59,999' '$45,000 - $49,999'
 '$50,000 - $54,999' '< $40,000' '$40,000 - $44,999']

-------------------------------------------------------------------------------------

['Counties in metropolitan areas ge 1 million pop'
 'Unknown/missing/no match/Not 1990-2024'
 'Counties in metropolitan areas of 250,000 to 1 million pop'
 'Nonmetropolitan counties adjacent to a metropolitan area'
 'Counties in metropolitan areas of lt 250 thousand pop'
 'Nonmetropolitan counties not adjacent to a metropolitan area'
 'Unknown/missing/no match (Alaska or Hawaii - Entire State)']

-------------------------------------------------------------------------------------

*Demographical Variables*

In [6]:
#Changed data type of age to string 
df['Age recode with <1 year olds and 90+']=df['Age recode with <1 year olds and 90+'].astype(str)
#Remover 'years' from '70-75 years'
df['Age recode with <1 year olds and 90+']=df['Age recode with <1 year olds and 90+'].str.strip(' years')

#'70-75' -> |70| |75|

age_lower = df['Age recode with <1 year olds and 90+'].str.replace('+', '', regex=False).str.split('-').str[0].astype(int)
age_upper = df['Age recode with <1 year olds and 90+'].str.replace('+', '', regex=False).str.split('-').str[-1].astype(int)

#Created a variable age which stores mid point of given age for calculation on age (mean age etc.)

df['Age']=(age_lower+age_upper)/2
df

,Age recode with <1 year olds and 90+,Sex,Year of diagnosis,"Race and origin recode (NHW, NHB, NHAIAN, NHAPI, Hispanic)",Marital status at diagnosis,Primary Site,Histologic Type ICD-O-3,Combined Summary Stage with Expanded Regional Codes (2004+),Radiation recode,"Chemotherapy recode (yes, no/unk)",RX Summ--Surg Prim Site (1998-2022),Survival months,Vital status recode (study cutoff used),COD to site recode,Median household income inflation adj to 2024,Rural-Urban Continuum Code,Age
0,75-79,Female,2007,Hispanic (All Races),Divorced,220,8170,Unknown/unstaged/unspecified/DCO,None/Unknown,No/Unknown,00,0024,Dead,Liver,"$110,000 - $119,999",Counties in metropolitan areas ge 1 million pop,77.0
1,80-84,Female,2022,Non-Hispanic White,Married (including common law),220,8170,Localized only,Radioisotopes (1988+),No/Unknown,00,0012,Alive,Alive,"$120,000+",Counties in metropolitan areas ge 1 million pop,82.0
2,80-84,Male,2000,Hispanic (All Races),Divorced,220,8170,Blank(s),Refused (1988+),No/Unknown,00,0004,Dead,Other Digestive Organs,"$110,000 - $119,999",Counties in metropolitan areas ge 1 million pop,82.0
3,75-79,Male,2022,Non-Hispanic White,Married (including common law),220,8170,Localized only,None/Unknown,No/Unknown,30,0023,Alive,Alive,"$120,000+",Counties in metropolitan areas ge 1 million pop,77.0
4,85-89,Male,2016,Non-Hispanic Asian or Pacific Islander,Married (including common law),220,8170,Localized only,Radioactive implants (includes brachytherapy) ...,Yes,00,0014,Dead,Prostate,"$110,000 - $119,999",Counties in metropolitan areas ge 1 million pop,87.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
157492,65-69,Male,2023,Non-Hispanic White,Married (including common law),220,8170,Unknown/unstaged/unspecified/DCO,None/Unknown,No/Unknown,Blank(s),Unknown,Dead,Liver,"$55,000 - $59,999",Nonmetropolitan counties adjacent to a metropo...,67.0
157493,85-89,Male,2023,Non-Hispanic White,Divorced,220,8000,Unknown/unstaged/unspecified/DCO,None/Unknown,No/Unknown,Blank(s),Unknown,Dead,Liver,"$85,000 - $89,999",Counties in metropolitan areas ge 1 million pop,87.0
157494,75-79,Male,2023,Non-Hispanic White,Married (including common law),220,8000,Unknown/unstaged/unspecified/DCO,None/Unknown,No/Unknown,Blank(s),Unknown,Dead,Liver,"$50,000 - $54,999",Nonmetropolitan counties not adjacent to a met...,77.0
157495,70-74,Male,2023,Non-Hispanic Black,Divorced,220,8000,Unknown/unstaged/unspecified/DCO,None/Unknown,No/Unknown,Blank(s),0000,Dead,Liver,"$70,000 - $74,999","Counties in metropolitan areas of 250,000 to 1...",72.0
157496,75-79,Female,2023,Non-Hispanic Black,Divorced,220,8000,Unknown/unstaged/unspecified/DCO,None/Unknown,No/Unknown,Blank(s),Unknown,Dead,Liver,"$80,000 - $84,999",Counties in metropolitan areas ge 1 million pop,77.0

*Tumor*

In [7]:
#Replacing the site code with their actual Anatomical site 

primary_sites = {
    220: "Liver, NOS"
}
df['Primary Site'] = df['Primary Site'].map(primary_sites)
df['Cancer_type']='Liver'

In [8]:
#Histology codes are replaced with Their Histological family group name.

bins =   [0,    8149,  8179,  8299,  8799,  9999]

#Bins work as intervals and labels as value of the code if it falls in that bin.
# If Histologuy code falls between 7999 to 8009 then it will replace it with 'Neoplasms, NOS'.

labels = [
    "Carcinoma NOS",           # 0–8149
    "Hepatocellular",          # 8150–8179  ← 8170=hepatocellular carcinoma
    "Cholangiocarcinoma",      # 8180–8299  ← 8160=cholangiocarcinoma
    "Sarcoma/Rare",            # 8300–8799
    "Other"                    # 8800–9999
]
df['Histologic Type ICD-O-3'] = pd.cut(
    pd.to_numeric(df['Histologic Type ICD-O-3'], errors='coerce'), 
    bins=bins, 
    labels=labels, 
    ordered=False
)

*Staging*

In [9]:
#Created a mew variable 'Stage' and changed the given categpries in 'Combined Summary Stage with Expanded Regional Codes (2004+)' to [I,II,III,IV].

stage_mapping = {
    "Localized only": "I",
    "Regional by direct extension only": "II",      
    "Regional lymph nodes involved only": "III",
    "Regional by both direct extension and lymph node involvement": "III",
    "Distant site(s)/node(s) involved": "IV",         
    "Unknown/unstaged/unspecified/DCO": "Unknown",
    "Blank(s)": "Unknown"
}
df['Stage']=df['Combined Summary Stage with Expanded Regional Codes (2004+)'].map(stage_mapping)

*Treatment*

In [10]:
#Created a new variable 'Radiation'  and changed the given categpries in 'Radiation recode' to [Radiation,No Radiation,Unknown].

radiation_map = {
    'None/Unknown': 'No',
    'Beam radiation': 'Yes',
    'Radiation, NOS  method or source not specified': 'Yes',
    'Refused (1988+)': 'No',
    'Recommended, unknown if administered': 'Unknown',
    'Radioactive implants (includes brachytherapy) (1988+)': 'Yes',
    'Combination of beam with implants or isotopes': 'Yes',
    'Radioisotopes (1988+)': 'Yes',
}
df['Radiation'] = df['Radiation recode'].map(radiation_map)

In [11]:
#Created a new variable 'Surgery' and changed the given surgery codes in 'RX Summ--Surg Prim Site (1998-2022)' to [Yes,NO,unknown].

surgery_binary_map = {
    # No surgical intervention
    '0': 'No',
    # Surgical interventions (Destruction, Excisions, Resections)
    '12': 'Yes',
    '13': 'Yes',
    '15': 'Yes',
    '19': 'Yes',
    '20': 'Yes',
    '21': 'Yes',
    '22': 'Yes',
    '23': 'Yes',
    '24': 'Yes',
    '25': 'Yes',
    '30': 'Yes',
    '33': 'Yes',
    '45': 'Yes',
    '46': 'Yes',
    '47': 'Yes',
    '48': 'Yes',
    '55': 'Yes',
    '56': 'Yes',
    '65': 'Yes',
    '66': 'Yes',
    '70': 'Yes',
    '80': 'Yes',
    '90': 'Yes',  # Surgery performed, scope unknown
    
    # Missing, uncollected, or unstageable data
    '99': 'Unknown',
    'Blank(s)': 'Unknown'
}
df['surgery']=df['RX Summ--Surg Prim Site (1998-2022)'].map(surgery_binary_map)

In [12]:
s = df['surgery'] == 'Yes'
r = df['Radiation'] == 'Yes'
c = df['Chemotherapy recode (yes, no/unk)'] == 'Yes'

# Define the conditions in order of priority (most specific to least specific)
conditions = [
    s & r & c,
    s & r,
    s & c,
    r & c,
    s,
    r,
    c
]

# Define the corresponding outputs
choices = [
    'Surgery+Radiation+Chemotherapy',
    'Surgery+Radiation',
    'Surgery+Chemotherapy',
    'Radiation+Chemotherapy',
    'Surgery',
    'Radiation',
    'Chemotherapy'
]

# Apply the conditions and choices to create the new column
df['Treatment'] = np.select(conditions, choices, default='Unknown')

*Outcomes*

In [13]:
#Changed survival month data type to numeric from object
df['Survival months']=pd.to_numeric(df['Survival months'],errors='coerce')
#replaced unknown with NaN
df['Survival months']=df['Survival months'].replace('unknown',np.nan)
#Dropped rows with unknkown Survival months
df=df.dropna(subset=['Survival months'])

In [14]:
#Assigned Binary(0,1) to vital status
df['Vital status recode (study cutoff used)']=df['Vital status recode (study cutoff used)'].replace(['Alive','Dead'],[0,1])

C:\Users\ricky\AppData\Local\Temp\ipykernel_24224\2702481694.py:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['Vital status recode (study cutoff used)']=df['Vital status recode (study cutoff used)'].replace(['Alive','Dead'],[0,1])
C:\Users\ricky\AppData\Local\Temp\ipykernel_24224\2702481694.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Vital status recode (study cutoff used)']=df['Vital status recode (study cutoff used)'].replace(['Alive','Dead'],[0,1])

*SocioEconomic*

In [15]:
#Changed datatype to string
df['Median household income inflation adj to 2024']=df['Median household income inflation adj to 2024'].astype(str)

#'$70,000 - $74,999' -> '70000 - 74999' 
clean_inc = df['Median household income inflation adj to 2024'].str.replace('$', '', regex=False).str.replace(',', '', regex=False).str.replace('+', '', regex=False).str.replace('<', '', regex=False).str.strip()

#'70000 - 74999' -> '70000' | '74999' 
lower = clean_inc.str.split('-').str[0]
upper = clean_inc.str.split('-').str[-1]
# '70000' ->700000 (string to numeric) 
inc_lower=pd.to_numeric(lower,errors='coerce')
inc_upper=pd.to_numeric(upper,errors='coerce')

#Created a variable income which stores mid point of given income for calculation on income (mean inclome etc.)
df['Income']=(inc_lower+inc_upper)/2
df.sample(7)

C:\Users\ricky\AppData\Local\Temp\ipykernel_24224\7351343.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Median household income inflation adj to 2024']=df['Median household income inflation adj to 2024'].astype(str)
C:\Users\ricky\AppData\Local\Temp\ipykernel_24224\7351343.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Income']=(inc_lower+inc_upper)/2

,Age recode with <1 year olds and 90+,Sex,Year of diagnosis,"Race and origin recode (NHW, NHB, NHAIAN, NHAPI, Hispanic)",Marital status at diagnosis,Primary Site,Histologic Type ICD-O-3,Combined Summary Stage with Expanded Regional Codes (2004+),Radiation recode,"Chemotherapy recode (yes, no/unk)",...,COD to site recode,Median household income inflation adj to 2024,Rural-Urban Continuum Code,Age,Cancer_type,Stage,Radiation,surgery,Treatment,Income
102380,65-69,Male,2018,Non-Hispanic Asian or Pacific Islander,Married (including common law),"Liver, NOS",Hepatocellular,Regional by direct extension only,None/Unknown,No/Unknown,...,Liver,"$100,000 - $109,999","Counties in metropolitan areas of 250,000 to 1...",67.0,Liver,II,No,NaN,Unknown,104999.5
129740,55-59,Female,2019,Non-Hispanic White,Married (including common law),"Liver, NOS",Hepatocellular,Distant site(s)/node(s) involved,None/Unknown,Yes,...,Liver,"$55,000 - $59,999","Counties in metropolitan areas of 250,000 to 1...",57.0,Liver,IV,No,NaN,Chemotherapy,57499.5
136094,80-84,Male,2014,Non-Hispanic White,Married (including common law),"Liver, NOS",Hepatocellular,Regional by direct extension only,None/Unknown,No/Unknown,...,Diseases of Heart,"$120,000+",Counties in metropolitan areas ge 1 million pop,82.0,Liver,II,No,NaN,Unknown,120000.0
139929,60-64,Male,2014,Non-Hispanic White,Married (including common law),"Liver, NOS",Hepatocellular,Localized only,None/Unknown,Yes,...,Liver,"$120,000+",Counties in metropolitan areas ge 1 million pop,62.0,Liver,I,No,Yes,Surgery+Chemotherapy,120000.0
94723,70-74,Male,2014,Hispanic (All Races),Married (including common law),"Liver, NOS",Cholangiocarcinoma,Regional by direct extension only,None/Unknown,Yes,...,Alive,"$65,000 - $69,999","Counties in metropolitan areas of 250,000 to 1...",72.0,Liver,II,No,NaN,Chemotherapy,67499.5
152251,50-54,Male,2014,Non-Hispanic White,Unknown,"Liver, NOS",Hepatocellular,Regional by direct extension only,None/Unknown,No/Unknown,...,Tuberculosis,"< $40,000",Nonmetropolitan counties adjacent to a metropo...,52.0,Liver,II,No,NaN,Unknown,40000.0
62430,60-64,Male,2013,Hispanic (All Races),Divorced,"Liver, NOS",Hepatocellular,Localized only,None/Unknown,Yes,...,Liver,"$70,000 - $74,999",Counties in metropolitan areas ge 1 million pop,62.0,Liver,I,No,NaN,Chemotherapy,72499.5

In [16]:
a=df.columns
a
for i in a:
    print(f'{df[i].value_counts()}')
    print(f'{df[i].value_counts().sum()}')
    print("")
    print('-------------------------------------------------------------------------------------')
    print("")

Age recode with <1 year olds and 90+
60-64    25984
65-69    24591
55-59    22174
70-74    19509
75-79    15251
50-54    13312
80-84    10549
45-49     5958
85-89     5655
90+       2231
40-44     2173
35-39     1015
01-04      684
30-34      526
25-29      370
00         352
20-24      248
15-19      180
05-09      156
10-14      155
Name: count, dtype: int64
151073

-------------------------------------------------------------------------------------

Sex
Male      111546
Female     39527
Name: count, dtype: int64
151073

-------------------------------------------------------------------------------------

Year of diagnosis
2019    8136
2021    7971
2018    7869
2015    7829
2017    7795
2016    7767
2014    7622
2023    7527
2022    7420
2013    7381
2020    7256
2012    7100
2011    6695
2010    6339
2009    6233
2008    5709
2007    5447
2006    5034
2005    4763
2004    4373
2003    4033
2002    3799
2001    3672
2000    3303
Name: count, dtype: int64
151073

-------------------------------------------------------------------------------------

Race and origin recode (NHW, NHB, NHAIAN, NHAPI, Hispanic)
Non-Hispanic White                            76148
Hispanic (All Races)                          31693
Non-Hispanic Asian or Pacific Islander        23529
Non-Hispanic Black                            17389
Non-Hispanic American Indian/Alaska Native     1923
Non-Hispanic Unknown Race                       391
Name: count, dtype: int64
151073

-------------------------------------------------------------------------------------

Marital status at diagnosis
Married (including common law)    74942
Single (never married)            31818
Divorced                          17220
Widowed                           16921
Unknown                            7020
Separated                          2480
Unmarried or Domestic Partner       672
Name: count, dtype: int64
151073

-------------------------------------------------------------------------------------

Primary Site
Liver, NOS    151073
Name: count, dtype: int64
151073

-------------------------------------------------------------------------------------

Histologic Type ICD-O-3
Hepatocellular        135843
Carcinoma NOS          10548
Other                   2279
Cholangiocarcinoma      2187
Sarcoma/Rare             216
Name: count, dtype: int64
151073

-------------------------------------------------------------------------------------

Combined Summary Stage with Expanded Regional Codes (2004+)
Localized only                                                  65165
Regional by direct extension only                               29838
Distant site(s)/node(s) involved                                21163
Unknown/unstaged/unspecified/DCO                                15195
Blank(s)                                                        14807
Regional by both direct extension and lymph node involvement     2925
Regional lymph nodes involved only                               1979
In situ                                                             1
Name: count, dtype: int64
151073

-------------------------------------------------------------------------------------

Radiation recode
None/Unknown                                             132711
Radioisotopes (1988+)                                      8275
Beam radiation                                             5633
Radioactive implants (includes brachytherapy) (1988+)      2566
Refused (1988+)                                             947
Recommended, unknown if administered                        460
Radiation, NOS  method or source not specified              335
Combination of beam with implants or isotopes               146
Name: count, dtype: int64
151073

-------------------------------------------------------------------------------------

Chemotherapy recode (yes, no/unk)
No/Unknown    103516
Yes            47557
Name: count, dtype: int64
151073

-------------------------------------------------------------------------------------

RX Summ--Surg Prim Site (1998-2022)
00          108827
16           10576
Blank(s)      7527
61            5800
36            2234
99            1853
10            1521
23            1453
20            1090
37            1082
22            1052
21            1044
24            1015
30             805
60             736
17             598
26             580
15             537
51             505
25             474
90             296
13             283
52             271
50             226
75             148
14             138
38             135
59              96
12              93
66              50
11              25
65               3
Name: count, dtype: int64
151073

-------------------------------------------------------------------------------------

Survival months
0.0      21886
1.0      13639
2.0      10309
3.0       7702
4.0       6069
         ...
285.0        4
273.0        4
279.0        3
277.0        3
286.0        3
Name: count, Length: 288, dtype: int64
151073

-------------------------------------------------------------------------------------

Vital status recode (study cutoff used)
1    122796
0     28277
Name: count, dtype: int64
151073

-------------------------------------------------------------------------------------

COD to site recode
Liver                                                77880
Alive                                                28277
Chronic Liver Disease and Cirrhosis                   6650
Miscellaneous Malignant Cancer                        6508
Other Cause of Death                                  5907
                                                     ...
Trachea, Mediastinum and Other Respiratory Organs        2
Pleura                                                   2
Floor of Mouth                                           1
Vagina                                                   1
Other Male Genital Organs                                1
Name: count, Length: 91, dtype: int64
151073

-------------------------------------------------------------------------------------

Median household income inflation adj to 2024
$75,000 - $79,999                         20510
$100,000 - $109,999                       16491
$85,000 - $89,999                         13642
$80,000 - $84,999                         13455
$120,000+                                 12416
$70,000 - $74,999                         11334
$90,000 - $94,999                         11024
$65,000 - $69,999                         10831
$110,000 - $119,999                        9573
$95,000 - $99,999                          8976
$60,000 - $64,999                          6705
$55,000 - $59,999                          6120
$50,000 - $54,999                          4993
$45,000 - $49,999                          2593
$40,000 - $44,999                          1419
< $40,000                                   966
Unknown/missing/no match/Not 1990-2024       25
Name: count, dtype: int64
151073

-------------------------------------------------------------------------------------

Rural-Urban Continuum Code
Counties in metropolitan areas ge 1 million pop                 94154
Counties in metropolitan areas of 250,000 to 1 million pop      30956
Counties in metropolitan areas of lt 250 thousand pop           10611
Nonmetropolitan counties adjacent to a metropolitan area         9014
Nonmetropolitan counties not adjacent to a metropolitan area     6083
Unknown/missing/no match (Alaska or Hawaii - Entire State)        230
Unknown/missing/no match/Not 1990-2024                             25
Name: count, dtype: int64
151073

-------------------------------------------------------------------------------------

Age
62.0    25984
67.0    24591
57.0    22174
72.0    19509
77.0    15251
52.0    13312
82.0    10549
47.0     5958
87.0     5655
90.0     2231
42.0     2173
37.0     1015
2.5       684
32.0      526
27.0      370
0.0       352
22.0      248
17.0      180
7.0       156
12.0      155
Name: count, dtype: int64
151073

-------------------------------------------------------------------------------------

Cancer_type
Liver    151073
Name: count, dtype: int64
151073

-------------------------------------------------------------------------------------

Stage
I          65165
Unknown    30002
II         29838
IV         21163
III         4904
Name: count, dtype: int64
151072

-------------------------------------------------------------------------------------

Radiation
No         133658
Yes         16955
Unknown       460
Name: count, dtype: int64
151073

-------------------------------------------------------------------------------------

surgery
Unknown    9380
Yes        8195
Name: count, dtype: int64
17575

-------------------------------------------------------------------------------------

Treatment
Unknown                           85329
Chemotherapy                      40885
Radiation                         11657
Surgery                            6363
Radiation+Chemotherapy             5007
Surgery+Chemotherapy               1541
Surgery+Radiation                   167
Surgery+Radiation+Chemotherapy      124
Name: count, dtype: int64
151073

-------------------------------------------------------------------------------------

Income
77499.5     20510
104999.5    16491
87499.5     13642
82499.5     13455
120000.0    12416
72499.5     11334
92499.5     11024
67499.5     10831
114999.5     9573
97499.5      8976
62499.5      6705
57499.5      6120
52499.5      4993
47499.5      2593
42499.5      1419
40000.0       966
Name: count, dtype: int64
151048

-------------------------------------------------------------------------------------

In [17]:
df = df.drop(columns=['Unnamed: 0'], errors='ignore')
df.to_csv('Liver_Clean.csv', index=False)
print("Ready for analysis!")
df.info()

Ready for analysis!
<class 'pandas.core.frame.DataFrame'>
Index: 151073 entries, 0 to 157495
Data columns (total 23 columns):
 #   Column                                                       Non-Null Count   Dtype
---  ------                                                       --------------   -----
 0   Age recode with <1 year olds and 90+                         151073 non-null  object
 1   Sex                                                          151073 non-null  object
 2   Year of diagnosis                                            151073 non-null  int64
 3   Race and origin recode (NHW, NHB, NHAIAN, NHAPI, Hispanic)   151073 non-null  object
 4   Marital status at diagnosis                                  151073 non-null  object
 5   Primary Site                                                 151073 non-null  object
 6   Histologic Type ICD-O-3                                      151073 non-null  category
 7   Combined Summary Stage with Expanded Regional Codes (2004+)  151073 non-null  object
 8   Radiation recode                                             151073 non-null  object
 9   Chemotherapy recode (yes, no/unk)                            151073 non-null  object
 10  RX Summ--Surg Prim Site (1998-2022)                          151073 non-null  object
 11  Survival months                                              151073 non-null  float64
 12  Vital status recode (study cutoff used)                      151073 non-null  int64
 13  COD to site recode                                           151073 non-null  object
 14  Median household income inflation adj to 2024                151073 non-null  object
 15  Rural-Urban Continuum Code                                   151073 non-null  object
 16  Age                                                          151073 non-null  float64
 17  Cancer_type                                                  151073 non-null  object
 18  Stage                                                        151072 non-null  object
 19  Radiation                                                    151073 non-null  object
 20  surgery                                                      17575 non-null   object
 21  Treatment                                                    151073 non-null  object
 22  Income                                                       151048 non-null  float64
dtypes: category(1), float64(3), int64(2), object(17)
memory usage: 26.7+ MB