In [1]:
import numpy as np
import pandas as pd

In [2]:
df=pd.read_csv('All Cancer Data/Lung.csv')
df.sample(7)

,Age recode with <1 year olds and 90+,Sex,Year of diagnosis,"Race and origin recode (NHW, NHB, NHAIAN, NHAPI, Hispanic)",Marital status at diagnosis,Primary Site,Histologic Type ICD-O-3,Combined Summary Stage with Expanded Regional Codes (2004+),Radiation recode,"Chemotherapy recode (yes, no/unk)",RX Summ--Surg Prim Site (1998-2022),Survival months,Vital status recode (study cutoff used),COD to site recode,Median household income inflation adj to 2024,Rural-Urban Continuum Code
723411,70-74 years,Female,2007,Non-Hispanic White,Widowed,341,8046,Distant site(s)/node(s) involved,Refused (1988+),No/Unknown,00,0000,Dead,Lung and Bronchus,"$50,000 - $54,999",Nonmetropolitan counties adjacent to a metropo...
1089850,70-74 years,Male,2007,Non-Hispanic White,Widowed,349,8000,Unknown/unstaged/unspecified/DCO,None/Unknown,No/Unknown,99,Unknown,Dead,Lung and Bronchus,"$50,000 - $54,999","Counties in metropolitan areas of 250,000 to 1..."
286350,85-89 years,Female,2023,Non-Hispanic White,Married (including common law),349,8140,Distant site(s)/node(s) involved,None/Unknown,No/Unknown,Blank(s),0000,Dead,Lung and Bronchus,"$95,000 - $99,999",Counties in metropolitan areas ge 1 million pop
800464,75-79 years,Male,2019,Non-Hispanic White,Unmarried or Domestic Partner,343,8046,Localized only,Beam radiation,No/Unknown,00,0040,Dead,Other Cause of Death,"$75,000 - $79,999","Counties in metropolitan areas of 250,000 to 1..."
928575,70-74 years,Female,2002,Non-Hispanic White,Widowed,341,8140,Blank(s),Beam radiation,No/Unknown,00,0007,Dead,Lung and Bronchus,"$90,000 - $94,999",Counties in metropolitan areas ge 1 million pop
513514,75-79 years,Female,2002,Non-Hispanic White,Widowed,349,8000,Blank(s),None/Unknown,No/Unknown,00,0002,Dead,Lung and Bronchus,"$75,000 - $79,999",Counties in metropolitan areas ge 1 million pop
1146964,80-84 years,Female,2021,Non-Hispanic White,Widowed,341,8140,Distant site(s)/node(s) involved,None/Unknown,No/Unknown,00,0000,Dead,Other Cause of Death,"$95,000 - $99,999","Counties in metropolitan areas of 250,000 to 1..."

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1158613 entries, 0 to 1158612
Data columns (total 16 columns):
 #   Column                                                       Non-Null Count    Dtype
---  ------                                                       --------------    -----
 0   Age recode with <1 year olds and 90+                         1158613 non-null  object
 1   Sex                                                          1158613 non-null  object
 2   Year of diagnosis                                            1158613 non-null  int64
 3   Race and origin recode (NHW, NHB, NHAIAN, NHAPI, Hispanic)   1158613 non-null  object
 4   Marital status at diagnosis                                  1158613 non-null  object
 5   Primary Site                                                 1158613 non-null  int64
 6   Histologic Type ICD-O-3                                      1158613 non-null  int64
 7   Combined Summary Stage with Expanded Regional Codes (2004+)  1158613 non-null  object
 8   Radiation recode                                             1158613 non-null  object
 9   Chemotherapy recode (yes, no/unk)                            1158613 non-null  object
 10  RX Summ--Surg Prim Site (1998-2022)                          1158613 non-null  object
 11  Survival months                                              1158613 non-null  object
 12  Vital status recode (study cutoff used)                      1158613 non-null  object
 13  COD to site recode                                           1158613 non-null  object
 14  Median household income inflation adj to 2024                1158613 non-null  object
 15  Rural-Urban Continuum Code                                   1158613 non-null  object
dtypes: int64(3), object(13)
memory usage: 141.4+ MB

In [4]:
a=df.columns
for i in a:
    print(f'{df[i].value_counts()}')
    print(f'{df[i].value_counts().sum()}')
    print("")
    print('-------------------------------------------------------------------------------------')
    print("")

Age recode with <1 year olds and 90+
70-74 years    201417
65-69 years    187154
75-79 years    186593
60-64 years    146281
80-84 years    135363
55-59 years     99491
85-89 years     71906
50-54 years     55867
90+ years       29686
45-49 years     26522
40-44 years     10989
35-39 years      4024
30-34 years      1691
25-29 years       815
20-24 years       425
15-19 years       179
10-14 years        75
01-04 years        73
00 years           32
05-09 years        30
Name: count, dtype: int64
1158613

-------------------------------------------------------------------------------------

Sex
Male      607278
Female    551335
Name: count, dtype: int64
1158613

-------------------------------------------------------------------------------------

Year of diagnosis
2019    51078
2017    50234
2023    49944
2018    49768
2016    49685
2015    49604
2009    49205
2014    49188
2022    48970
2021    48839
2013    48529
2012    48433
2008    48402
2007    48147
2010    47996
2006    47902
2011    47651
2005    47409
2003    46723
2004    46648
2002    46430
2001    46233
2020    45830
2000    45765
Name: count, dtype: int64
1158613

-------------------------------------------------------------------------------------

Race and origin recode (NHW, NHB, NHAIAN, NHAPI, Hispanic)
Non-Hispanic White                            887328
Non-Hispanic Black                            117956
Non-Hispanic Asian or Pacific Islander         73825
Hispanic (All Races)                           71340
Non-Hispanic American Indian/Alaska Native      6420
Non-Hispanic Unknown Race                       1744
Name: count, dtype: int64
1158613

-------------------------------------------------------------------------------------

Marital status at diagnosis
Married (including common law)    570410
Widowed                           227571
Single (never married)            154851
Divorced                          140737
Unknown                            49153
Separated                          12935
Unmarried or Domestic Partner       2956
Name: count, dtype: int64
1158613

-------------------------------------------------------------------------------------

Primary Site
341    558904
343    288938
349    197390
340     51393
342     48963
348     13025
Name: count, dtype: int64
1158613

-------------------------------------------------------------------------------------

Histologic Type ICD-O-3
8140    374758
8070    199580
8041    127721
8046    102046
8000     89611
         ...
8342         1
8585         1
9061         1
9367         1
8124         1
Name: count, Length: 234, dtype: int64
1158613

-------------------------------------------------------------------------------------

Combined Summary Stage with Expanded Regional Codes (2004+)
Distant site(s)/node(s) involved                                491401
Localized only                                                  211349
Blank(s)                                                        185151
Regional lymph nodes involved only                               81499
Unknown/unstaged/unspecified/DCO                                 65870
Regional by direct extension only                                65011
Regional by both direct extension and lymph node involvement     58331
In situ                                                              1
Name: count, dtype: int64
1158613

-------------------------------------------------------------------------------------

Radiation recode
None/Unknown                                             714252
Beam radiation                                           406296
Refused (1988+)                                           21053
Recommended, unknown if administered                       8902
Radiation, NOS  method or source not specified             5422
Combination of beam with implants or isotopes              1217
Radioactive implants (includes brachytherapy) (1988+)      1205
Radioisotopes (1988+)                                       266
Name: count, dtype: int64
1158613

-------------------------------------------------------------------------------------

Chemotherapy recode (yes, no/unk)
No/Unknown    714774
Yes           443839
Name: count, dtype: int64
1158613

-------------------------------------------------------------------------------------

RX Summ--Surg Prim Site (1998-2022)
00          840069
33          110090
Blank(s)     49944
30           46186
21           38779
99           34064
22           10216
45            6105
56            5807
55            4338
90            1974
46            1952
23            1823
20            1552
12            1427
24             891
15             806
19             579
80             487
13             457
25             326
70             218
47             191
48             135
66             120
65              77
Name: count, dtype: int64
1158613

-------------------------------------------------------------------------------------

Survival months
0000    133095
0001     96461
0002     72378
0003     54100
0004     46355
         ...
0282        57
0284        53
0280        53
0278        53
0287        52
Name: count, Length: 289, dtype: int64
1158613

-------------------------------------------------------------------------------------

Vital status recode (study cutoff used)
Dead     976160
Alive    182453
Name: count, dtype: int64
1158613

-------------------------------------------------------------------------------------

COD to site recode
Lung and Bronchus                                        742156
Alive                                                    182453
Diseases of Heart                                         42249
Miscellaneous Malignant Cancer                            32591
Chronic Obstructive Pulmonary Disease and Allied Cond     31807
                                                          ...
Lip                                                          14
Certain Conditions Originating in Perinatal Period            9
Acute Monocytic Leukemia                                      8
Other Male Genital Organs                                     3
Syphilis                                                      1
Name: count, Length: 94, dtype: int64
1158613

-------------------------------------------------------------------------------------

Median household income inflation adj to 2024
$75,000 - $79,999                         133718
$100,000 - $109,999                       109483
$85,000 - $89,999                         102150
$80,000 - $84,999                         101568
$65,000 - $69,999                          90913
$70,000 - $74,999                          86634
$120,000+                                  80826
$110,000 - $119,999                        75210
$90,000 - $94,999                          73723
$60,000 - $64,999                          65098
$95,000 - $99,999                          62672
$55,000 - $59,999                          60712
$50,000 - $54,999                          51145
$45,000 - $49,999                          30049
$40,000 - $44,999                          19732
< $40,000                                  14874
Unknown/missing/no match/Not 1990-2024       106
Name: count, dtype: int64
1158613

-------------------------------------------------------------------------------------

Rural-Urban Continuum Code
Counties in metropolitan areas ge 1 million pop                 628519
Counties in metropolitan areas of 250,000 to 1 million pop      237519
Nonmetropolitan counties adjacent to a metropolitan area        108927
Counties in metropolitan areas of lt 250 thousand pop           105657
Nonmetropolitan counties not adjacent to a metropolitan area     76247
Unknown/missing/no match (Alaska or Hawaii - Entire State)        1638
Unknown/missing/no match/Not 1990-2024                             106
Name: count, dtype: int64
1158613

-------------------------------------------------------------------------------------

In [5]:
b=df.columns
for i in b:
    print(f'{df[i].unique()}')
    print("")
    print('-------------------------------------------------------------------------------------')
    print("")

['75-79 years' '60-64 years' '70-74 years' '65-69 years' '50-54 years'
 '55-59 years' '90+ years' '80-84 years' '85-89 years' '45-49 years'
 '40-44 years' '35-39 years' '30-34 years' '25-29 years' '20-24 years'
 '15-19 years' '10-14 years' '05-09 years' '00 years' '01-04 years']

-------------------------------------------------------------------------------------

['Female' 'Male']

-------------------------------------------------------------------------------------

[2006 2001 2007 2018 2011 2009 2010 2016 2005 2014 2021 2015 2019 2004
 2020 2008 2003 2017 2000 2012 2022 2013 2023 2002]

-------------------------------------------------------------------------------------

['Non-Hispanic White' 'Non-Hispanic Black' 'Hispanic (All Races)'
 'Non-Hispanic Asian or Pacific Islander'
 'Non-Hispanic American Indian/Alaska Native' 'Non-Hispanic Unknown Race']

-------------------------------------------------------------------------------------

['Married (including common law)' 'Single (never married)' 'Widowed'
 'Divorced' 'Unknown' 'Separated' 'Unmarried or Domestic Partner']

-------------------------------------------------------------------------------------

[343 340 341 349 342 348]

-------------------------------------------------------------------------------------

[8250 8140 8070 8041 8046 8010 8042 8550 8000 8240 8255 8144 8246 8071
 8032 8560 8012 8480 8072 8031 8020 8253 8551 8252 8260 8254 8050 8815
 8083 8481 8230 8073 8200 9120 8310 8045 8022 8033 9040 8265 8323 8980
 8430 8570 8074 8013 8802 8249 8043 8021 8507 8001 8800 8244 8044 8900
 8500 9041 8082 8052 8490 8251 8004 8574 8470 8890 9130 8123 8711 8245
 8920 8015 8576 8141 9150 8145 8972 8243 8014 8460 8503 9181 9043 8801
 8805 8256 8084 8075 8830 9133 8973 8562 8575 9064 8933 8333 9540 9101
 8005 9581 8680 8023 9137 8825 8257 9364 9080 8858 8940 8811 8341 8051
 8803 8076 8804 8030 8901 8241 8471 8247 8524 8894 8034 8891 8921 8720
 8580 8581 8290 8714 9071 8525 9085 9560 8401 8963 8002 9100 8441 8806
 8810 8990 8147 8035 8120 8095 9220 8852 8910 9065 9180 9260 8936 8201
 9530 8340 8003 9231 8090 8902 9473 9044 8312 8263 8855 8824 8854 8211
 8982 8693 9174 8440 8650 8770 8011 8078 9084 8523 8410 8850 8912 8086
 8170 8896 8231 9070 8851 8130 8572 9042 8094 8840 9500 8510 9015 9571
 9580 9240 9222 8584 8320 9561 8040 8350 8146 8934 8935 8345 8210 8743
 9250 8710 8772 8571 9370 8582 8150 8143 8583 8950 8832 9230 9522 8085
 8842 8836 9020 9310 8530 8342 8585 9061 9367 8124]

-------------------------------------------------------------------------------------

['Localized only' 'Blank(s)' 'Distant site(s)/node(s) involved'
 'Regional by both direct extension and lymph node involvement'
 'Regional lymph nodes involved only' 'Unknown/unstaged/unspecified/DCO'
 'Regional by direct extension only' 'In situ']

-------------------------------------------------------------------------------------

['None/Unknown' 'Radiation, NOS  method or source not specified'
 'Beam radiation' 'Recommended, unknown if administered' 'Refused (1988+)'
 'Radioactive implants (includes brachytherapy) (1988+)'
 'Combination of beam with implants or isotopes' 'Radioisotopes (1988+)']

-------------------------------------------------------------------------------------

['No/Unknown' 'Yes']

-------------------------------------------------------------------------------------

['30' '00' '33' '90' '45' '21' 'Blank(s)' '23' '24' '55' '80' '22' '99'
 '56' '15' '13' '20' '12' '46' '70' '19' '47' '25' '65' '48' '66']

-------------------------------------------------------------------------------------

['0128' '0001' '0005' '0000' '0071' '0003' '0095' '0029' '0027' '0023'
 '0014' '0026' '0052' '0053' '0012' '0007' '0018' '0067' '0040' '0022'
 '0008' '0047' '0046' '0068' '0017' '0002' '0025' '0033' '0166' '0054'
 '0010' '0009' '0024' '0013' '0016' '0032' '0004' '0015' '0116' '0042'
 '0087' '0200' '0020' '0021' '0130' '0037' '0045' '0019' '0011' '0006'
 '0155' '0076' '0035' '0060' '0030' '0112' '0125' '0123' '0102' '0062'
 '0050' '0208' '0088' '0169' '0075' '0034' '0110' '0174' '0100' '0090'
 '0059' '0049' '0119' '0209' '0172' '0239' '0140' '0137' '0283' 'Unknown'
 '0133' '0058' '0043' '0108' '0091' '0028' '0051' '0236' '0079' '0198'
 '0036' '0113' '0126' '0031' '0098' '0086' '0141' '0044' '0224' '0135'
 '0072' '0063' '0104' '0069' '0160' '0107' '0136' '0078' '0234' '0055'
 '0210' '0171' '0082' '0061' '0118' '0207' '0250' '0077' '0038' '0096'
 '0089' '0233' '0138' '0101' '0056' '0094' '0111' '0070' '0039' '0081'
 '0057' '0121' '0074' '0065' '0134' '0114' '0092' '0228' '0109' '0179'
 '0124' '0066' '0122' '0281' '0064' '0190' '0099' '0158' '0084' '0142'
 '0197' '0144' '0127' '0120' '0048' '0193' '0093' '0203' '0041' '0232'
 '0073' '0080' '0132' '0083' '0265' '0103' '0146' '0129' '0218' '0106'
 '0258' '0183' '0181' '0269' '0199' '0097' '0139' '0221' '0182' '0159'
 '0163' '0180' '0201' '0168' '0220' '0229' '0186' '0223' '0219' '0149'
 '0148' '0246' '0167' '0085' '0185' '0268' '0145' '0131' '0156' '0213'
 '0153' '0170' '0263' '0175' '0151' '0222' '0150' '0227' '0205' '0249'
 '0272' '0212' '0164' '0117' '0231' '0254' '0152' '0253' '0173' '0105'
 '0115' '0259' '0241' '0277' '0192' '0143' '0275' '0206' '0176' '0235'
 '0189' '0287' '0280' '0285' '0286' '0262' '0256' '0215' '0255' '0245'
 '0211' '0261' '0177' '0257' '0279' '0247' '0242' '0191' '0157' '0260'
 '0271' '0240' '0273' '0194' '0252' '0251' '0184' '0278' '0161' '0276'
 '0238' '0266' '0230' '0214' '0188' '0196' '0267' '0195' '0216' '0202'
 '0264' '0282' '0244' '0154' '0147' '0243' '0274' '0284' '0165' '0225'
 '0270' '0162' '0226' '0204' '0248' '0187' '0178' '0237' '0217']

-------------------------------------------------------------------------------------

['Dead' 'Alive']

-------------------------------------------------------------------------------------

['Lung and Bronchus'
 'Other Infectious and Parasitic Diseases including HIV'
 'Chronic Obstructive Pulmonary Disease and Allied Cond' 'Alive'
 'Cerebrovascular Diseases' 'Diseases of Heart' 'Breast' 'Prostate'
 'Vulva' 'Other Cause of Death'
 'In situ, benign or unknown behavior neoplasm'
 'Miscellaneous Malignant Cancer' 'Hypertension without Heart Disease'
 'Melanoma of the Skin' 'Non-Hodgkin Lymphoma' 'Kidney and Renal Pelvis'
 'Urinary Bladder' 'Chronic Lymphocytic Leukemia'
 'Pneumonia and Influenza'
 'State DC not available or state DC available but no COD'
 'Hodgkin Lymphoma' 'Colon excluding Rectum'
 'Suicide and Self-Inflicted Injury' 'Larynx'
 'Accidents and Adverse Effects' 'Stomach'
 'Alzheimers (ICD-9 and 10 only)' 'Diabetes Mellitus'
 'Stomach and Duodenal Ulcers' 'Esophagus' 'Myeloma'
 'Peritoneum, Omentum and Mesentery' 'Acute Myeloid Leukemia' 'Septicemia'
 'Other Diseases of Arteries, Arterioles, Capillaries'
 'Nephritis, Nephrotic Syndrome and Nephrosis' 'Pancreas'
 'Congenital Anomalies' 'Gum and Other Mouth' 'Salivary Gland'
 'Aleukemic, Subleukemic and NOS' 'Brain and Other Nervous System'
 'Uterus, NOS' 'Rectum and Rectosigmoid Junction' 'Ovary' 'Oropharynx'
 'Soft Tissue including Heart' 'Other Acute Leukemia'
 'Symptoms, Signs and Ill-Defined Conditions'
 'Chronic Liver Disease and Cirrhosis' 'Intrahepatic Bile Duct'
 'Corpus Uteri' 'Liver' 'Thyroid' 'Tongue' 'Other Lymphocytic Leukemia'
 'Non-Melanoma Skin' 'Other Oral Cavity and Pharynx' 'Cervix Uteri'
 'Hypopharynx' 'Other Myeloid/Monocytic Leukemia'
 'Chronic Myeloid Leukemia' 'Other Endocrine including Thymus'
 'Atherosclerosis' 'Tonsil' 'Aortic Aneurysm and Dissection'
 'Other Digestive Organs' 'Penis' 'Nose, Nasal Cavity and Middle Ear'
 'Other Biliary' 'Ureter' 'Nasopharynx'
 'Trachea, Mediastinum and Other Respiratory Organs' 'Tuberculosis'
 'Anus, Anal Canal and Anorectum' 'Lip' 'Small Intestine' 'Gallbladder'
 'Homicide and Legal Intervention' 'Pleura'
 'Complications of Pregnancy, Childbirth, Puerperium' 'Bones and Joints'
 'Retroperitoneum' 'Other Female Genital Organs' 'Other Urinary Organs'
 'Eye and Orbit' 'Floor of Mouth' 'Testis' 'Vagina'
 'Acute Lymphocytic Leukemia' 'Other Male Genital Organs'
 'Acute Monocytic Leukemia'
 'Certain Conditions Originating in Perinatal Period' 'Syphilis']

-------------------------------------------------------------------------------------

['$110,000 - $119,999' '$120,000+' '$95,000 - $99,999'
 '$100,000 - $109,999' '$85,000 - $89,999' '$90,000 - $94,999'
 '$80,000 - $84,999' '$75,000 - $79,999' '$70,000 - $74,999'
 '$65,000 - $69,999' '< $40,000' '$60,000 - $64,999' '$55,000 - $59,999'
 '$45,000 - $49,999' '$50,000 - $54,999' '$40,000 - $44,999'
 'Unknown/missing/no match/Not 1990-2024']

-------------------------------------------------------------------------------------

['Counties in metropolitan areas ge 1 million pop'
 'Counties in metropolitan areas of 250,000 to 1 million pop'
 'Nonmetropolitan counties adjacent to a metropolitan area'
 'Nonmetropolitan counties not adjacent to a metropolitan area'
 'Counties in metropolitan areas of lt 250 thousand pop'
 'Unknown/missing/no match/Not 1990-2024'
 'Unknown/missing/no match (Alaska or Hawaii - Entire State)']

-------------------------------------------------------------------------------------

*Demographical Variables*

In [6]:
#Changed data type of age to string 
df['Age recode with <1 year olds and 90+']=df['Age recode with <1 year olds and 90+'].astype(str)
#Remover 'years' from '70-75 years'
df['Age recode with <1 year olds and 90+']=df['Age recode with <1 year olds and 90+'].str.strip(' years')

#'70-75' -> |70| |75|

age_lower = df['Age recode with <1 year olds and 90+'].str.replace('+', '', regex=False).str.split('-').str[0].astype(int)
age_upper = df['Age recode with <1 year olds and 90+'].str.replace('+', '', regex=False).str.split('-').str[-1].astype(int)

#Created a variable age which stores mid point of given age for calculation on age (mean age etc.)
df['Age']=(age_lower+age_upper)/2
df

,Age recode with <1 year olds and 90+,Sex,Year of diagnosis,"Race and origin recode (NHW, NHB, NHAIAN, NHAPI, Hispanic)",Marital status at diagnosis,Primary Site,Histologic Type ICD-O-3,Combined Summary Stage with Expanded Regional Codes (2004+),Radiation recode,"Chemotherapy recode (yes, no/unk)",RX Summ--Surg Prim Site (1998-2022),Survival months,Vital status recode (study cutoff used),COD to site recode,Median household income inflation adj to 2024,Rural-Urban Continuum Code,Age
0,75-79,Female,2006,Non-Hispanic White,Married (including common law),343,8250,Localized only,None/Unknown,No/Unknown,30,0128,Dead,Lung and Bronchus,"$110,000 - $119,999",Counties in metropolitan areas ge 1 million pop,77.0
1,60-64,Male,2001,Non-Hispanic White,Single (never married),340,8140,Blank(s),None/Unknown,No/Unknown,00,0001,Dead,Lung and Bronchus,"$120,000+",Counties in metropolitan areas ge 1 million pop,62.0
2,75-79,Male,2006,Non-Hispanic White,Married (including common law),343,8070,Localized only,None/Unknown,No/Unknown,30,0005,Dead,Other Infectious and Parasitic Diseases includ...,"$95,000 - $99,999",Counties in metropolitan areas ge 1 million pop,77.0
3,75-79,Female,2001,Non-Hispanic White,Widowed,341,8041,Blank(s),None/Unknown,No/Unknown,00,0001,Dead,Lung and Bronchus,"$110,000 - $119,999",Counties in metropolitan areas ge 1 million pop,77.0
4,70-74,Female,2007,Non-Hispanic White,Divorced,341,8046,Distant site(s)/node(s) involved,None/Unknown,No/Unknown,00,0000,Dead,Chronic Obstructive Pulmonary Disease and Alli...,"$110,000 - $119,999",Counties in metropolitan areas ge 1 million pop,72.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1158608,70-74,Male,2023,Non-Hispanic Black,Divorced,343,8000,Unknown/unstaged/unspecified/DCO,None/Unknown,No/Unknown,Blank(s),0000,Dead,Lung and Bronchus,"$50,000 - $54,999",Nonmetropolitan counties adjacent to a metropo...,72.0
1158609,20-24,Male,2016,Non-Hispanic White,Single (never married),343,8240,Regional by direct extension only,None/Unknown,No/Unknown,21,0087,Alive,Alive,"$70,000 - $74,999",Counties in metropolitan areas of lt 250 thous...,22.0
1158610,60-64,Male,2023,Non-Hispanic White,Married (including common law),343,8000,Unknown/unstaged/unspecified/DCO,None/Unknown,No/Unknown,Blank(s),Unknown,Dead,Lung and Bronchus,"$95,000 - $99,999","Counties in metropolitan areas of 250,000 to 1...",62.0
1158611,65-69,Male,2023,Non-Hispanic White,Married (including common law),343,8140,Distant site(s)/node(s) involved,None/Unknown,Yes,Blank(s),0000,Alive,Alive,"$50,000 - $54,999",Counties in metropolitan areas of lt 250 thous...,67.0
1158612,75-79,Female,2013,Non-Hispanic White,Unknown,341,8140,Localized only,None/Unknown,No/Unknown,00,0121,Alive,Alive,"$45,000 - $49,999",Nonmetropolitan counties not adjacent to a met...,77.0

*Tumor*

In [7]:
#Replacing the site code with their actual Anatomical site 

primary_sites = {
    340: "Main bronchus",
    341: "Upper lobe, lung",
    342: "Middle lobe, lung",
    343: "Lower lobe, lung",
    348: "Overlapping lesion of lung",
    349: "Lung, NOS (Not Otherwise Specified)"
}
df['Primary Site'] = df['Primary Site'].map(primary_sites)
df['Cancer_type']='Lung and Bronchus'

In [8]:
#Histology codes are replaced with Their Histological family group name.

bins =   [0,    8009,  8049,  8089,  8149,  8299,  8559,  9999]

#Bins work as intervals and labels as value of the code if it falls in that bin.
# If Histologuy code falls between 7999 to 8009 then it will replace it with 'Neoplasms, NOS'.

labels = [
    "Carcinoma NOS",           # 0–8009
    "Small Cell",              # 8010–8049  ← 8041=small cell
    "Squamous Cell",           # 8050–8089  ← 8070=squamous
    "Large Cell",              # 8090–8149  ← 8012=large cell
    "Adenocarcinoma",          # 8150–8299  ← 8140=adeno, 8250=bronchioloalveolar
    "Adenosquamous/Special",   # 8300–8559  ← 8560=adenosquamous
    "Other"                    # 8560–9999
]

df['Histologic Type ICD-O-3'] = pd.cut(
    pd.to_numeric(df['Histologic Type ICD-O-3'], errors='coerce'), 
    bins=bins, 
    labels=labels, 
    ordered=False
)

*Staging*

In [9]:
#Created a mew variable 'Stage' and changed the given categpries in 'Combined Summary Stage with Expanded Regional Codes (2004+)' to [I,II,III,IV].

stage_mapping = {
    "Localized only": "I",
    "Regional by direct extension only": "II",      
    "Regional lymph nodes involved only": "III",
    "Regional by both direct extension and lymph node involvement": "III",
    "Distant site(s)/node(s) involved": "IV",         
    "Unknown/unstaged/unspecified/DCO": "Unknown",
    "Blank(s)": "Unknown"
}
df['Stage']=df['Combined Summary Stage with Expanded Regional Codes (2004+)'].map(stage_mapping)

*Treatment*

In [10]:
#Created a new variable 'Radiation'  and changed the given categpries in 'Radiation recode' to [Radiation,No Radiation,Unknown].

radiation_map = {
    'None/Unknown': 'No',
    'Beam radiation': 'Yes',
    'Radiation, NOS  method or source not specified': 'Yes',
    'Refused (1988+)': 'No',
    'Recommended, unknown if administered': 'Unknown',
    'Radioactive implants (includes brachytherapy) (1988+)': 'Yes',
    'Combination of beam with implants or isotopes': 'Yes',
    'Radioisotopes (1988+)': 'Yes',
}
df['Radiation'] = df['Radiation recode'].map(radiation_map)

In [11]:
#Created a new variable 'Surgery' and changed the given surgery codes in 'RX Summ--Surg Prim Site (1998-2022)' to [Yes,NO,unknown].

surgery_binary_map = {
    # No surgical intervention
    '0': 'No',
    # Surgical interventions (Destruction, Excisions, Resections)
    '12': 'Yes',
    '13': 'Yes',
    '15': 'Yes',
    '19': 'Yes',
    '20': 'Yes',
    '21': 'Yes',
    '22': 'Yes',
    '23': 'Yes',
    '24': 'Yes',
    '25': 'Yes',
    '30': 'Yes',
    '33': 'Yes',
    '45': 'Yes',
    '46': 'Yes',
    '47': 'Yes',
    '48': 'Yes',
    '55': 'Yes',
    '56': 'Yes',
    '65': 'Yes',
    '66': 'Yes',
    '70': 'Yes',
    '80': 'Yes',
    '90': 'Yes',  # Surgery performed, scope unknown
    
    # Missing, uncollected, or unstageable data
    '99': 'Unknown',
    'Blank(s)': 'Unknown'
}
df['surgery']=df['RX Summ--Surg Prim Site (1998-2022)'].map(surgery_binary_map)

In [12]:
s = df['surgery'] == 'Yes'
r = df['Radiation'] == 'Yes'
c = df['Chemotherapy recode (yes, no/unk)'] == 'Yes'

# Define the conditions in order of priority (most specific to least specific)
conditions = [
    s & r & c,
    s & r,
    s & c,
    r & c,
    s,
    r,
    c
]

# Define the corresponding outputs
choices = [
    'Surgery+Radiation+Chemotherapy',
    'Surgery+Radiation',
    'Surgery+Chemotherapy',
    'Radiation+Chemotherapy',
    'Surgery',
    'Radiation',
    'Chemotherapy'
]

# Apply the conditions and choices to create the new column
df['Treatment'] = np.select(conditions, choices, default='Unknown')

*Outcomes*

In [13]:
#Changed survival month data type to numeric from object
df['Survival months']=pd.to_numeric(df['Survival months'],errors='coerce')
#replaced unknown with NaN
df['Survival months']=df['Survival months'].replace('unknown',np.nan)
#Dropped rows with unknkown Survival months
df=df.dropna(subset=['Survival months'])

In [14]:
#Assigned Binary(0,1) to vital status
df['Vital status recode (study cutoff used)']=df['Vital status recode (study cutoff used)'].replace(['Alive','Dead'],[0,1])

C:\Users\ricky\AppData\Local\Temp\ipykernel_4284\2702481694.py:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['Vital status recode (study cutoff used)']=df['Vital status recode (study cutoff used)'].replace(['Alive','Dead'],[0,1])
C:\Users\ricky\AppData\Local\Temp\ipykernel_4284\2702481694.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Vital status recode (study cutoff used)']=df['Vital status recode (study cutoff used)'].replace(['Alive','Dead'],[0,1])

*SocioEconomic*

In [15]:
#Changed datatype to string
df['Median household income inflation adj to 2024']=df['Median household income inflation adj to 2024'].astype(str)

#'$70,000 - $74,999' -> '70000 - 74999' 
clean_inc = df['Median household income inflation adj to 2024'].str.replace('$', '', regex=False).str.replace(',', '', regex=False).str.replace('+', '', regex=False).str.replace('<', '', regex=False).str.strip()

#'70000 - 74999' -> '70000' | '74999' 
lower = clean_inc.str.split('-').str[0]
upper = clean_inc.str.split('-').str[-1]
# '70000' ->700000 (string to numeric) 
inc_lower=pd.to_numeric(lower,errors='coerce')
inc_upper=pd.to_numeric(upper,errors='coerce')

#Created a variable income which stores mid point of given income for calculation on income (mean inclome etc.)
df['Income']=(inc_lower+inc_upper)/2
df.sample(7)

C:\Users\ricky\AppData\Local\Temp\ipykernel_4284\7351343.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Median household income inflation adj to 2024']=df['Median household income inflation adj to 2024'].astype(str)
C:\Users\ricky\AppData\Local\Temp\ipykernel_4284\7351343.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Income']=(inc_lower+inc_upper)/2

,Age recode with <1 year olds and 90+,Sex,Year of diagnosis,"Race and origin recode (NHW, NHB, NHAIAN, NHAPI, Hispanic)",Marital status at diagnosis,Primary Site,Histologic Type ICD-O-3,Combined Summary Stage with Expanded Regional Codes (2004+),Radiation recode,"Chemotherapy recode (yes, no/unk)",...,COD to site recode,Median household income inflation adj to 2024,Rural-Urban Continuum Code,Age,Cancer_type,Stage,Radiation,surgery,Treatment,Income
751268,70-74,Male,2009,Non-Hispanic White,Married (including common law),Main bronchus,Squamous Cell,Distant site(s)/node(s) involved,None/Unknown,Yes,...,Lung and Bronchus,"$65,000 - $69,999",Nonmetropolitan counties adjacent to a metropo...,72.0,Lung and Bronchus,IV,No,NaN,Chemotherapy,67499.5
518751,80-84,Female,2004,Non-Hispanic White,Divorced,"Upper lobe, lung",Small Cell,Distant site(s)/node(s) involved,Refused (1988+),No/Unknown,...,"Other Diseases of Arteries, Arterioles, Capill...","$95,000 - $99,999",Counties in metropolitan areas ge 1 million pop,82.0,Lung and Bronchus,IV,No,NaN,Unknown,97499.5
369625,65-69,Male,2011,Non-Hispanic Black,Married (including common law),"Lower lobe, lung",Squamous Cell,Localized only,None/Unknown,No/Unknown,...,Lung and Bronchus,"$75,000 - $79,999",Counties in metropolitan areas ge 1 million pop,67.0,Lung and Bronchus,I,No,NaN,Unknown,77499.5
430444,70-74,Female,2013,Non-Hispanic White,Married (including common law),"Lung, NOS (Not Otherwise Specified)",Small Cell,Distant site(s)/node(s) involved,None/Unknown,No/Unknown,...,Lung and Bronchus,"$70,000 - $74,999",Counties in metropolitan areas ge 1 million pop,72.0,Lung and Bronchus,IV,No,NaN,Unknown,72499.5
107532,50-54,Male,2019,Hispanic (All Races),Divorced,"Lower lobe, lung",Adenocarcinoma,Localized only,None/Unknown,No/Unknown,...,Alive,"$90,000 - $94,999",Counties in metropolitan areas ge 1 million pop,52.0,Lung and Bronchus,I,No,Yes,Surgery,92499.5
359674,70-74,Male,2018,Non-Hispanic American Indian/Alaska Native,Married (including common law),"Upper lobe, lung",Large Cell,Localized only,None/Unknown,No/Unknown,...,Alive,"$90,000 - $94,999","Counties in metropolitan areas of 250,000 to 1...",72.0,Lung and Bronchus,I,No,Yes,Surgery,92499.5
449144,65-69,Female,2022,Non-Hispanic White,Married (including common law),"Lower lobe, lung",Adenocarcinoma,Localized only,None/Unknown,No/Unknown,...,Alive,"$90,000 - $94,999",Counties in metropolitan areas ge 1 million pop,67.0,Lung and Bronchus,I,No,Yes,Surgery,92499.5

In [16]:
a=df.columns
a
for i in a:
    print(f'{df[i].value_counts()}')
    print(f'{df[i].value_counts().sum()}')
    print("")
    print('-------------------------------------------------------------------------------------')
    print("")

Age recode with <1 year olds and 90+
70-74    198191
65-69    184725
75-79    182827
60-64    144566
80-84    130969
55-59     98391
85-89     67741
50-54     55285
45-49     26281
90+       25999
40-44     10887
35-39      3986
30-34      1678
25-29       806
20-24       421
15-19       178
10-14        75
01-04        73
00           31
05-09        30
Name: count, dtype: int64
1133140

-------------------------------------------------------------------------------------

Sex
Male      593634
Female    539506
Name: count, dtype: int64
1133140

-------------------------------------------------------------------------------------

Year of diagnosis
2019    49815
2017    49199
2023    49028
2018    48369
2009    48334
2016    48312
2015    48194
2014    47825
2022    47789
2021    47637
2012    47562
2013    47504
2008    47500
2010    47214
2007    47132
2006    46967
2011    46706
2005    46352
2003    45755
2004    45696
2002    45429
2001    45331
2000    44885
2020    44605
Name: count, dtype: int64
1133140

-------------------------------------------------------------------------------------

Race and origin recode (NHW, NHB, NHAIAN, NHAPI, Hispanic)
Non-Hispanic White                            867700
Non-Hispanic Black                            115460
Non-Hispanic Asian or Pacific Islander         72444
Hispanic (All Races)                           69627
Non-Hispanic American Indian/Alaska Native      6254
Non-Hispanic Unknown Race                       1655
Name: count, dtype: int64
1133140

-------------------------------------------------------------------------------------

Marital status at diagnosis
Married (including common law)    562771
Widowed                           218223
Single (never married)            152639
Divorced                          136001
Unknown                            48078
Separated                          12479
Unmarried or Domestic Partner       2949
Name: count, dtype: int64
1133140

-------------------------------------------------------------------------------------

Primary Site
Upper lobe, lung                       558203
Lower lobe, lung                       288556
Lung, NOS (Not Otherwise Specified)    173265
Main bronchus                           51231
Middle lobe, lung                       48896
Overlapping lesion of lung              12989
Name: count, dtype: int64
1133140

-------------------------------------------------------------------------------------

Histologic Type ICD-O-3
Large Cell               374363
Small Cell               331800
Squamous Cell            224728
Adenocarcinoma            80789
Carcinoma NOS             69242
Adenosquamous/Special     36823
Other                     15395
Name: count, dtype: int64
1133140

-------------------------------------------------------------------------------------

Combined Summary Stage with Expanded Regional Codes (2004+)
Distant site(s)/node(s) involved                                490935
Localized only                                                  211123
Blank(s)                                                        181400
Regional lymph nodes involved only                               81425
Regional by direct extension only                                64943
Regional by both direct extension and lymph node involvement     58296
Unknown/unstaged/unspecified/DCO                                 45017
In situ                                                              1
Name: count, dtype: int64
1133140

-------------------------------------------------------------------------------------

Radiation recode
None/Unknown                                             688779
Beam radiation                                           406296
Refused (1988+)                                           21053
Recommended, unknown if administered                       8902
Radiation, NOS  method or source not specified             5422
Combination of beam with implants or isotopes              1217
Radioactive implants (includes brachytherapy) (1988+)      1205
Radioisotopes (1988+)                                       266
Name: count, dtype: int64
1133140

-------------------------------------------------------------------------------------

Chemotherapy recode (yes, no/unk)
No/Unknown    689301
Yes           443839
Name: count, dtype: int64
1133140

-------------------------------------------------------------------------------------

RX Summ--Surg Prim Site (1998-2022)
00          838654
33          110090
Blank(s)     49028
30           46186
21           38779
99           10922
22           10216
45            6105
56            5807
55            4338
90            1974
46            1952
23            1823
20            1552
12            1427
24             891
15             806
19             579
80             487
13             457
25             326
70             218
47             191
48             135
66             120
65              77
Name: count, dtype: int64
1133140

-------------------------------------------------------------------------------------

Survival months
0.0      133095
1.0       96461
2.0       72378
3.0       54100
4.0       46355
          ...
282.0        57
284.0        53
280.0        53
278.0        53
287.0        52
Name: count, Length: 288, dtype: int64
1133140

-------------------------------------------------------------------------------------

Vital status recode (study cutoff used)
1    950760
0    182380
Name: count, dtype: int64
1133140

-------------------------------------------------------------------------------------

COD to site recode
Lung and Bronchus                                        719108
Alive                                                    182380
Diseases of Heart                                         41570
Miscellaneous Malignant Cancer                            32412
Chronic Obstructive Pulmonary Disease and Allied Cond     31384
                                                          ...
Lip                                                          14
Certain Conditions Originating in Perinatal Period            9
Acute Monocytic Leukemia                                      8
Other Male Genital Organs                                     3
Syphilis                                                      1
Name: count, Length: 94, dtype: int64
1133140

-------------------------------------------------------------------------------------

Median household income inflation adj to 2024
$75,000 - $79,999                         131131
$100,000 - $109,999                       106955
$85,000 - $89,999                          99985
$80,000 - $84,999                          99471
$65,000 - $69,999                          89136
$70,000 - $74,999                          84726
$120,000+                                  78934
$110,000 - $119,999                        73594
$90,000 - $94,999                          71924
$60,000 - $64,999                          63667
$95,000 - $99,999                          61556
$55,000 - $59,999                          59266
$50,000 - $54,999                          49818
$45,000 - $49,999                          29222
$40,000 - $44,999                          19268
< $40,000                                  14392
Unknown/missing/no match/Not 1990-2024        95
Name: count, dtype: int64
1133140

-------------------------------------------------------------------------------------

Rural-Urban Continuum Code
Counties in metropolitan areas ge 1 million pop                 615119
Counties in metropolitan areas of 250,000 to 1 million pop      232086
Nonmetropolitan counties adjacent to a metropolitan area        106492
Counties in metropolitan areas of lt 250 thousand pop           103619
Nonmetropolitan counties not adjacent to a metropolitan area     74110
Unknown/missing/no match (Alaska or Hawaii - Entire State)        1619
Unknown/missing/no match/Not 1990-2024                              95
Name: count, dtype: int64
1133140

-------------------------------------------------------------------------------------

Age
72.0    198191
67.0    184725
77.0    182827
62.0    144566
82.0    130969
57.0     98391
87.0     67741
52.0     55285
47.0     26281
90.0     25999
42.0     10887
37.0      3986
32.0      1678
27.0       806
22.0       421
17.0       178
12.0        75
2.5         73
0.0         31
7.0         30
Name: count, dtype: int64
1133140

-------------------------------------------------------------------------------------

Cancer_type
Lung and Bronchus    1133140
Name: count, dtype: int64
1133140

-------------------------------------------------------------------------------------

Stage
IV         490935
Unknown    226417
I          211123
III        139721
II          64943
Name: count, dtype: int64
1133139

-------------------------------------------------------------------------------------

Radiation
No         709832
Yes        414406
Unknown      8902
Name: count, dtype: int64
1133140

-------------------------------------------------------------------------------------

surgery
Yes        234536
Unknown     59950
Name: count, dtype: int64
294486

-------------------------------------------------------------------------------------

Treatment
Unknown                           354213
Radiation+Chemotherapy            222731
Surgery                           165458
Chemotherapy                      161424
Radiation                         160236
Surgery+Chemotherapy               37639
Surgery+Radiation+Chemotherapy     22045
Surgery+Radiation                   9394
Name: count, dtype: int64
1133140

-------------------------------------------------------------------------------------

Income
77499.5     131131
104999.5    106955
87499.5      99985
82499.5      99471
67499.5      89136
72499.5      84726
120000.0     78934
114999.5     73594
92499.5      71924
62499.5      63667
97499.5      61556
57499.5      59266
52499.5      49818
47499.5      29222
42499.5      19268
40000.0      14392
Name: count, dtype: int64
1133045

-------------------------------------------------------------------------------------

In [17]:
df = df.drop(columns=['Unnamed: 0'], errors='ignore')
df.to_csv('Lung_Clean.csv', index=False)
print("Ready for analysis!")
df.info()

Ready for analysis!
<class 'pandas.core.frame.DataFrame'>
Index: 1133140 entries, 0 to 1158612
Data columns (total 23 columns):
 #   Column                                                       Non-Null Count    Dtype
---  ------                                                       --------------    -----
 0   Age recode with <1 year olds and 90+                         1133140 non-null  object
 1   Sex                                                          1133140 non-null  object
 2   Year of diagnosis                                            1133140 non-null  int64
 3   Race and origin recode (NHW, NHB, NHAIAN, NHAPI, Hispanic)   1133140 non-null  object
 4   Marital status at diagnosis                                  1133140 non-null  object
 5   Primary Site                                                 1133140 non-null  object
 6   Histologic Type ICD-O-3                                      1133140 non-null  category
 7   Combined Summary Stage with Expanded Regional Codes (2004+)  1133140 non-null  object
 8   Radiation recode                                             1133140 non-null  object
 9   Chemotherapy recode (yes, no/unk)                            1133140 non-null  object
 10  RX Summ--Surg Prim Site (1998-2022)                          1133140 non-null  object
 11  Survival months                                              1133140 non-null  float64
 12  Vital status recode (study cutoff used)                      1133140 non-null  int64
 13  COD to site recode                                           1133140 non-null  object
 14  Median household income inflation adj to 2024                1133140 non-null  object
 15  Rural-Urban Continuum Code                                   1133140 non-null  object
 16  Age                                                          1133140 non-null  float64
 17  Cancer_type                                                  1133140 non-null  object
 18  Stage                                                        1133139 non-null  object
 19  Radiation                                                    1133140 non-null  object
 20  surgery                                                      294486 non-null   object
 21  Treatment                                                    1133140 non-null  object
 22  Income                                                       1133045 non-null  float64
dtypes: category(1), float64(3), int64(2), object(17)
memory usage: 199.9+ MB