In [1]:
import numpy as np
import pandas as pd

In [2]:
df=pd.read_csv('All Cancer Data/Prostate.csv')
df.sample(7)

,Age recode with <1 year olds and 90+,Sex,Year of diagnosis,"Race and origin recode (NHW, NHB, NHAIAN, NHAPI, Hispanic)",Marital status at diagnosis,Primary Site,Histologic Type ICD-O-3,Combined Summary Stage with Expanded Regional Codes (2004+),Radiation recode,"Chemotherapy recode (yes, no/unk)",RX Summ--Surg Prim Site (1998-2022),Survival months,Vital status recode (study cutoff used),COD to site recode,Median household income inflation adj to 2024,Rural-Urban Continuum Code
139163,50-54 years,Male,2023,Non-Hispanic White,Married (including common law),619,8140,Regional by both direct extension and lymph no...,Beam radiation,No/Unknown,Blank(s),0000,Alive,Alive,"$100,000 - $109,999",Counties in metropolitan areas ge 1 million pop
969970,60-64 years,Male,2004,Non-Hispanic Black,Single (never married),619,8140,Localized only,None/Unknown,No/Unknown,50,0214,Dead,Cerebrovascular Diseases,"$50,000 - $54,999","Counties in metropolitan areas of 250,000 to 1..."
1174136,65-69 years,Male,2013,Non-Hispanic White,Married (including common law),619,8140,Localized only,None/Unknown,No/Unknown,00,0126,Alive,Alive,"$110,000 - $119,999",Counties in metropolitan areas ge 1 million pop
230120,60-64 years,Male,2009,Hispanic (All Races),Married (including common law),619,8140,Localized only,None/Unknown,No/Unknown,50,0171,Alive,Alive,"$65,000 - $69,999","Counties in metropolitan areas of 250,000 to 1..."
1299718,60-64 years,Male,2017,Non-Hispanic White,Married (including common law),619,8140,Localized only,Beam radiation,No/Unknown,00,0073,Alive,Alive,"$55,000 - $59,999",Nonmetropolitan counties adjacent to a metropo...
571664,65-69 years,Male,2021,Non-Hispanic Black,Divorced,619,8140,Localized only,None/Unknown,No/Unknown,00,0026,Alive,Alive,"$90,000 - $94,999",Counties in metropolitan areas ge 1 million pop
46486,70-74 years,Male,2015,Hispanic (All Races),Single (never married),619,8140,Localized only,Beam radiation,No/Unknown,00,0083,Alive,Alive,"$100,000 - $109,999",Counties in metropolitan areas ge 1 million pop

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1334542 entries, 0 to 1334541
Data columns (total 16 columns):
 #   Column                                                       Non-Null Count    Dtype
---  ------                                                       --------------    -----
 0   Age recode with <1 year olds and 90+                         1334542 non-null  object
 1   Sex                                                          1334542 non-null  object
 2   Year of diagnosis                                            1334542 non-null  int64
 3   Race and origin recode (NHW, NHB, NHAIAN, NHAPI, Hispanic)   1334542 non-null  object
 4   Marital status at diagnosis                                  1334542 non-null  object
 5   Primary Site                                                 1334542 non-null  int64
 6   Histologic Type ICD-O-3                                      1334542 non-null  int64
 7   Combined Summary Stage with Expanded Regional Codes (2004+)  1334542 non-null  object
 8   Radiation recode                                             1334542 non-null  object
 9   Chemotherapy recode (yes, no/unk)                            1334542 non-null  object
 10  RX Summ--Surg Prim Site (1998-2022)                          1334542 non-null  object
 11  Survival months                                              1334542 non-null  object
 12  Vital status recode (study cutoff used)                      1334542 non-null  object
 13  COD to site recode                                           1334542 non-null  object
 14  Median household income inflation adj to 2024                1334542 non-null  object
 15  Rural-Urban Continuum Code                                   1334542 non-null  object
dtypes: int64(3), object(13)
memory usage: 162.9+ MB

In [4]:
a=df.columns
for i in a:
    print(f'{df[i].value_counts()}')
    print(f'{df[i].value_counts().sum()}')
    print("")
    print('-------------------------------------------------------------------------------------')
    print("")

Age recode with <1 year olds and 90+
65-69 years    288796
60-64 years    236910
70-74 years    234250
55-59 years    164027
75-79 years    159534
80-84 years     84312
50-54 years     80028
85-89 years     39710
45-49 years     24378
90+ years       16528
40-44 years      5404
35-39 years       506
30-34 years        54
25-29 years        30
01-04 years        23
15-19 years        15
20-24 years        11
00 years           10
10-14 years         8
05-09 years         8
Name: count, dtype: int64
1334542

-------------------------------------------------------------------------------------

Sex
Male    1334542
Name: count, dtype: int64
1334542

-------------------------------------------------------------------------------------

Year of diagnosis
2023    68241
2022    68216
2021    66467
2019    62433
2007    59266
2018    58340
2009    56987
2011    56769
2017    56327
2008    56318
2020    56245
2010    55907
2006    55741
2002    54982
2001    53375
2016    52208
2004    51924
2000    51358
2003    50958
2005    50419
2012    49124
2015    48989
2013    48333
2014    45615
Name: count, dtype: int64
1334542

-------------------------------------------------------------------------------------

Race and origin recode (NHW, NHB, NHAIAN, NHAPI, Hispanic)
Non-Hispanic White                            915081
Non-Hispanic Black                            190102
Hispanic (All Races)                          130987
Non-Hispanic Asian or Pacific Islander         68822
Non-Hispanic Unknown Race                      24009
Non-Hispanic American Indian/Alaska Native      5541
Name: count, dtype: int64
1334542

-------------------------------------------------------------------------------------

Marital status at diagnosis
Married (including common law)    859695
Unknown                           171483
Single (never married)            136590
Divorced                           85638
Widowed                            67558
Separated                          10248
Unmarried or Domestic Partner       3330
Name: count, dtype: int64
1334542

-------------------------------------------------------------------------------------

Primary Site
619    1334542
Name: count, dtype: int64
1334542

-------------------------------------------------------------------------------------

Histologic Type ICD-O-3
8140    1280190
8000      26215
8010      15531
8550       6246
8500       1730
         ...
8230          1
8510          1
9071          1
8901          1
8720          1
Name: count, Length: 114, dtype: int64
1334542

-------------------------------------------------------------------------------------

Combined Summary Stage with Expanded Regional Codes (2004+)
Localized only                                                  839796
Blank(s)                                                        210673
Regional by direct extension only                               115775
Distant site(s)/node(s) involved                                 76741
Unknown/unstaged/unspecified/DCO                                 67459
Regional by both direct extension and lymph node involvement     15119
Regional lymph nodes involved only                                8975
In situ                                                              4
Name: count, dtype: int64
1334542

-------------------------------------------------------------------------------------

Radiation recode
None/Unknown                                             868581
Beam radiation                                           308491
Radioactive implants (includes brachytherapy) (1988+)     74167
Combination of beam with implants or isotopes             50113
Recommended, unknown if administered                      16317
Refused (1988+)                                           11151
Radiation, NOS  method or source not specified             3634
Radioisotopes (1988+)                                      2088
Name: count, dtype: int64
1334542

-------------------------------------------------------------------------------------

Chemotherapy recode (yes, no/unk)
No/Unknown    1318182
Yes             16360
Name: count, dtype: int64
1334542

-------------------------------------------------------------------------------------

RX Summ--Surg Prim Site (1998-2022)
00          789442
50          363769
Blank(s)     68241
22           31482
99           23547
23           12706
21           12315
70            8221
14            7443
19            3294
30            2700
80            2670
15            1945
25            1496
17            1156
24            1155
90            1037
20             966
16             462
18             205
10             189
26             101
Name: count, dtype: int64
1334542

-------------------------------------------------------------------------------------

Survival months
0000    19654
0001    10851
0002    10835
0004    10434
0009    10290
        ...
0283      868
0281      867
0284      805
0285      802
0287      780
Name: count, Length: 289, dtype: int64
1334542

-------------------------------------------------------------------------------------

Vital status recode (study cutoff used)
Alive    830913
Dead     503629
Name: count, dtype: int64
1334542

-------------------------------------------------------------------------------------

COD to site recode
Alive                                                 830913
Prostate                                              121001
Diseases of Heart                                      96440
Other Cause of Death                                   65642
Lung and Bronchus                                      21749
                                                       ...
Floor of Mouth                                            14
Lip                                                       12
Certain Conditions Originating in Perinatal Period         7
Syphilis                                                   5
Complications of Pregnancy, Childbirth, Puerperium         1
Name: count, Length: 87, dtype: int64
1334542

-------------------------------------------------------------------------------------

Median household income inflation adj to 2024
$75,000 - $79,999                         166312
$100,000 - $109,999                       141399
$85,000 - $89,999                         121190
$80,000 - $84,999                         119001
$120,000+                                 115955
$110,000 - $119,999                       101816
$90,000 - $94,999                          98069
$70,000 - $74,999                          93678
$65,000 - $69,999                          92497
$95,000 - $99,999                          79618
$60,000 - $64,999                          59120
$55,000 - $59,999                          54234
$50,000 - $54,999                          44986
$45,000 - $49,999                          23652
$40,000 - $44,999                          13714
< $40,000                                   8827
Unknown/missing/no match/Not 1990-2024       474
Name: count, dtype: int64
1334542

-------------------------------------------------------------------------------------

Rural-Urban Continuum Code
Counties in metropolitan areas ge 1 million pop                 791552
Counties in metropolitan areas of 250,000 to 1 million pop      275212
Counties in metropolitan areas of lt 250 thousand pop           109336
Nonmetropolitan counties adjacent to a metropolitan area         96969
Nonmetropolitan counties not adjacent to a metropolitan area     60367
Unknown/missing/no match (Alaska or Hawaii - Entire State)         632
Unknown/missing/no match/Not 1990-2024                             474
Name: count, dtype: int64
1334542

-------------------------------------------------------------------------------------

In [5]:
b=df.columns
for i in b:
    print(f'{df[i].unique()}')
    print("")
    print('-------------------------------------------------------------------------------------')
    print("")

['70-74 years' '65-69 years' '55-59 years' '80-84 years' '75-79 years'
 '60-64 years' '50-54 years' '45-49 years' '85-89 years' '90+ years'
 '40-44 years' '35-39 years' '15-19 years' '10-14 years' '25-29 years'
 '30-34 years' '01-04 years' '20-24 years' '00 years' '05-09 years']

-------------------------------------------------------------------------------------

['Male']

-------------------------------------------------------------------------------------

[2011 2007 2021 2001 2015 2013 2018 2002 2019 2005 2012 2010 2000 2016
 2009 2022 2008 2017 2004 2023 2003 2006 2014 2020]

-------------------------------------------------------------------------------------

['Non-Hispanic White' 'Hispanic (All Races)' 'Non-Hispanic Black'
 'Non-Hispanic Asian or Pacific Islander'
 'Non-Hispanic American Indian/Alaska Native' 'Non-Hispanic Unknown Race']

-------------------------------------------------------------------------------------

['Unknown' 'Single (never married)' 'Widowed'
 'Married (including common law)' 'Divorced' 'Separated'
 'Unmarried or Domestic Partner']

-------------------------------------------------------------------------------------

[619]

-------------------------------------------------------------------------------------

[8140 8010 8000 8550 8500 8046 8246 8041 8120 8890 9120 8574 9220 8480
 8803 8130 8920 8098 8481 8934 8045 8551 8020 8201 8490 8260 8070 8255
 8380 8501 8935 8523 8910 8013 8240 8200 8503 8323 8980 8263 8560 8801
 8552 8033 8800 8022 8001 8090 8123 8141 8290 8143 8804 8310 8902 9561
 9020 8572 8050 8802 8900 8249 8147 8071 8012 8244 8003 8570 8814 8180
 8810 9364 8082 9260 8680 9540 8410 8014 8805 8912 8440 8806 8021 8015
 8815 8312 9040 8430 8052 8030 8032 8145 8854 9490 8042 8210 8211 8521
 8571 8573 9041 8576 8072 8936 8044 8830 9180 8230 9071 8510 8148 8215
 8901 8720]

-------------------------------------------------------------------------------------

['Localized only' 'Distant site(s)/node(s) involved' 'Blank(s)'
 'Unknown/unstaged/unspecified/DCO' 'Regional lymph nodes involved only'
 'Regional by direct extension only'
 'Regional by both direct extension and lymph node involvement' 'In situ']

-------------------------------------------------------------------------------------

['None/Unknown' 'Radioactive implants (includes brachytherapy) (1988+)'
 'Beam radiation' 'Refused (1988+)'
 'Combination of beam with implants or isotopes'
 'Radiation, NOS  method or source not specified' 'Radioisotopes (1988+)'
 'Recommended, unknown if administered']

-------------------------------------------------------------------------------------

['No/Unknown' 'Yes']

-------------------------------------------------------------------------------------

['00' '50' '22' '23' '21' '99' 'Blank(s)' '19' '30' '15' '14' '80' '70'
 '25' '24' '20' '90' '26' '17' '18' '16' '10']

-------------------------------------------------------------------------------------

['0154' '0061' '0199' '0020' '0191' '0104' '0098' '0065' '0067' '0053'
 '0027' '0155' '0072' '0133' '0160' '0082' '0069' '0076' '0110' '0123'
 '0066' '0028' '0282' '0037' '0064' '0153' '0004' '0003' '0045' '0090'
 '0021' '0049' '0017' '0080' '0073' '0077' '0070' '0111' '0250' '0097'
 '0275' '0137' '0023' '0267' '0135' '0274' '0125' '0278' '0214' '0183'
 '0273' '0263' '0279' '0182' '0262' '0283' '0033' '0185' 'Unknown' '0057'
 '0018' '0006' '0239' '0145' '0050' '0231' '0002' '0083' '0107' '0056'
 '0127' '0009' '0218' '0022' '0220' '0007' '0014' '0170' '0255' '0119'
 '0258' '0042' '0200' '0047' '0142' '0159' '0101' '0186' '0251' '0089'
 '0029' '0232' '0011' '0001' '0139' '0235' '0019' '0041' '0052' '0092'
 '0044' '0032' '0015' '0207' '0280' '0266' '0081' '0132' '0281' '0096'
 '0113' '0062' '0115' '0038' '0086' '0129' '0078' '0128' '0060' '0134'
 '0150' '0187' '0238' '0005' '0165' '0156' '0106' '0152' '0120' '0121'
 '0168' '0225' '0216' '0147' '0087' '0055' '0103' '0277' '0048' '0176'
 '0276' '0026' '0230' '0272' '0143' '0085' '0030' '0181' '0068' '0025'
 '0013' '0079' '0233' '0016' '0131' '0031' '0256' '0091' '0144' '0039'
 '0035' '0130' '0105' '0265' '0204' '0043' '0193' '0188' '0059' '0114'
 '0012' '0058' '0162' '0146' '0074' '0209' '0158' '0192' '0201' '0172'
 '0271' '0248' '0141' '0178' '0100' '0198' '0118' '0206' '0268' '0197'
 '0095' '0117' '0112' '0071' '0213' '0179' '0140' '0177' '0000' '0217'
 '0161' '0243' '0124' '0051' '0236' '0169' '0088' '0136' '0249' '0054'
 '0285' '0203' '0184' '0046' '0215' '0242' '0264' '0010' '0240' '0246'
 '0174' '0164' '0208' '0094' '0202' '0173' '0093' '0234' '0109' '0036'
 '0189' '0024' '0148' '0063' '0226' '0157' '0244' '0205' '0195' '0175'
 '0102' '0008' '0108' '0257' '0163' '0260' '0075' '0253' '0196' '0211'
 '0171' '0116' '0122' '0212' '0084' '0270' '0180' '0138' '0034' '0247'
 '0194' '0245' '0190' '0210' '0151' '0040' '0149' '0223' '0126' '0286'
 '0221' '0099' '0237' '0222' '0259' '0241' '0219' '0228' '0287' '0224'
 '0284' '0166' '0229' '0167' '0227' '0252' '0254' '0261' '0269']

-------------------------------------------------------------------------------------

['Alive' 'Dead']

-------------------------------------------------------------------------------------

['Alive' 'Urinary Bladder'
 'Chronic Obstructive Pulmonary Disease and Allied Cond' 'Prostate'
 'Ureter' 'Alzheimers (ICD-9 and 10 only)' 'Diseases of Heart'
 'Pneumonia and Influenza' 'Brain and Other Nervous System'
 'Other Cause of Death' 'Pancreas' 'Diabetes Mellitus'
 'Soft Tissue including Heart' 'Cerebrovascular Diseases' 'Septicemia'
 'Suicide and Self-Inflicted Injury' 'Lung and Bronchus' 'Myeloma'
 'Kidney and Renal Pelvis' 'Miscellaneous Malignant Cancer'
 'Aortic Aneurysm and Dissection' 'Small Intestine'
 'In situ, benign or unknown behavior neoplasm'
 'Accidents and Adverse Effects' 'Rectum and Rectosigmoid Junction'
 'Other Infectious and Parasitic Diseases including HIV' 'Stomach'
 'Colon excluding Rectum' 'Peritoneum, Omentum and Mesentery'
 'State DC not available or state DC available but no COD'
 'Symptoms, Signs and Ill-Defined Conditions' 'Esophagus'
 'Stomach and Duodenal Ulcers' 'Non-Hodgkin Lymphoma'
 'Acute Myeloid Leukemia' 'Hypertension without Heart Disease'
 'Bones and Joints' 'Melanoma of the Skin'
 'Other Diseases of Arteries, Arterioles, Capillaries'
 'Nephritis, Nephrotic Syndrome and Nephrosis' 'Congenital Anomalies'
 'Chronic Liver Disease and Cirrhosis' 'Liver' 'Retroperitoneum'
 'Atherosclerosis' 'Intrahepatic Bile Duct' 'Non-Melanoma Skin' 'Larynx'
 'Gum and Other Mouth' 'Chronic Lymphocytic Leukemia' 'Breast'
 'Chronic Myeloid Leukemia' 'Oropharynx' 'Tongue' 'Eye and Orbit'
 'Other Lymphocytic Leukemia' 'Hodgkin Lymphoma' 'Gallbladder'
 'Other Oral Cavity and Pharynx' 'Thyroid' 'Penis'
 'Aleukemic, Subleukemic and NOS' 'Acute Lymphocytic Leukemia' 'Testis'
 'Tonsil' 'Other Urinary Organs' 'Other Biliary' 'Other Digestive Organs'
 'Other Myeloid/Monocytic Leukemia' 'Other Acute Leukemia' 'Tuberculosis'
 'Homicide and Legal Intervention' 'Salivary Gland' 'Nasopharynx'
 'Hypopharynx' 'Pleura' 'Other Male Genital Organs'
 'Trachea, Mediastinum and Other Respiratory Organs'
 'Other Endocrine including Thymus' 'Nose, Nasal Cavity and Middle Ear'
 'Anus, Anal Canal and Anorectum'
 'Certain Conditions Originating in Perinatal Period'
 'Acute Monocytic Leukemia' 'Syphilis' 'Floor of Mouth' 'Lip'
 'Complications of Pregnancy, Childbirth, Puerperium']

-------------------------------------------------------------------------------------

['$100,000 - $109,999' '$95,000 - $99,999' '$120,000+'
 '$110,000 - $119,999' 'Unknown/missing/no match/Not 1990-2024'
 '$90,000 - $94,999' '$85,000 - $89,999' '$80,000 - $84,999'
 '$75,000 - $79,999' '$70,000 - $74,999' '$65,000 - $69,999'
 '$60,000 - $64,999' '$50,000 - $54,999' '$45,000 - $49,999'
 '$55,000 - $59,999' '< $40,000' '$40,000 - $44,999']

-------------------------------------------------------------------------------------

['Counties in metropolitan areas ge 1 million pop'
 'Unknown/missing/no match/Not 1990-2024'
 'Counties in metropolitan areas of 250,000 to 1 million pop'
 'Nonmetropolitan counties adjacent to a metropolitan area'
 'Counties in metropolitan areas of lt 250 thousand pop'
 'Nonmetropolitan counties not adjacent to a metropolitan area'
 'Unknown/missing/no match (Alaska or Hawaii - Entire State)']

-------------------------------------------------------------------------------------

*Demographical Variables*

In [6]:
#Changed data type of age to string 
df['Age recode with <1 year olds and 90+']=df['Age recode with <1 year olds and 90+'].astype(str)
#Remover 'years' from '70-75 years'
df['Age recode with <1 year olds and 90+']=df['Age recode with <1 year olds and 90+'].str.strip(' years')

#'70-75' -> |70| |75|

age_lower = df['Age recode with <1 year olds and 90+'].str.replace('+', '', regex=False).str.split('-').str[0].astype(int)
age_upper = df['Age recode with <1 year olds and 90+'].str.replace('+', '', regex=False).str.split('-').str[-1].astype(int)

#Created a variable age which stores mid point of given age for calculation on age (mean age etc.)

df['Age']=(age_lower+age_upper)/2
df

,Age recode with <1 year olds and 90+,Sex,Year of diagnosis,"Race and origin recode (NHW, NHB, NHAIAN, NHAPI, Hispanic)",Marital status at diagnosis,Primary Site,Histologic Type ICD-O-3,Combined Summary Stage with Expanded Regional Codes (2004+),Radiation recode,"Chemotherapy recode (yes, no/unk)",RX Summ--Surg Prim Site (1998-2022),Survival months,Vital status recode (study cutoff used),COD to site recode,Median household income inflation adj to 2024,Rural-Urban Continuum Code,Age
0,70-74,Male,2011,Non-Hispanic White,Unknown,619,8140,Localized only,None/Unknown,No/Unknown,00,0154,Alive,Alive,"$100,000 - $109,999",Counties in metropolitan areas ge 1 million pop,72.0
1,65-69,Male,2011,Non-Hispanic White,Unknown,619,8140,Localized only,None/Unknown,No/Unknown,50,0061,Dead,Urinary Bladder,"$100,000 - $109,999",Counties in metropolitan areas ge 1 million pop,67.0
2,55-59,Male,2007,Hispanic (All Races),Single (never married),619,8140,Localized only,Radioactive implants (includes brachytherapy) ...,No/Unknown,00,0199,Alive,Alive,"$95,000 - $99,999",Counties in metropolitan areas ge 1 million pop,57.0
3,80-84,Male,2021,Non-Hispanic White,Widowed,619,8140,Distant site(s)/node(s) involved,None/Unknown,No/Unknown,00,0020,Dead,Chronic Obstructive Pulmonary Disease and Alli...,"$120,000+",Counties in metropolitan areas ge 1 million pop,82.0
4,75-79,Male,2001,Non-Hispanic White,Unknown,619,8140,Blank(s),Beam radiation,No/Unknown,00,0191,Dead,Prostate,"$120,000+",Counties in metropolitan areas ge 1 million pop,77.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1334537,55-59,Male,2023,Non-Hispanic White,Married (including common law),619,8140,Localized only,None/Unknown,No/Unknown,Blank(s),0011,Alive,Alive,"$50,000 - $54,999",Nonmetropolitan counties adjacent to a metropo...,57.0
1334538,85-89,Male,2023,Non-Hispanic Black,Widowed,619,8140,Localized only,None/Unknown,No/Unknown,Blank(s),0010,Alive,Alive,"$55,000 - $59,999",Counties in metropolitan areas of lt 250 thous...,87.0
1334539,80-84,Male,2023,Non-Hispanic White,Married (including common law),619,8140,Distant site(s)/node(s) involved,Beam radiation,No/Unknown,Blank(s),0000,Alive,Alive,"$100,000 - $109,999",Counties in metropolitan areas ge 1 million pop,82.0
1334540,65-69,Male,2023,Non-Hispanic Black,Married (including common law),619,8140,Unknown/unstaged/unspecified/DCO,None/Unknown,No/Unknown,Blank(s),0002,Alive,Alive,"$95,000 - $99,999","Counties in metropolitan areas of 250,000 to 1...",67.0
1334541,60-64,Male,2023,Non-Hispanic Black,Married (including common law),619,8140,Regional lymph nodes involved only,None/Unknown,No/Unknown,Blank(s),0002,Alive,Alive,"$70,000 - $74,999","Counties in metropolitan areas of 250,000 to 1...",62.0

*Tumor*

In [7]:
#Replacing the site code with their actual Anatomical site 

primary_sites = {
    619: "Prostate, NOS"
}
df['Primary Site'] = df['Primary Site'].map(primary_sites)
df['Cancer_type']='Prostate'

In [8]:
#Histology codes are replaced with Their Histological family group name.

bins =   [0, 8139, 8299, 8549, 9999]

#Bins work as intervals and labels as value of the code if it falls in that bin.
# If Histologuy code falls between 7999 to 8009 then it will replace it with 'Neoplasms, NOS'.

labels = ["Carcinoma NOS", "Adenocarcinoma", "Special Types", "Other"]

df['Histologic Type ICD-O-3'] = pd.cut(
    pd.to_numeric(df['Histologic Type ICD-O-3'], errors='coerce'), 
    bins=bins, 
    labels=labels, 
    ordered=False
)

*Staging*

In [9]:
#Created a mew variable 'Stage' and changed the given categpries in 'Combined Summary Stage with Expanded Regional Codes (2004+)' to [I,II,III,IV].

stage_mapping = {
    "Localized only": "I",
    "Regional by direct extension only": "II",      
    "Regional lymph nodes involved only": "III",
    "Regional by both direct extension and lymph node involvement": "III",
    "Distant site(s)/node(s) involved": "IV",         
    "Unknown/unstaged/unspecified/DCO": "Unknown",
    "Blank(s)": "Unknown"
}
df['Stage']=df['Combined Summary Stage with Expanded Regional Codes (2004+)'].map(stage_mapping)

*Treatment*

In [10]:
#Created a new variable 'Radiation'  and changed the given categpries in 'Radiation recode' to [Radiation,No Radiation,Unknown].

radiation_map = {
    'None/Unknown': 'No',
    'Beam radiation': 'Yes',
    'Radiation, NOS  method or source not specified': 'Yes',
    'Refused (1988+)': 'No',
    'Recommended, unknown if administered': 'Unknown',
    'Radioactive implants (includes brachytherapy) (1988+)': 'Yes',
    'Combination of beam with implants or isotopes': 'Yes',
    'Radioisotopes (1988+)': 'Yes',
}
df['Radiation'] = df['Radiation recode'].map(radiation_map)

In [11]:
#Created a new variable 'Surgery' and changed the given surgery codes in 'RX Summ--Surg Prim Site (1998-2022)' to [Yes,NO,unknown].

surgery_binary_map = {
    # No surgical intervention
    '0': 'No',
    # Surgical interventions (Destruction, Excisions, Resections)
    '12': 'Yes',
    '13': 'Yes',
    '15': 'Yes',
    '19': 'Yes',
    '20': 'Yes',
    '21': 'Yes',
    '22': 'Yes',
    '23': 'Yes',
    '24': 'Yes',
    '25': 'Yes',
    '30': 'Yes',
    '33': 'Yes',
    '45': 'Yes',
    '46': 'Yes',
    '47': 'Yes',
    '48': 'Yes',
    '55': 'Yes',
    '56': 'Yes',
    '65': 'Yes',
    '66': 'Yes',
    '70': 'Yes',
    '80': 'Yes',
    '90': 'Yes',  # Surgery performed, scope unknown
    
    # Missing, uncollected, or unstageable data
    '99': 'Unknown',
    'Blank(s)': 'Unknown'
}
df['surgery']=df['RX Summ--Surg Prim Site (1998-2022)'].map(surgery_binary_map)

In [12]:
s = df['surgery'] == 'Yes'
r = df['Radiation'] == 'Yes'
c = df['Chemotherapy recode (yes, no/unk)'] == 'Yes'

# Define the conditions in order of priority (most specific to least specific)
conditions = [
    s & r & c,
    s & r,
    s & c,
    r & c,
    s,
    r,
    c
]

# Define the corresponding outputs
choices = [
    'Surgery+Radiation+Chemotherapy',
    'Surgery+Radiation',
    'Surgery+Chemotherapy',
    'Radiation+Chemotherapy',
    'Surgery',
    'Radiation',
    'Chemotherapy'
]

# Apply the conditions and choices to create the new column
df['Treatment'] = np.select(conditions, choices, default='Unknown')

*Outcomes*

In [13]:
#Changed survival month data type to numeric from object
df['Survival months']=pd.to_numeric(df['Survival months'],errors='coerce')
#replaced unknown with NaN
df['Survival months']=df['Survival months'].replace('unknown',np.nan)
#Dropped rows with unknkown Survival months
df=df.dropna(subset=['Survival months'])

In [14]:
#Assigned Binary(0,1) to vital status
df['Vital status recode (study cutoff used)']=df['Vital status recode (study cutoff used)'].replace(['Alive','Dead'],[0,1])

C:\Users\ricky\AppData\Local\Temp\ipykernel_5872\2702481694.py:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['Vital status recode (study cutoff used)']=df['Vital status recode (study cutoff used)'].replace(['Alive','Dead'],[0,1])
C:\Users\ricky\AppData\Local\Temp\ipykernel_5872\2702481694.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Vital status recode (study cutoff used)']=df['Vital status recode (study cutoff used)'].replace(['Alive','Dead'],[0,1])

*SocioEconomic*

In [15]:
#Changed datatype to string
df['Median household income inflation adj to 2024']=df['Median household income inflation adj to 2024'].astype(str)

#'$70,000 - $74,999' -> '70000 - 74999' 
clean_inc = df['Median household income inflation adj to 2024'].str.replace('$', '', regex=False).str.replace(',', '', regex=False).str.replace('+', '', regex=False).str.replace('<', '', regex=False).str.strip()

#'70000 - 74999' -> '70000' | '74999' 
lower = clean_inc.str.split('-').str[0]
upper = clean_inc.str.split('-').str[-1]
# '70000' ->700000 (string to numeric) 
inc_lower=pd.to_numeric(lower,errors='coerce')
inc_upper=pd.to_numeric(upper,errors='coerce')

#Created a variable income which stores mid point of given income for calculation on income (mean inclome etc.)
df['Income']=(inc_lower+inc_upper)/2
df.sample(7)

C:\Users\ricky\AppData\Local\Temp\ipykernel_5872\7351343.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Median household income inflation adj to 2024']=df['Median household income inflation adj to 2024'].astype(str)
C:\Users\ricky\AppData\Local\Temp\ipykernel_5872\7351343.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Income']=(inc_lower+inc_upper)/2

,Age recode with <1 year olds and 90+,Sex,Year of diagnosis,"Race and origin recode (NHW, NHB, NHAIAN, NHAPI, Hispanic)",Marital status at diagnosis,Primary Site,Histologic Type ICD-O-3,Combined Summary Stage with Expanded Regional Codes (2004+),Radiation recode,"Chemotherapy recode (yes, no/unk)",...,COD to site recode,Median household income inflation adj to 2024,Rural-Urban Continuum Code,Age,Cancer_type,Stage,Radiation,surgery,Treatment,Income
623462,65-69,Male,2002,Non-Hispanic White,Divorced,"Prostate, NOS",Adenocarcinoma,Blank(s),None/Unknown,No/Unknown,...,Alive,"$65,000 - $69,999","Counties in metropolitan areas of 250,000 to 1...",67.0,Prostate,Unknown,No,NaN,Unknown,67499.5
70508,65-69,Male,2008,Non-Hispanic White,Married (including common law),"Prostate, NOS",Adenocarcinoma,Localized only,None/Unknown,No/Unknown,...,Alive,"$110,000 - $119,999","Counties in metropolitan areas of 250,000 to 1...",67.0,Prostate,I,No,Yes,Surgery,114999.5
1039451,55-59,Male,2022,Non-Hispanic White,Married (including common law),"Prostate, NOS",Adenocarcinoma,Localized only,None/Unknown,No/Unknown,...,Alive,"$40,000 - $44,999",Counties in metropolitan areas of lt 250 thous...,57.0,Prostate,I,No,NaN,Unknown,42499.5
888444,65-69,Male,2000,Non-Hispanic White,Widowed,"Prostate, NOS",Adenocarcinoma,Blank(s),None/Unknown,No/Unknown,...,Alive,"$70,000 - $74,999",Counties in metropolitan areas ge 1 million pop,67.0,Prostate,Unknown,No,NaN,Unknown,72499.5
722010,80-84,Male,2010,Non-Hispanic White,Widowed,"Prostate, NOS",Adenocarcinoma,Localized only,None/Unknown,No/Unknown,...,Prostate,"$85,000 - $89,999",Counties in metropolitan areas ge 1 million pop,82.0,Prostate,I,No,NaN,Unknown,87499.5
530661,60-64,Male,2012,Non-Hispanic Asian or Pacific Islander,Married (including common law),"Prostate, NOS",Adenocarcinoma,Localized only,None/Unknown,No/Unknown,...,Alive,"$70,000 - $74,999",Counties in metropolitan areas ge 1 million pop,62.0,Prostate,I,No,NaN,Unknown,72499.5
22881,45-49,Male,2006,Non-Hispanic Black,Married (including common law),"Prostate, NOS",Adenocarcinoma,Localized only,Radioactive implants (includes brachytherapy) ...,No/Unknown,...,Alive,"$100,000 - $109,999",Counties in metropolitan areas ge 1 million pop,47.0,Prostate,I,Yes,NaN,Radiation,104999.5

In [16]:
a=df.columns
a
for i in a:
    print(f'{df[i].value_counts()}')
    print(f'{df[i].value_counts().sum()}')
    print("")
    print('-------------------------------------------------------------------------------------')
    print("")

Age recode with <1 year olds and 90+
65-69    288281
60-64    236581
70-74    233407
55-59    163852
75-79    158308
80-84     82507
50-54     79958
85-89     37332
45-49     24344
90+       13649
40-44      5398
35-39       505
30-34        53
25-29        28
01-04        23
15-19        15
20-24        11
00           10
10-14         8
05-09         8
Name: count, dtype: int64
1324278

-------------------------------------------------------------------------------------

Sex
Male    1324278
Name: count, dtype: int64
1324278

-------------------------------------------------------------------------------------

Year of diagnosis
2023    67904
2022    67778
2021    65947
2019    61988
2007    58842
2018    57889
2009    56571
2011    56408
2017    56008
2008    55966
2020    55774
2010    55492
2006    55326
2002    54477
2001    52926
2016    51774
2004    51493
2000    50930
2003    50522
2005    49923
2012    48759
2015    48526
2013    47932
2014    45123
Name: count, dtype: int64
1324278

-------------------------------------------------------------------------------------

Race and origin recode (NHW, NHB, NHAIAN, NHAPI, Hispanic)
Non-Hispanic White                            908022
Non-Hispanic Black                            188368
Hispanic (All Races)                          130045
Non-Hispanic Asian or Pacific Islander         68397
Non-Hispanic Unknown Race                      23969
Non-Hispanic American Indian/Alaska Native      5477
Name: count, dtype: int64
1324278

-------------------------------------------------------------------------------------

Marital status at diagnosis
Married (including common law)    855380
Unknown                           170998
Single (never married)            135689
Divorced                           84384
Widowed                            64387
Separated                          10116
Unmarried or Domestic Partner       3324
Name: count, dtype: int64
1324278

-------------------------------------------------------------------------------------

Primary Site
Prostate, NOS    1324278
Name: count, dtype: int64
1324278

-------------------------------------------------------------------------------------

Histologic Type ICD-O-3
Adenocarcinoma    1279938
Carcinoma NOS       34477
Other                7152
Special Types        2711
Name: count, dtype: int64
1324278

-------------------------------------------------------------------------------------

Combined Summary Stage with Expanded Regional Codes (2004+)
Localized only                                                  839628
Blank(s)                                                        208855
Regional by direct extension only                               115756
Distant site(s)/node(s) involved                                 76687
Unknown/unstaged/unspecified/DCO                                 59259
Regional by both direct extension and lymph node involvement     15118
Regional lymph nodes involved only                                8971
In situ                                                              4
Name: count, dtype: int64
1324278

-------------------------------------------------------------------------------------

Radiation recode
None/Unknown                                             858317
Beam radiation                                           308491
Radioactive implants (includes brachytherapy) (1988+)     74167
Combination of beam with implants or isotopes             50113
Recommended, unknown if administered                      16317
Refused (1988+)                                           11151
Radiation, NOS  method or source not specified             3634
Radioisotopes (1988+)                                      2088
Name: count, dtype: int64
1324278

-------------------------------------------------------------------------------------

Chemotherapy recode (yes, no/unk)
No/Unknown    1307918
Yes             16360
Name: count, dtype: int64
1324278

-------------------------------------------------------------------------------------

RX Summ--Surg Prim Site (1998-2022)
00          788657
50          363769
Blank(s)     67904
22           31482
99           14405
23           12706
21           12315
70            8221
14            7443
19            3294
30            2700
80            2670
15            1945
25            1496
17            1156
24            1155
90            1037
20             966
16             462
18             205
10             189
26             101
Name: count, dtype: int64
1324278

-------------------------------------------------------------------------------------

Survival months
0.0      19654
1.0      10851
2.0      10835
4.0      10434
9.0      10290
         ...
283.0      868
281.0      867
284.0      805
285.0      802
287.0      780
Name: count, Length: 288, dtype: int64
1324278

-------------------------------------------------------------------------------------

Vital status recode (study cutoff used)
0    830884
1    493394
Name: count, dtype: int64
1324278

-------------------------------------------------------------------------------------

COD to site recode
Alive                                                 830884
Prostate                                              113918
Diseases of Heart                                      95211
Other Cause of Death                                   65160
Lung and Bronchus                                      21700
                                                       ...
Floor of Mouth                                            14
Lip                                                       12
Certain Conditions Originating in Perinatal Period         7
Syphilis                                                   4
Complications of Pregnancy, Childbirth, Puerperium         1
Name: count, Length: 87, dtype: int64
1324278

-------------------------------------------------------------------------------------

Median household income inflation adj to 2024
$75,000 - $79,999                         164995
$100,000 - $109,999                       140399
$85,000 - $89,999                         120114
$80,000 - $84,999                         118181
$120,000+                                 115316
$110,000 - $119,999                       101136
$90,000 - $94,999                          97344
$70,000 - $74,999                          92897
$65,000 - $69,999                          91817
$95,000 - $99,999                          79100
$60,000 - $64,999                          58634
$55,000 - $59,999                          53721
$50,000 - $54,999                          44496
$45,000 - $49,999                          23375
$40,000 - $44,999                          13569
< $40,000                                   8715
Unknown/missing/no match/Not 1990-2024       469
Name: count, dtype: int64
1324278

-------------------------------------------------------------------------------------

Rural-Urban Continuum Code
Counties in metropolitan areas ge 1 million pop                 785765
Counties in metropolitan areas of 250,000 to 1 million pop      272980
Counties in metropolitan areas of lt 250 thousand pop           108521
Nonmetropolitan counties adjacent to a metropolitan area         96151
Nonmetropolitan counties not adjacent to a metropolitan area     59767
Unknown/missing/no match (Alaska or Hawaii - Entire State)         625
Unknown/missing/no match/Not 1990-2024                             469
Name: count, dtype: int64
1324278

-------------------------------------------------------------------------------------

Age
67.0    288281
62.0    236581
72.0    233407
57.0    163852
77.0    158308
82.0     82507
52.0     79958
87.0     37332
47.0     24344
90.0     13649
42.0      5398
37.0       505
32.0        53
27.0        28
2.5         23
17.0        15
22.0        11
0.0         10
12.0         8
7.0          8
Name: count, dtype: int64
1324278

-------------------------------------------------------------------------------------

Cancer_type
Prostate    1324278
Name: count, dtype: int64
1324278

-------------------------------------------------------------------------------------

Stage
I          839628
Unknown    268114
II         115756
IV          76687
III         24089
Name: count, dtype: int64
1324274

-------------------------------------------------------------------------------------

Radiation
No         869468
Yes        438493
Unknown     16317
Name: count, dtype: int64
1324278

-------------------------------------------------------------------------------------

surgery
Unknown    82309
Yes        79987
Name: count, dtype: int64
162296

-------------------------------------------------------------------------------------

Treatment
Unknown                           808345
Radiation                         421032
Surgery                            66804
Surgery+Radiation                  11737
Chemotherapy                        9660
Radiation+Chemotherapy              5254
Surgery+Chemotherapy                 976
Surgery+Radiation+Chemotherapy       470
Name: count, dtype: int64
1324278

-------------------------------------------------------------------------------------

Income
77499.5     164995
104999.5    140399
87499.5     120114
82499.5     118181
120000.0    115316
114999.5    101136
92499.5      97344
72499.5      92897
67499.5      91817
97499.5      79100
62499.5      58634
57499.5      53721
52499.5      44496
47499.5      23375
42499.5      13569
40000.0       8715
Name: count, dtype: int64
1323809

-------------------------------------------------------------------------------------

In [17]:
df = df.drop(columns=['Unnamed: 0'], errors='ignore')
df.to_csv('Prostate_Clean.csv', index=False)
print("Ready for analysis!")
df.info()

Ready for analysis!
<class 'pandas.core.frame.DataFrame'>
Index: 1324278 entries, 0 to 1334541
Data columns (total 23 columns):
 #   Column                                                       Non-Null Count    Dtype
---  ------                                                       --------------    -----
 0   Age recode with <1 year olds and 90+                         1324278 non-null  object
 1   Sex                                                          1324278 non-null  object
 2   Year of diagnosis                                            1324278 non-null  int64
 3   Race and origin recode (NHW, NHB, NHAIAN, NHAPI, Hispanic)   1324278 non-null  object
 4   Marital status at diagnosis                                  1324278 non-null  object
 5   Primary Site                                                 1324278 non-null  object
 6   Histologic Type ICD-O-3                                      1324278 non-null  category
 7   Combined Summary Stage with Expanded Regional Codes (2004+)  1324278 non-null  object
 8   Radiation recode                                             1324278 non-null  object
 9   Chemotherapy recode (yes, no/unk)                            1324278 non-null  object
 10  RX Summ--Surg Prim Site (1998-2022)                          1324278 non-null  object
 11  Survival months                                              1324278 non-null  float64
 12  Vital status recode (study cutoff used)                      1324278 non-null  int64
 13  COD to site recode                                           1324278 non-null  object
 14  Median household income inflation adj to 2024                1324278 non-null  object
 15  Rural-Urban Continuum Code                                   1324278 non-null  object
 16  Age                                                          1324278 non-null  float64
 17  Cancer_type                                                  1324278 non-null  object
 18  Stage                                                        1324274 non-null  object
 19  Radiation                                                    1324278 non-null  object
 20  surgery                                                      162296 non-null   object
 21  Treatment                                                    1324278 non-null  object
 22  Income                                                       1323809 non-null  float64
dtypes: category(1), float64(3), int64(2), object(17)
memory usage: 233.6+ MB