In [1]:
import numpy as np
import pandas as pd

In [2]:
df=pd.read_csv('All Cancer Data/Stomach.csv')
df.sample(7)

,Age recode with <1 year olds and 90+,Sex,Year of diagnosis,"Race and origin recode (NHW, NHB, NHAIAN, NHAPI, Hispanic)",Marital status at diagnosis,Primary Site,Histologic Type ICD-O-3,Combined Summary Stage with Expanded Regional Codes (2004+),Radiation recode,"Chemotherapy recode (yes, no/unk)",RX Summ--Surg Prim Site (1998-2022),Survival months,Vital status recode (study cutoff used),COD to site recode,Median household income inflation adj to 2024,Rural-Urban Continuum Code
98588,80-84 years,Female,2015,Non-Hispanic White,Widowed,160,8936,Localized only,None/Unknown,Yes,33,0074,Dead,Diseases of Heart,"$100,000 - $109,999",Counties in metropolitan areas ge 1 million pop
41940,30-34 years,Female,2008,Non-Hispanic Black,Separated,160,8140,Regional by both direct extension and lymph no...,None/Unknown,Yes,50,0018,Dead,Stomach,"$60,000 - $64,999",Counties in metropolitan areas ge 1 million pop
47308,70-74 years,Male,2005,Non-Hispanic Asian or Pacific Islander,Married (including common law),160,8490,Localized only,None/Unknown,No/Unknown,27,0050,Dead,Stomach,"$120,000+",Counties in metropolitan areas ge 1 million pop
111557,75-79 years,Male,2008,Non-Hispanic White,Divorced,160,8140,Regional by both direct extension and lymph no...,Beam radiation,Yes,51,0008,Dead,Esophagus,"$55,000 - $59,999","Counties in metropolitan areas of 250,000 to 1..."
9290,35-39 years,Female,2023,Non-Hispanic White,Unknown,169,8936,Unknown/unstaged/unspecified/DCO,None/Unknown,No/Unknown,Blank(s),0009,Alive,Alive,"$120,000+",Counties in metropolitan areas ge 1 million pop
84825,90+ years,Male,2007,Non-Hispanic White,Widowed,160,8144,Localized only,None/Unknown,Yes,00,0004,Dead,Stomach,"$100,000 - $109,999",Counties in metropolitan areas ge 1 million pop
152002,65-69 years,Male,2014,Non-Hispanic White,Married (including common law),165,8000,Distant site(s)/node(s) involved,None/Unknown,No/Unknown,00,0001,Dead,Miscellaneous Malignant Cancer,"$70,000 - $74,999",Counties in metropolitan areas ge 1 million pop

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 156289 entries, 0 to 156288
Data columns (total 16 columns):
 #   Column                                                       Non-Null Count   Dtype
---  ------                                                       --------------   -----
 0   Age recode with <1 year olds and 90+                         156289 non-null  object
 1   Sex                                                          156289 non-null  object
 2   Year of diagnosis                                            156289 non-null  int64
 3   Race and origin recode (NHW, NHB, NHAIAN, NHAPI, Hispanic)   156289 non-null  object
 4   Marital status at diagnosis                                  156289 non-null  object
 5   Primary Site                                                 156289 non-null  int64
 6   Histologic Type ICD-O-3                                      156289 non-null  int64
 7   Combined Summary Stage with Expanded Regional Codes (2004+)  156289 non-null  object
 8   Radiation recode                                             156289 non-null  object
 9   Chemotherapy recode (yes, no/unk)                            156289 non-null  object
 10  RX Summ--Surg Prim Site (1998-2022)                          156289 non-null  object
 11  Survival months                                              156289 non-null  object
 12  Vital status recode (study cutoff used)                      156289 non-null  object
 13  COD to site recode                                           156289 non-null  object
 14  Median household income inflation adj to 2024                156289 non-null  object
 15  Rural-Urban Continuum Code                                   156289 non-null  object
dtypes: int64(3), object(13)
memory usage: 19.1+ MB

In [4]:
a=df.columns
for i in a:
    print(f'{df[i].value_counts()}')
    print(f'{df[i].value_counts().sum()}')
    print("")
    print('-------------------------------------------------------------------------------------')
    print("")

Age recode with <1 year olds and 90+
70-74 years    21243
65-69 years    20525
75-79 years    20349
60-64 years    17679
80-84 years    16998
55-59 years    14368
85-89 years    11194
50-54 years    10636
45-49 years     7213
90+ years       5925
40-44 years     4576
35-39 years     2811
30-34 years     1583
25-29 years      708
20-24 years      327
15-19 years      103
10-14 years       38
01-04 years        6
05-09 years        4
00 years           3
Name: count, dtype: int64
156289

-------------------------------------------------------------------------------------

Sex
Male      93610
Female    62679
Name: count, dtype: int64
156289

-------------------------------------------------------------------------------------

Year of diagnosis
2023    8491
2022    8236
2021    8069
2019    6987
2018    6967
2017    6912
2015    6721
2014    6701
2016    6672
2020    6659
2012    6492
2013    6490
2010    6255
2009    6230
2011    6222
2007    5969
2004    5954
2008    5882
2005    5806
2006    5791
2002    5772
2003    5732
2000    5717
2001    5562
Name: count, dtype: int64
156289

-------------------------------------------------------------------------------------

Race and origin recode (NHW, NHB, NHAIAN, NHAPI, Hispanic)
Non-Hispanic White                            81542
Hispanic (All Races)                          30239
Non-Hispanic Asian or Pacific Islander        21969
Non-Hispanic Black                            20539
Non-Hispanic American Indian/Alaska Native     1416
Non-Hispanic Unknown Race                       584
Name: count, dtype: int64
156289

-------------------------------------------------------------------------------------

Marital status at diagnosis
Married (including common law)    85645
Widowed                           23955
Single (never married)            23163
Divorced                          12466
Unknown                            8853
Separated                          1711
Unmarried or Domestic Partner       496
Name: count, dtype: int64
156289

-------------------------------------------------------------------------------------

Primary Site
160    42182
169    30849
163    25672
162    17052
165    11339
168    10508
161     8008
166     6795
164     3884
Name: count, dtype: int64
156289

-------------------------------------------------------------------------------------

Histologic Type ICD-O-3
8140    72758
8490    22720
8936    14191
8144    11389
8240     7837
        ...
8441        1
8910        1
8803        1
8730        1
9085        1
Name: count, Length: 147, dtype: int64
156289

-------------------------------------------------------------------------------------

Combined Summary Stage with Expanded Regional Codes (2004+)
Distant site(s)/node(s) involved                                44744
Localized only                                                  41144
Blank(s)                                                        22783
Unknown/unstaged/unspecified/DCO                                15392
Regional lymph nodes involved only                              13462
Regional by both direct extension and lymph node involvement    12572
Regional by direct extension only                                6192
Name: count, dtype: int64
156289

-------------------------------------------------------------------------------------

Radiation recode
None/Unknown                                             123998
Beam radiation                                            28854
Refused (1988+)                                            1701
Recommended, unknown if administered                       1121
Radiation, NOS  method or source not specified              493
Combination of beam with implants or isotopes                45
Radioactive implants (includes brachytherapy) (1988+)        40
Radioisotopes (1988+)                                        37
Name: count, dtype: int64
156289

-------------------------------------------------------------------------------------

Chemotherapy recode (yes, no/unk)
No/Unknown    90088
Yes           66201
Name: count, dtype: int64
156289

-------------------------------------------------------------------------------------

RX Summ--Surg Prim Site (1998-2022)
00          78433
30          15471
32          10483
Blank(s)     8491
51           7245
42           4984
27           3641
61           3606
33           3174
26           3019
99           2571
52           2375
50           2161
31           2051
62           1854
40           1406
20           1296
41            772
63            757
90            722
60            635
80            399
22            388
24             84
12             48
10             42
23             40
25             40
14             33
11             27
13             21
21             20
Name: count, dtype: int64
156289

-------------------------------------------------------------------------------------

Survival months
0000    14806
0001    11538
0002     8926
0003     6718
0004     5946
        ...
0277       17
0285       16
0283       16
0271       16
0284       13
Name: count, Length: 289, dtype: int64
156289

-------------------------------------------------------------------------------------

Vital status recode (study cutoff used)
Dead     116288
Alive     40001
Name: count, dtype: int64
156289

-------------------------------------------------------------------------------------

COD to site recode
Stomach                                               66858
Alive                                                 40001
Esophagus                                             14721
Diseases of Heart                                      6223
Other Cause of Death                                   4522
                                                      ...
Floor of Mouth                                            2
Anus, Anal Canal and Anorectum                            2
Trachea, Mediastinum and Other Respiratory Organs         2
Other Male Genital Organs                                 1
Certain Conditions Originating in Perinatal Period        1
Name: count, Length: 89, dtype: int64
156289

-------------------------------------------------------------------------------------

Median household income inflation adj to 2024
$75,000 - $79,999                         22370
$100,000 - $109,999                       16363
$85,000 - $89,999                         14276
$120,000+                                 13987
$80,000 - $84,999                         13331
$90,000 - $94,999                         12428
$110,000 - $119,999                       11547
$70,000 - $74,999                         10816
$65,000 - $69,999                          9740
$95,000 - $99,999                          9161
$60,000 - $64,999                          6029
$55,000 - $59,999                          5832
$50,000 - $54,999                          4936
$45,000 - $49,999                          2806
$40,000 - $44,999                          1530
< $40,000                                  1115
Unknown/missing/no match/Not 1990-2024       22
Name: count, dtype: int64
156289

-------------------------------------------------------------------------------------

Rural-Urban Continuum Code
Counties in metropolitan areas ge 1 million pop                 98876
Counties in metropolitan areas of 250,000 to 1 million pop      30460
Counties in metropolitan areas of lt 250 thousand pop           10707
Nonmetropolitan counties adjacent to a metropolitan area         9390
Nonmetropolitan counties not adjacent to a metropolitan area     6414
Unknown/missing/no match (Alaska or Hawaii - Entire State)        420
Unknown/missing/no match/Not 1990-2024                             22
Name: count, dtype: int64
156289

-------------------------------------------------------------------------------------

In [5]:
b=df.columns
for i in b:
    print(f'{df[i].unique()}')
    print("")
    print('-------------------------------------------------------------------------------------')
    print("")

['80-84 years' '65-69 years' '60-64 years' '90+ years' '75-79 years'
 '45-49 years' '85-89 years' '50-54 years' '30-34 years' '55-59 years'
 '70-74 years' '40-44 years' '35-39 years' '25-29 years' '20-24 years'
 '15-19 years' '10-14 years' '01-04 years' '05-09 years' '00 years']

-------------------------------------------------------------------------------------

['Female' 'Male']

-------------------------------------------------------------------------------------

[2009 2022 2010 2008 2003 2000 2014 2005 2020 2002 2021 2012 2011 2001
 2004 2016 2017 2023 2007 2006 2015 2018 2019 2013]

-------------------------------------------------------------------------------------

['Non-Hispanic White' 'Non-Hispanic Asian or Pacific Islander'
 'Non-Hispanic Black' 'Hispanic (All Races)'
 'Non-Hispanic American Indian/Alaska Native' 'Non-Hispanic Unknown Race']

-------------------------------------------------------------------------------------

['Widowed' 'Married (including common law)' 'Single (never married)'
 'Unknown' 'Divorced' 'Unmarried or Domestic Partner' 'Separated']

-------------------------------------------------------------------------------------

[160 168 169 162 165 164 163 161 166]

-------------------------------------------------------------------------------------

[8490 8936 8140 8480 8010 9090 8144 8000 8246 8145 8240 8020 8013 8261
 8070 8142 8323 8211 8245 8032 8574 8249 8720 8255 8210 8481 8263 8560
 8260 8890 8012 8041 8891 8046 8153 8071 8083 8143 8935 8082 8310 8800
 8550 8050 8262 8510 8840 9120 8072 8021 8512 8802 8576 8244 8001 8858
 8711 8033 8004 8170 8214 8241 8801 9150 8963 8980 8074 8242 8022 8045
 8700 8851 9560 8805 8221 9260 8830 8243 8896 9064 8230 8960 8806 8572
 9364 8044 8220 9100 8290 8500 8154 8933 9473 9040 8003 8850 8931 8714
 8680 9133 8976 8930 8810 8852 8570 8031 8450 9071 8201 8804 9540 8523
 8811 8507 8410 8990 8200 8252 9041 9500 8815 8912 8575 9490 8160 8895
 9080 8014 8147 8156 8253 8900 8320 8042 9580 8452 8821 8141 8950 8441
 8940 8503 8910 8051 8803 8730 9085]

-------------------------------------------------------------------------------------

['Regional by direct extension only' 'Localized only' 'Blank(s)'
 'Regional lymph nodes involved only' 'Distant site(s)/node(s) involved'
 'Regional by both direct extension and lymph node involvement'
 'Unknown/unstaged/unspecified/DCO']

-------------------------------------------------------------------------------------

['None/Unknown' 'Refused (1988+)' 'Beam radiation'
 'Radiation, NOS  method or source not specified'
 'Recommended, unknown if administered' 'Radioisotopes (1988+)'
 'Radioactive implants (includes brachytherapy) (1988+)'
 'Combination of beam with implants or isotopes']

-------------------------------------------------------------------------------------

['No/Unknown' 'Yes']

-------------------------------------------------------------------------------------

['21' '30' '51' '00' '42' '62' '33' '32' '40' '52' 'Blank(s)' '61' '26'
 '99' '27' '31' '50' '12' '60' '90' '20' '13' '41' '63' '80' '14' '11'
 '22' '25' '24' '10' '23']

-------------------------------------------------------------------------------------

['0011' '0019' '0014' '0007' '0095' '0010' '0002' '0001' '0027' '0005'
 '0258' '0000' '0008' '0240' '0062' '0028' '0009' '0018' '0036' '0169'
 '0006' '0037' '0012' '0130' '0022' '0069' '0125' '0166' '0047' '0003'
 '0045' '0013' 'Unknown' '0023' '0004' '0056' '0160' '0029' '0081' '0064'
 '0057' '0170' '0024' '0159' '0187' '0017' '0030' '0111' '0131' '0026'
 '0075' '0137' '0021' '0055' '0172' '0115' '0016' '0025' '0020' '0051'
 '0033' '0088' '0104' '0128' '0117' '0059' '0031' '0228' '0050' '0083'
 '0044' '0015' '0138' '0073' '0039' '0072' '0065' '0183' '0076' '0151'
 '0035' '0054' '0096' '0217' '0102' '0046' '0143' '0052' '0135' '0087'
 '0091' '0038' '0116' '0156' '0107' '0154' '0060' '0049' '0078' '0089'
 '0080' '0126' '0101' '0153' '0034' '0084' '0100' '0058' '0152' '0042'
 '0079' '0150' '0168' '0077' '0282' '0194' '0254' '0167' '0173' '0188'
 '0189' '0048' '0285' '0205' '0063' '0119' '0085' '0223' '0113' '0074'
 '0175' '0249' '0108' '0279' '0132' '0280' '0206' '0277' '0098' '0199'
 '0155' '0053' '0043' '0273' '0105' '0263' '0272' '0270' '0210' '0092'
 '0265' '0110' '0177' '0196' '0245' '0264' '0161' '0260' '0261' '0136'
 '0197' '0099' '0133' '0071' '0195' '0281' '0120' '0235' '0251' '0114'
 '0162' '0255' '0066' '0286' '0211' '0276' '0106' '0093' '0112' '0129'
 '0269' '0094' '0224' '0274' '0124' '0040' '0208' '0103' '0201' '0257'
 '0181' '0165' '0268' '0236' '0239' '0121' '0109' '0070' '0244' '0209'
 '0180' '0061' '0212' '0256' '0041' '0174' '0171' '0032' '0231' '0253'
 '0229' '0186' '0246' '0250' '0082' '0233' '0248' '0227' '0192' '0204'
 '0247' '0163' '0215' '0238' '0118' '0140' '0222' '0145' '0230' '0243'
 '0242' '0225' '0184' '0146' '0090' '0122' '0067' '0221' '0214' '0219'
 '0234' '0237' '0191' '0157' '0178' '0198' '0226' '0220' '0086' '0139'
 '0203' '0149' '0213' '0218' '0216' '0141' '0176' '0207' '0127' '0144'
 '0200' '0202' '0193' '0179' '0164' '0190' '0185' '0182' '0097' '0142'
 '0068' '0158' '0134' '0123' '0148' '0147' '0267' '0283' '0275' '0232'
 '0287' '0278' '0271' '0266' '0252' '0259' '0241' '0262' '0284']

-------------------------------------------------------------------------------------

['Dead' 'Alive']

-------------------------------------------------------------------------------------

['Esophagus' 'Alive' 'Miscellaneous Malignant Cancer' 'Diseases of Heart'
 'Stomach' 'State DC not available or state DC available but no COD'
 'In situ, benign or unknown behavior neoplasm' 'Other Cause of Death'
 'Chronic Obstructive Pulmonary Disease and Allied Cond'
 'Lung and Bronchus' 'Nephritis, Nephrotic Syndrome and Nephrosis'
 'Other Digestive Organs' 'Ovary' 'Prostate' 'Larynx'
 'Other Infectious and Parasitic Diseases including HIV'
 'Diabetes Mellitus' 'Pancreas' 'Alzheimers (ICD-9 and 10 only)' 'Breast'
 'Urinary Bladder' 'Colon excluding Rectum' 'Corpus Uteri'
 'Kidney and Renal Pelvis' 'Acute Myeloid Leukemia'
 'Intrahepatic Bile Duct' 'Septicemia' 'Non-Melanoma Skin' 'Liver'
 'Cerebrovascular Diseases' 'Soft Tissue including Heart'
 'Pneumonia and Influenza' 'Small Intestine' 'Non-Hodgkin Lymphoma'
 'Rectum and Rectosigmoid Junction' 'Hypertension without Heart Disease'
 'Accidents and Adverse Effects' 'Other Biliary'
 'Suicide and Self-Inflicted Injury'
 'Symptoms, Signs and Ill-Defined Conditions' 'Atherosclerosis'
 'Stomach and Duodenal Ulcers' 'Chronic Myeloid Leukemia'
 'Chronic Liver Disease and Cirrhosis' 'Tuberculosis'
 'Peritoneum, Omentum and Mesentery' 'Aleukemic, Subleukemic and NOS'
 'Homicide and Legal Intervention' 'Melanoma of the Skin'
 'Aortic Aneurysm and Dissection' 'Brain and Other Nervous System'
 'Thyroid' 'Other Oral Cavity and Pharynx' 'Myeloma' 'Retroperitoneum'
 'Gallbladder' 'Tongue' 'Chronic Lymphocytic Leukemia'
 'Other Endocrine including Thymus' 'Hodgkin Lymphoma'
 'Other Diseases of Arteries, Arterioles, Capillaries'
 'Other Acute Leukemia' 'Congenital Anomalies' 'Gum and Other Mouth'
 'Other Male Genital Organs' 'Cervix Uteri' 'Oropharynx' 'Nasopharynx'
 'Other Urinary Organs' 'Testis' 'Hypopharynx' 'Ureter'
 'Acute Lymphocytic Leukemia' 'Penis' 'Other Myeloid/Monocytic Leukemia'
 'Nose, Nasal Cavity and Middle Ear' 'Bones and Joints' 'Tonsil'
 'Floor of Mouth' 'Complications of Pregnancy, Childbirth, Puerperium'
 'Uterus, NOS' 'Vagina' 'Other Female Genital Organs' 'Vulva'
 'Other Lymphocytic Leukemia' 'Salivary Gland'
 'Trachea, Mediastinum and Other Respiratory Organs'
 'Anus, Anal Canal and Anorectum'
 'Certain Conditions Originating in Perinatal Period']

-------------------------------------------------------------------------------------

['$110,000 - $119,999' '$120,000+' '$100,000 - $109,999'
 '$95,000 - $99,999' '$85,000 - $89,999' '$90,000 - $94,999'
 '$80,000 - $84,999' '$75,000 - $79,999' '$70,000 - $74,999'
 '$65,000 - $69,999' '$60,000 - $64,999' '$55,000 - $59,999'
 '$50,000 - $54,999' '$45,000 - $49,999' '$40,000 - $44,999'
 'Unknown/missing/no match/Not 1990-2024' '< $40,000']

-------------------------------------------------------------------------------------

['Counties in metropolitan areas ge 1 million pop'
 'Counties in metropolitan areas of 250,000 to 1 million pop'
 'Nonmetropolitan counties adjacent to a metropolitan area'
 'Nonmetropolitan counties not adjacent to a metropolitan area'
 'Counties in metropolitan areas of lt 250 thousand pop'
 'Unknown/missing/no match/Not 1990-2024'
 'Unknown/missing/no match (Alaska or Hawaii - Entire State)']

-------------------------------------------------------------------------------------

*Demographical Variables*

In [6]:
#Changed data type of age to string 
df['Age recode with <1 year olds and 90+']=df['Age recode with <1 year olds and 90+'].astype(str)
#Remover 'years' from '70-75 years'
df['Age recode with <1 year olds and 90+']=df['Age recode with <1 year olds and 90+'].str.strip(' years')

#'70-75' -> |70| |75|

age_lower = df['Age recode with <1 year olds and 90+'].str.replace('+', '', regex=False).str.split('-').str[0].astype(int)
age_upper = df['Age recode with <1 year olds and 90+'].str.replace('+', '', regex=False).str.split('-').str[-1].astype(int)

#Created a variable age which stores mid point of given age for calculation on age (mean age etc.)

df['Age']=(age_lower+age_upper)/2
df

,Age recode with <1 year olds and 90+,Sex,Year of diagnosis,"Race and origin recode (NHW, NHB, NHAIAN, NHAPI, Hispanic)",Marital status at diagnosis,Primary Site,Histologic Type ICD-O-3,Combined Summary Stage with Expanded Regional Codes (2004+),Radiation recode,"Chemotherapy recode (yes, no/unk)",RX Summ--Surg Prim Site (1998-2022),Survival months,Vital status recode (study cutoff used),COD to site recode,Median household income inflation adj to 2024,Rural-Urban Continuum Code,Age
0,80-84,Female,2009,Non-Hispanic White,Widowed,160,8490,Regional by direct extension only,None/Unknown,No/Unknown,21,0011,Dead,Esophagus,"$110,000 - $119,999",Counties in metropolitan areas ge 1 million pop,82.0
1,65-69,Female,2022,Non-Hispanic White,Married (including common law),168,8936,Localized only,None/Unknown,No/Unknown,30,0019,Alive,Alive,"$120,000+",Counties in metropolitan areas ge 1 million pop,67.0
2,60-64,Male,2010,Non-Hispanic White,Married (including common law),160,8140,Localized only,None/Unknown,Yes,51,0014,Dead,Esophagus,"$110,000 - $119,999",Counties in metropolitan areas ge 1 million pop,62.0
3,90+,Male,2008,Non-Hispanic White,Widowed,169,8140,Localized only,Refused (1988+),No/Unknown,00,0007,Dead,Miscellaneous Malignant Cancer,"$120,000+",Counties in metropolitan areas ge 1 million pop,90.0
4,75-79,Male,2003,Non-Hispanic Asian or Pacific Islander,Single (never married),162,8480,Blank(s),Beam radiation,Yes,42,0095,Dead,Diseases of Heart,"$100,000 - $109,999",Counties in metropolitan areas ge 1 million pop,77.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
156284,65-69,Female,2023,Non-Hispanic Black,Single (never married),169,8000,Unknown/unstaged/unspecified/DCO,None/Unknown,No/Unknown,Blank(s),Unknown,Dead,Stomach,"$55,000 - $59,999",Nonmetropolitan counties adjacent to a metropo...,67.0
156285,50-54,Male,2023,Non-Hispanic White,Divorced,169,8000,Unknown/unstaged/unspecified/DCO,None/Unknown,No/Unknown,Blank(s),Unknown,Dead,Other Cause of Death,"$55,000 - $59,999",Nonmetropolitan counties adjacent to a metropo...,52.0
156286,70-74,Male,2023,Non-Hispanic White,Married (including common law),169,8000,Unknown/unstaged/unspecified/DCO,None/Unknown,No/Unknown,Blank(s),Unknown,Dead,Chronic Obstructive Pulmonary Disease and Alli...,"$70,000 - $74,999","Counties in metropolitan areas of 250,000 to 1...",72.0
156287,60-64,Male,2023,Non-Hispanic White,Single (never married),169,8000,Unknown/unstaged/unspecified/DCO,None/Unknown,No/Unknown,Blank(s),Unknown,Dead,Stomach,"$70,000 - $74,999","Counties in metropolitan areas of 250,000 to 1...",62.0
156288,50-54,Female,2016,Non-Hispanic Black,Married (including common law),169,8936,Localized only,None/Unknown,Yes,33,0093,Alive,Alive,"$45,000 - $49,999",Counties in metropolitan areas of lt 250 thous...,52.0

*Tumor*

In [7]:
#Replacing the site code with their actual Anatomical site 

primary_sites = {
    160: "Cardia, NOS",
    161: "Fundus of stomach",
    162: "Body of stomach",
    163: "Gastric antrum",
    164: "Pylorus",
    165: "Lesser curvature of stomach, NOS",
    166: "Greater curvature of stomach, NOS",
    168: "Overlapping lesion of stomach",
    169: "Stomach, NOS (Not Otherwise Specified)"
}
df['Primary Site'] = df['Primary Site'].map(primary_sites)
df['Cancer_type']='Stomach'

In [8]:
#Histology codes are replaced with Their Histological family group name.

# Stomach bins
bins =   [0, 8139, 8299, 8499, 8799, 9999]


#Bins work as intervals and labels as value of the code if it falls in that bin.
# If Histologuy code falls between 7999 to 8009 then it will replace it with 'Neoplasms, NOS'.

labels = ["Carcinoma NOS", "Adenocarcinoma", "Mucinous/Signet", "Sarcoma/Rare", "Other"]

df['Histologic Type ICD-O-3'] = pd.cut(
    pd.to_numeric(df['Histologic Type ICD-O-3'], errors='coerce'), 
    bins=bins, 
    labels=labels, 
    ordered=False
)

*Staging*

In [9]:
#Created a mew variable 'Stage' and changed the given categpries in 'Combined Summary Stage with Expanded Regional Codes (2004+)' to [I,II,III,IV].

stage_mapping = {
    "Localized only": "I",
    "Regional by direct extension only": "II",      
    "Regional lymph nodes involved only": "III",
    "Regional by both direct extension and lymph node involvement": "III",
    "Distant site(s)/node(s) involved": "IV",         
    "Unknown/unstaged/unspecified/DCO": "Unknown",
    "Blank(s)": "Unknown"
}
df['Stage']=df['Combined Summary Stage with Expanded Regional Codes (2004+)'].map(stage_mapping)

*Treatment*

In [10]:
#Created a new variable 'Radiation'  and changed the given categpries in 'Radiation recode' to [Radiation,No Radiation,Unknown].

radiation_map = {
    'None/Unknown': 'No',
    'Beam radiation': 'Yes',
    'Radiation, NOS  method or source not specified': 'Yes',
    'Refused (1988+)': 'No',
    'Recommended, unknown if administered': 'Unknown',
    'Radioactive implants (includes brachytherapy) (1988+)': 'Yes',
    'Combination of beam with implants or isotopes': 'Yes',
    'Radioisotopes (1988+)': 'Yes',
}
df['Radiation'] = df['Radiation recode'].map(radiation_map)

In [11]:
#Created a new variable 'Surgery' and changed the given surgery codes in 'RX Summ--Surg Prim Site (1998-2022)' to [Yes,NO,unknown].

surgery_binary_map = {
    # No surgical intervention
    '0': 'No',
    # Surgical interventions (Destruction, Excisions, Resections)
    '12': 'Yes',
    '13': 'Yes',
    '15': 'Yes',
    '19': 'Yes',
    '20': 'Yes',
    '21': 'Yes',
    '22': 'Yes',
    '23': 'Yes',
    '24': 'Yes',
    '25': 'Yes',
    '30': 'Yes',
    '33': 'Yes',
    '45': 'Yes',
    '46': 'Yes',
    '47': 'Yes',
    '48': 'Yes',
    '55': 'Yes',
    '56': 'Yes',
    '65': 'Yes',
    '66': 'Yes',
    '70': 'Yes',
    '80': 'Yes',
    '90': 'Yes',  # Surgery performed, scope unknown
    
    # Missing, uncollected, or unstageable data
    '99': 'Unknown',
    'Blank(s)': 'Unknown'
}
df['surgery']=df['RX Summ--Surg Prim Site (1998-2022)'].map(surgery_binary_map)

In [12]:
s = df['surgery'] == 'Yes'
r = df['Radiation'] == 'Yes'
c = df['Chemotherapy recode (yes, no/unk)'] == 'Yes'

# Define the conditions in order of priority (most specific to least specific)
conditions = [
    s & r & c,
    s & r,
    s & c,
    r & c,
    s,
    r,
    c
]

# Define the corresponding outputs
choices = [
    'Surgery+Radiation+Chemotherapy',
    'Surgery+Radiation',
    'Surgery+Chemotherapy',
    'Radiation+Chemotherapy',
    'Surgery',
    'Radiation',
    'Chemotherapy'
]

# Apply the conditions and choices to create the new column
df['Treatment'] = np.select(conditions, choices, default='Unknown')

*Outcomes*

In [13]:
#Changed survival month data type to numeric from object
df['Survival months']=pd.to_numeric(df['Survival months'],errors='coerce')
#replaced unknown with NaN
df['Survival months']=df['Survival months'].replace('unknown',np.nan)
#Dropped rows with unknkown Survival months
df=df.dropna(subset=['Survival months'])

In [14]:
#Assigned Binary(0,1) to vital status
df['Vital status recode (study cutoff used)']=df['Vital status recode (study cutoff used)'].replace(['Alive','Dead'],[0,1])

C:\Users\ricky\AppData\Local\Temp\ipykernel_22112\2702481694.py:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['Vital status recode (study cutoff used)']=df['Vital status recode (study cutoff used)'].replace(['Alive','Dead'],[0,1])
C:\Users\ricky\AppData\Local\Temp\ipykernel_22112\2702481694.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Vital status recode (study cutoff used)']=df['Vital status recode (study cutoff used)'].replace(['Alive','Dead'],[0,1])

*SocioEconomic*

In [15]:
#Changed datatype to string
df['Median household income inflation adj to 2024']=df['Median household income inflation adj to 2024'].astype(str)

#'$70,000 - $74,999' -> '70000 - 74999' 
clean_inc = df['Median household income inflation adj to 2024'].str.replace('$', '', regex=False).str.replace(',', '', regex=False).str.replace('+', '', regex=False).str.replace('<', '', regex=False).str.strip()

#'70000 - 74999' -> '70000' | '74999' 
lower = clean_inc.str.split('-').str[0]
upper = clean_inc.str.split('-').str[-1]
# '70000' ->700000 (string to numeric) 
inc_lower=pd.to_numeric(lower,errors='coerce')
inc_upper=pd.to_numeric(upper,errors='coerce')

#Created a variable income which stores mid point of given income for calculation on income (mean inclome etc.)
df['Income']=(inc_lower+inc_upper)/2
df.sample(7)

C:\Users\ricky\AppData\Local\Temp\ipykernel_22112\7351343.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Median household income inflation adj to 2024']=df['Median household income inflation adj to 2024'].astype(str)
C:\Users\ricky\AppData\Local\Temp\ipykernel_22112\7351343.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Income']=(inc_lower+inc_upper)/2

,Age recode with <1 year olds and 90+,Sex,Year of diagnosis,"Race and origin recode (NHW, NHB, NHAIAN, NHAPI, Hispanic)",Marital status at diagnosis,Primary Site,Histologic Type ICD-O-3,Combined Summary Stage with Expanded Regional Codes (2004+),Radiation recode,"Chemotherapy recode (yes, no/unk)",...,COD to site recode,Median household income inflation adj to 2024,Rural-Urban Continuum Code,Age,Cancer_type,Stage,Radiation,surgery,Treatment,Income
60587,75-79,Female,2022,Hispanic (All Races),Married (including common law),Body of stomach,Mucinous/Signet,Localized only,None/Unknown,No/Unknown,...,Alive,"$90,000 - $94,999",Counties in metropolitan areas ge 1 million pop,77.0,Stomach,I,No,Yes,Surgery,92499.5
134033,60-64,Male,2008,Non-Hispanic White,Married (including common law),"Cardia, NOS",Adenocarcinoma,Regional by direct extension only,None/Unknown,Yes,...,Stomach,"$75,000 - $79,999",Counties in metropolitan areas ge 1 million pop,62.0,Stomach,II,No,NaN,Chemotherapy,77499.5
155896,85-89,Male,2023,Non-Hispanic White,Married (including common law),Gastric antrum,Adenocarcinoma,Unknown/unstaged/unspecified/DCO,Refused (1988+),No/Unknown,...,Alive,"$70,000 - $74,999",Counties in metropolitan areas ge 1 million pop,87.0,Stomach,Unknown,No,Unknown,Unknown,72499.5
90919,60-64,Male,2012,Non-Hispanic White,Married (including common law),"Cardia, NOS",Adenocarcinoma,Regional lymph nodes involved only,Beam radiation,Yes,...,Diseases of Heart,"$70,000 - $74,999",Counties in metropolitan areas ge 1 million pop,62.0,Stomach,III,Yes,NaN,Radiation+Chemotherapy,72499.5
80332,50-54,Female,2003,Non-Hispanic White,Married (including common law),"Stomach, NOS (Not Otherwise Specified)",Adenocarcinoma,Blank(s),None/Unknown,No/Unknown,...,Alive,"$110,000 - $119,999",Counties in metropolitan areas ge 1 million pop,52.0,Stomach,Unknown,No,NaN,Unknown,114999.5
71976,55-59,Male,2022,Hispanic (All Races),Married (including common law),"Stomach, NOS (Not Otherwise Specified)",Adenocarcinoma,Distant site(s)/node(s) involved,None/Unknown,Yes,...,Stomach,"$90,000 - $94,999",Counties in metropolitan areas ge 1 million pop,57.0,Stomach,IV,No,NaN,Chemotherapy,92499.5
89359,55-59,Male,2011,Non-Hispanic White,Married (including common law),"Cardia, NOS",Adenocarcinoma,Distant site(s)/node(s) involved,None/Unknown,No/Unknown,...,Stomach,"$95,000 - $99,999",Counties in metropolitan areas ge 1 million pop,57.0,Stomach,IV,No,NaN,Unknown,97499.5

In [16]:
a=df.columns
a
for i in a:
    print(f'{df[i].value_counts()}')
    print(f'{df[i].value_counts().sum()}')
    print("")
    print('-------------------------------------------------------------------------------------')
    print("")

Age recode with <1 year olds and 90+
70-74    21084
65-69    20375
75-79    20136
60-64    17553
80-84    16735
55-59    14266
85-89    10919
50-54    10551
45-49     7165
90+       5625
40-44     4539
35-39     2796
30-34     1576
25-29      704
20-24      325
15-19      103
10-14       38
01-04        6
05-09        4
00           3
Name: count, dtype: int64
154503

-------------------------------------------------------------------------------------

Sex
Male      92626
Female    61877
Name: count, dtype: int64
154503

-------------------------------------------------------------------------------------

Year of diagnosis
2023    8410
2022    8129
2021    7973
2019    6898
2018    6881
2017    6845
2015    6614
2014    6609
2016    6568
2020    6567
2012    6427
2013    6423
2010    6213
2011    6167
2009    6159
2004    5912
2007    5901
2008    5824
2006    5736
2005    5725
2002    5693
2003    5670
2000    5649
2001    5510
Name: count, dtype: int64
154503

-------------------------------------------------------------------------------------

Race and origin recode (NHW, NHB, NHAIAN, NHAPI, Hispanic)
Non-Hispanic White                            80592
Hispanic (All Races)                          29910
Non-Hispanic Asian or Pacific Islander        21761
Non-Hispanic Black                            20262
Non-Hispanic American Indian/Alaska Native     1401
Non-Hispanic Unknown Race                       577
Name: count, dtype: int64
154503

-------------------------------------------------------------------------------------

Marital status at diagnosis
Married (including common law)    85045
Widowed                           23368
Single (never married)            22926
Divorced                          12207
Unknown                            8775
Separated                          1687
Unmarried or Domestic Partner       495
Name: count, dtype: int64
154503

-------------------------------------------------------------------------------------

Primary Site
Cardia, NOS                               42108
Stomach, NOS (Not Otherwise Specified)    29213
Gastric antrum                            25649
Body of stomach                           17042
Lesser curvature of stomach, NOS          11328
Overlapping lesion of stomach             10500
Fundus of stomach                          8000
Greater curvature of stomach, NOS          6786
Pylorus                                    3877
Name: count, dtype: int64
154503

-------------------------------------------------------------------------------------

Histologic Type ICD-O-3
Adenocarcinoma     105202
Mucinous/Signet     25265
Other               14683
Carcinoma NOS        8591
Sarcoma/Rare          762
Name: count, dtype: int64
154503

-------------------------------------------------------------------------------------

Combined Summary Stage with Expanded Regional Codes (2004+)
Distant site(s)/node(s) involved                                44675
Localized only                                                  41107
Blank(s)                                                        22522
Unknown/unstaged/unspecified/DCO                                13988
Regional lymph nodes involved only                              13458
Regional by both direct extension and lymph node involvement    12570
Regional by direct extension only                                6183
Name: count, dtype: int64
154503

-------------------------------------------------------------------------------------

Radiation recode
None/Unknown                                             122212
Beam radiation                                            28854
Refused (1988+)                                            1701
Recommended, unknown if administered                       1121
Radiation, NOS  method or source not specified              493
Combination of beam with implants or isotopes                45
Radioactive implants (includes brachytherapy) (1988+)        40
Radioisotopes (1988+)                                        37
Name: count, dtype: int64
154503

-------------------------------------------------------------------------------------

Chemotherapy recode (yes, no/unk)
No/Unknown    88302
Yes           66201
Name: count, dtype: int64
154503

-------------------------------------------------------------------------------------

RX Summ--Surg Prim Site (1998-2022)
00          78242
30          15471
32          10483
Blank(s)     8410
51           7245
42           4984
27           3641
61           3606
33           3174
26           3019
52           2375
50           2161
31           2051
62           1854
40           1406
20           1296
99           1057
41            772
63            757
90            722
60            635
80            399
22            388
24             84
12             48
10             42
23             40
25             40
14             33
11             27
13             21
21             20
Name: count, dtype: int64
154503

-------------------------------------------------------------------------------------

Survival months
0.0      14806
1.0      11538
2.0       8926
3.0       6718
4.0       5946
         ...
286.0       17
271.0       16
285.0       16
283.0       16
284.0       13
Name: count, Length: 288, dtype: int64
154503

-------------------------------------------------------------------------------------

Vital status recode (study cutoff used)
1    114505
0     39998
Name: count, dtype: int64
154503

-------------------------------------------------------------------------------------

COD to site recode
Stomach                                               65326
Alive                                                 39998
Esophagus                                             14719
Diseases of Heart                                      6162
Other Cause of Death                                   4473
                                                      ...
Floor of Mouth                                            2
Anus, Anal Canal and Anorectum                            2
Trachea, Mediastinum and Other Respiratory Organs         2
Other Male Genital Organs                                 1
Certain Conditions Originating in Perinatal Period        1
Name: count, Length: 89, dtype: int64
154503

-------------------------------------------------------------------------------------

Median household income inflation adj to 2024
$75,000 - $79,999                         22172
$100,000 - $109,999                       16163
$85,000 - $89,999                         14113
$120,000+                                 13840
$80,000 - $84,999                         13190
$90,000 - $94,999                         12273
$110,000 - $119,999                       11399
$70,000 - $74,999                         10706
$65,000 - $69,999                          9624
$95,000 - $99,999                          9066
$60,000 - $64,999                          5962
$55,000 - $59,999                          5753
$50,000 - $54,999                          4859
$45,000 - $49,999                          2761
$40,000 - $44,999                          1506
< $40,000                                  1094
Unknown/missing/no match/Not 1990-2024       22
Name: count, dtype: int64
154503

-------------------------------------------------------------------------------------

Rural-Urban Continuum Code
Counties in metropolitan areas ge 1 million pop                 97796
Counties in metropolitan areas of 250,000 to 1 million pop      30093
Counties in metropolitan areas of lt 250 thousand pop           10593
Nonmetropolitan counties adjacent to a metropolitan area         9280
Nonmetropolitan counties not adjacent to a metropolitan area     6300
Unknown/missing/no match (Alaska or Hawaii - Entire State)        419
Unknown/missing/no match/Not 1990-2024                             22
Name: count, dtype: int64
154503

-------------------------------------------------------------------------------------

Age
72.0    21084
67.0    20375
77.0    20136
62.0    17553
82.0    16735
57.0    14266
87.0    10919
52.0    10551
47.0     7165
90.0     5625
42.0     4539
37.0     2796
32.0     1576
27.0      704
22.0      325
17.0      103
12.0       38
2.5         6
7.0         4
0.0         3
Name: count, dtype: int64
154503

-------------------------------------------------------------------------------------

Cancer_type
Stomach    154503
Name: count, dtype: int64
154503

-------------------------------------------------------------------------------------

Stage
IV         44675
I          41107
Unknown    36510
III        26028
II          6183
Name: count, dtype: int64
154503

-------------------------------------------------------------------------------------

Radiation
No         123913
Yes         29469
Unknown      1121
Name: count, dtype: int64
154503

-------------------------------------------------------------------------------------

surgery
Yes        21703
Unknown     9467
Name: count, dtype: int64
31170

-------------------------------------------------------------------------------------

Treatment
Unknown                           69914
Chemotherapy                      36737
Radiation+Chemotherapy            21774
Surgery                           13720
Surgery+Chemotherapy               4663
Radiation                          4375
Surgery+Radiation+Chemotherapy     3027
Surgery+Radiation                   293
Name: count, dtype: int64
154503

-------------------------------------------------------------------------------------

Income
77499.5     22172
104999.5    16163
87499.5     14113
120000.0    13840
82499.5     13190
92499.5     12273
114999.5    11399
72499.5     10706
67499.5      9624
97499.5      9066
62499.5      5962
57499.5      5753
52499.5      4859
47499.5      2761
42499.5      1506
40000.0      1094
Name: count, dtype: int64
154481

-------------------------------------------------------------------------------------

In [17]:
df = df.drop(columns=['Unnamed: 0'], errors='ignore')
df.to_csv('Stomach_Clean.csv', index=False)
print("Ready for analysis!")
df.info()

Ready for analysis!
<class 'pandas.core.frame.DataFrame'>
Index: 154503 entries, 0 to 156288
Data columns (total 23 columns):
 #   Column                                                       Non-Null Count   Dtype
---  ------                                                       --------------   -----
 0   Age recode with <1 year olds and 90+                         154503 non-null  object
 1   Sex                                                          154503 non-null  object
 2   Year of diagnosis                                            154503 non-null  int64
 3   Race and origin recode (NHW, NHB, NHAIAN, NHAPI, Hispanic)   154503 non-null  object
 4   Marital status at diagnosis                                  154503 non-null  object
 5   Primary Site                                                 154503 non-null  object
 6   Histologic Type ICD-O-3                                      154503 non-null  category
 7   Combined Summary Stage with Expanded Regional Codes (2004+)  154503 non-null  object
 8   Radiation recode                                             154503 non-null  object
 9   Chemotherapy recode (yes, no/unk)                            154503 non-null  object
 10  RX Summ--Surg Prim Site (1998-2022)                          154503 non-null  object
 11  Survival months                                              154503 non-null  float64
 12  Vital status recode (study cutoff used)                      154503 non-null  int64
 13  COD to site recode                                           154503 non-null  object
 14  Median household income inflation adj to 2024                154503 non-null  object
 15  Rural-Urban Continuum Code                                   154503 non-null  object
 16  Age                                                          154503 non-null  float64
 17  Cancer_type                                                  154503 non-null  object
 18  Stage                                                        154503 non-null  object
 19  Radiation                                                    154503 non-null  object
 20  surgery                                                      31170 non-null   object
 21  Treatment                                                    154503 non-null  object
 22  Income                                                       154481 non-null  float64
dtypes: category(1), float64(3), int64(2), object(17)
memory usage: 27.3+ MB